dev(PasswordCreationInput): create password creation input component
kronostechnologies/design-elements pull request #389
Opened 2021-12-13 21:11 UTC by alexbrillant

## PR Description
[DS-153](https://jira.equisoft.com/browse/DS-153)
Component pour la création de password avec des validations (optionnelles). 

<img width="266" alt="Capture d’écran, le 2021-12-13 à 16 06 35" src="https://user-images.githubusercontent.com/19400226/145888790-6687ac01-579a-4c85-a1b4-715d80be214b.png">

```jsx
export const CustomValidations: Story = () => (
    <>
        <PasswordCreationInput
            validations={[
                {
                    label: 'Contains number',
                    isValid: (password) => /\d/.test(password),
                },
                {
                    label: 'Minimum 8 characters.',
                    isValid: isLongEnough(8),
                },
                {
                    label: 'Minimum one uppercase letter.',
                    isValid: hasAnUpperCaseLetter,
                },
                {
                    label: 'Minimum one lowercase letter.',
                    isValid: hasALowerCaseLetter,
                },
            ]}
            onChange={(event: ChangeEvent<HTMLInputElement>, isValid: boolean) => {
                console.log(event);
                console.log(isValid);
            }}
        />
    </>
);
```

2021-12-14 17:02 UTC, LarryMatte requested changes
Quelques modifications...
Tu peux surement utiliser le _TextInput_ du DS pour ton `input`.
Ca va venir régler quelques problèmes que je n'ai pas commentés.

Je repasserai faire un tour quand ce sera fait.

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +            <label>{t('create-password')}</label>
Il faudrait utiliser le component `FieldContainer` pour wrapper ton input. C'est à partir de ce component qu'on contrôle le label, hint, etc.

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +            <div id="idHint" aria-live="assertive" aria-hidden="true" aria-atomic="true">
Pour les ids j'utiliserais un uuid avec un useMemo pour diminuer les chances d'avoir le même id qu'un autre élément dans une page.

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    name="password"
Il faudrait exposer les props `id` et `name` aux utilisateurs DS.

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                id="idPasswordStrength"
Same, je ferais avec un uuid + useMemo

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        const wrapper = mountWithProviders(
J'ai l'impression que ce test pourrait être en `shallow`

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +    });
Il devrait y avoir un blank space entre le `mount` et le `simulate`

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +    test('sets password strength to weak when there is at least 8 characters', () => {
Je changerais le nom du test pour `'sets password strength to weak when there is only 8 characters'`

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength-meter.tsx
> +    }};
Tu pourrais te faire une fonction `getProgressBarBackgroundColor`. Si tu veux un exemple on en utilise dans `global-banner.tsx`

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength-meter.tsx
> +        <PasswordMeterContainer id="idPasswordMeter">
Le `id` me semble useless ici

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength-meter.tsx
> +export function PasswordStrengthMeter({ strength }: PasswordStrengthMeterProps): ReactElement {
J'utiliserais `VoidFunctionComponent`

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength.ts
> +    if (password) {
Je mettrais un blank space entre les variables et le reste du code

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength.ts
> +}
À toi de voir, mais je crois que j'aurais fait les conditons dans l'ordre inverse avec des return pour éviter de faire des réassignements de variables useless.

```ts
export function getPasswordStrength(password: string, t: TFunction): { label: string; strength: PasswordStrength } {
    const passwordLongEnough = isLongEnough(8)(password);
    const passwordHasUpperCaseLetter = hasAnUpperCaseLetter(password);
    const passwordHasLowerCaseLetter = hasALowerCaseLetter(password);

    if (passwordLongEnough && passwordHasUpperCaseLetter && passwordHasLowerCaseLetter) {
        if (password.length >= 12) {
            return {
                label: t('password-is') + t('strong'),
                strength: PasswordStrength.Strong,
            };
        }
        return {
            label: t('password-is') + t('good'),
            strength: PasswordStrength.Good,
        };
    }

    if (passwordLongEnough && (passwordHasUpperCaseLetter || passwordHasLowerCaseLetter)) {
        return {
            label: t('password-is') + t('fair'),
            strength: PasswordStrength.Fair,
        };
    }

    if (password) {
        return {
            label: t('password-is') + t('weak'),
            strength: PasswordStrength.Weak,
        };
    }

    return {
        label: '',
        strength: PasswordStrength.None,
    };
}
```

2021-12-16 19:45 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength.ts
> +export function getPasswordStrength(password: string, t: TFunction): { label: string; strength: PasswordStrength } {
On pourrait faire une interface pour la return value

2021-12-16 19:45 UTC, maxime-gendron commented on packages/storybook/stories/password-creation-input.stories.tsx
> +        }}
Tu peux utiliser `console.info()` pour éviter de devoir mettre les `// eslint-disable`

2021-12-16 20:29 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +const StyledUl = styled.ul`
pas possible de réutiliser les validations en prop sur le data inputs pour l'instant

2021-12-16 20:40 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-strength.ts
> +}
j'aime mieux comme je l'ai fait. je vais laisser ça comme ça.

2021-12-16 20:44 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-strength-meter.tsx
> +        <PasswordMeterContainer id="idPasswordMeter">
c'était dans le code html vanille de la story. jamais useless des id tant qu'à moi.

2021-12-16 22:29 UTC, closed without merging