feat(FieldContainer): add tooltip next to label with tooltipLabel prop
kronostechnologies/design-elements pull request #392
Opened 2021-12-17 17:00 UTC by maxime-gendron

## PR Description
Cette PR ajoute la possibilité de mettre un tooltip à côté du label des inputs. Cette feature sera utilisé dans CPanel2. Il est donc maintenant possible de passer la prop `tooltipLabel` au component `FieldContainer` pour ajouter un tooltip.

J'ai ajouté la prop `tooltipLabel` à tous les inputs utilisants `FieldContainer`. J'ai aussi profité de l'occasion pour faire des refactor légers.

2021-12-21 00:59 UTC, meriouma commented on packages/react/src/components/datepicker/datepicker.tsx
> +                tooltipLabel={tooltipLabel}
C'est quoi le rôle du `hint` vs le `tooltip`?

2021-12-21 16:23 UTC, maxime-gendron commented on packages/react/src/components/datepicker/datepicker.tsx
> +                tooltipLabel={tooltipLabel}
Je ne suis pas certain, mais j'ai l'impression qu'un tooltip est plus détaillé qu'un hint.

2021-12-21 17:22 UTC, meriouma commented on packages/react/src/components/datepicker/datepicker.tsx
> +                tooltipLabel={tooltipLabel}
Dans le cpanel2, c'est quoi le genre de texte qui va dans le tooltip?

2021-12-21 19:22 UTC, maxime-gendron commented on packages/react/src/components/datepicker/datepicker.tsx
> +                tooltipLabel={tooltipLabel}
Dans le ticket [ACC-985](https://jira.equisoft.com/browse/ACC-985?workflowName=DATAK+Dev+Workflow+-+2.0&stepId=33)

> Le champs "Cellulaire" comporte un tooltip. Ce tooltip doit contenir le texte suivant:
>
> - [FR] Le numéro de téléphone mobile est utilisé pour la réinitialisation de mot de passe par SMS.
> - [EN]The mobile phone number is used for password reset via SMS.

2022-01-04 15:27 UTC, LarryMatte commented on packages/react/src/components/datepicker/datepicker.tsx
> +                tooltipLabel={tooltipLabel}
Le hint donne un "hint" sur comment bien remplir le champ, le Tooltip donne de l'info supplémentaire qui ne requiert pas à l'utilisateur de le consulter pour bien remplis le champ.
exemple ordinaire mais c'est le 1er que j'ai en tête: 
**Label:** Id number
**Hint:** l'Id correspond au # sur votre carte commençant par A143-...
**Tooltip:** Nous avons besoin de votre Id pour blah blah blah.

2022-01-04 15:36 UTC, LarryMatte requested changes

2022-01-04 15:36 UTC, LarryMatte commented on packages/react/src/components/label/label.tsx
> +            {tooltipLabel && <StyledTooltip label={tooltipLabel} />}
Est-ce que tu peux sortir le tooltip à l'extérieur du `label`?

2022-01-04 15:56 UTC, maxime-gendron commented on packages/react/src/components/label/label.tsx
> +            {tooltipLabel && <StyledTooltip label={tooltipLabel} />}
Je pourrais le faire en wrappant le label dans un div, mais je ne suis pas certain si c'est mieux 🤔 
```jsx
    <div>
        <StyledLabel className={className} htmlFor={forId} isMobile={isMobile}>
            {children}
        </StyledLabel>
        {tooltipLabel && <StyledTooltip label={tooltipLabel} />}
    </div>
```

2022-01-04 15:58 UTC, maxime-gendron commented on packages/react/src/components/label/label.tsx
> +            {tooltipLabel && <StyledTooltip label={tooltipLabel} />}
C'est probablement mieux considérant que le screen reader va lire le contenu du label et ensuite le tooltip au prochain TAB.

2022-01-04 16:11 UTC, LarryMatte commented on packages/react/src/components/label/label.tsx
> +            {tooltipLabel && <StyledTooltip label={tooltipLabel} />}
ca pourrait effectivement être une option

2022-01-04 16:24 UTC, maxime-gendron commented on packages/react/src/components/label/label.tsx
> +            {tooltipLabel && <StyledTooltip label={tooltipLabel} />}
Je vais mettre un div conditionnel. S'il n'y a pas de tooltip il n'y aura pas de div useless.

2022-01-04 17:15 UTC, meriouma approved these changes

2022-01-04 17:15 UTC, meriouma commented on packages/react/src/components/field-container/field-container.tsx
> +    tooltipLabel?: string;
Est-ce que ça se peut qu'on ait à passer d'autres props du Tooltip? Si oui, çe serait peut-être mieux de passer une prop genre `tooltip: TooltipProps` pour éviter un potentiel breaking change

2022-01-04 17:51 UTC, maxime-gendron commented on packages/react/src/components/field-container/field-container.tsx
> +    tooltipLabel?: string;
Bonne idée je vais ajouter ce changement

2022-01-04 18:21 UTC, LarryMatte approved these changes
LGTM

2022-01-04 20:14 UTC, merged