dev(PasswordCreationInput): create password creation input component
kronostechnologies/design-elements pull request #393
Opened 2021-12-17 18:48 UTC by alexbrillant

[DS-153](https://jira.equisoft.com/browse/DS-153)

![Capture d’écran, le 2021-12-17 à 13 46 51](https://user-images.githubusercontent.com/19400226/146593370-6ea3a072-05fd-4fb7-9761-c8a171626b5e.png)

2021-12-22 15:31 UTC, maxime-gendron reviewed
Les styles sont un peu off par rapport au maquettes:
![image](https://user-images.githubusercontent.com/53787300/147116158-80b52ab7-212c-4cc0-a2fe-e95202dcaeff.png)

J'utilise le l'extension chrome [PerfectPixel](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en) pour faire la comparaison.

Aussi, les conditions restent de couleur noire alors qu'elles devraient être rouge et verte:
![image](https://user-images.githubusercontent.com/53787300/147116359-0fa991c2-265d-48b3-b402-315a098f0bef.png)

2021-12-22 15:31 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +    test('sets password strength to good when there is at least 8 characters and at least one uppercase', () => {
Le nom du test devrait probablement être changé pour:
```suggestion
    test('sets password strength to good when there is at least 8 characters, one lowercase and one uppercase', () => {
```

2021-12-22 15:31 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +    test('sets password strength to strong when there is at least 8 characters and at least one uppercase', () => {
Devrait probablement être changé pour:
```suggestion
    test('sets password strength to strong when there is more than 8 characters and at least one lowercase and one uppercase', () => {
```

2021-12-22 15:31 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-strength-meter.tsx
> +    { isFilled, passwordStrength, theme }: StyledProps<{ isFilled: boolean; passwordStrength: PasswordStrengthEnum }>,
J'ajouterais une interface `ProgressBarProps` afin d'éviter de répéter ce type
```ts
{ isFilled: boolean; passwordStrength: PasswordStrengthEnum }
```

2021-12-22 15:31 UTC, maxime-gendron commented on packages/react/src/i18n/translations.ts
> +            'password-is': 'La password est: ',
Je crois que ça se traduirais plus à `Force du mot de passe:`

2021-12-22 15:31 UTC, maxime-gendron commented on packages/react/src/i18n/translations.ts
> +            'min-8-characters': 'Minimum 8 charactères',
typo
```suggestion
            'min-8-characters': 'Minimum 8 caractères',
```

2021-12-22 15:31 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    aria-label={t('show-password')}
Le aria-label devrait probablement changer entre `Montrer` et `Cacher` le mot de passe selon la prochaine action du bouton.

2021-12-22 15:31 UTC, maxime-gendron commented on packages/storybook/stories/password-creation-input.stories.tsx
> +import React, { ChangeEvent } from 'react';
Pas besoin de l'import `React`

2021-12-22 15:31 UTC, maxime-gendron commented on packages/storybook/stories/password-creation-input.stories.tsx
> +);
Pas besoin du fragment

2021-12-22 15:31 UTC, maxime-gendron commented on packages/storybook/stories/password-creation-input.stories.tsx
> +    <>
Pas besoin du fragment

2022-01-04 15:03 UTC, alexbrillant commented
@maxime-gendron les conditions sont déjà rouges et verte je sais pas quel version de code tu utilisais ? 
<img width="1100" alt="Capture d’écran, le 2022-01-04 à 10 03 21" src="https://user-images.githubusercontent.com/19400226/148078947-dac05dc7-ac6f-4365-bc0d-fc1b7ce27af0.png">

2022-01-07 16:55 UTC, maxime-gendron reviewed
Last review 🔍  Take care my guy! ❤️

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +`;
Il y a une margin-bottom qui apparait sur `:nth-child(1)` quand les critères sont tous remplis.

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +    margin-bottom: 12px;
Pour utiliser les variables css on pourrait changer pour
```suggestion
    margin-bottom: calc(var(--spacing-1x) * 1.5);
```

2022-01-07 16:55 UTC, maxime-gendron commented on packages/storybook/stories/password-creation-input.stories.tsx
> +export const CustomValidations: Story = () => (
On pourrait importer `rawCodeParameters` des utils storybook et ajouter `CustomValidation.parameters = rawCodeParameters;` à la fin de la story pour voir l'ensemble du code de la story dans la doc storybook.

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')(event);
Tu pourrais utiliser `.simulate`
```suggestion
        getByTestId(wrapper, 'password-input').simulate('change',  { target: { name: 'password', value: password } });
```

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        expect(onChange).toHaveBeenCalledWith(expect.objectContaining(event), false);
J'isolerais le callback `onChange` dans chaque tests pour être certain que ce n'est pas un autre test qui fait passer le suivant.

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')(event);
simulate

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        expect(onChange).toHaveBeenCalledWith(expect.objectContaining(event), true);
isoler le callback onChange

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        expect(onChange).toHaveBeenCalledWith(expect.objectContaining(event), true);
same

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        expect(onChange).toHaveBeenCalledWith(expect.objectContaining(event), false);
same

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')({ target: { value: '12345678' } });
simulate

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')({ target: { value: 'P2345678' } });
same

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')({ target: { value: 'Pe234567' } });
same

2022-01-07 16:55 UTC, maxime-gendron commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')({ target: { value: 'Pe2345678910' } });
same

2022-01-07 18:25 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +        getByTestId(wrapper, 'password-input').prop('onChange')(event);
j'avais essayé et ça fonctionne pas avec simulate. je sais pas trop pourquoi. won't fix 
<img width="1047" alt="Capture d’écran, le 2022-01-07 à 13 23 28" src="https://user-images.githubusercontent.com/19400226/148589470-5c4dcb56-bd2e-4666-8a0e-823e68e9201f.png">

2022-01-10 17:26 UTC, LarryMatte requested changes
Quelques modifications ici et là

2022-01-10 17:26 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-condition.tsx
> +    height: 20px;
Si tu fais les modifications dans le `StyledIcon` et le `StyledLi` (le `align-center` pour un `flex-start`et que tu enlèves le `20px`) et que tu ajoutes un `margin-bottom: 2px;`, tu devrais arriver proche de ce que nous cherchons comme résultat.

2022-01-10 17:26 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    aria-describedby={`idHint ${passwordStrengthUuid}`}
Le `aria-describedby` et le `aria-invalid` ne semble pas fonctionner. Il n'apparaissent pas quand j'inspecte le composant.

2022-01-10 20:00 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +            <div
<img width="457" alt="Capture d’écran, le 2022-01-10 à 14 59 16" src="https://user-images.githubusercontent.com/19400226/148831172-9b33f2ec-a6c6-4df6-a5f9-c7da2a5070c0.png">

2022-01-17 19:37 UTC, LarryMatte requested changes

2022-01-17 19:37 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    ariaDescribedBy={`idHint ${passwordStrengthUuid}`}
L'`Id` devrait être celui du "hint" donc de la liste de condition. (ton `hintUuid` si je ne me trompe pas.)

2022-01-17 19:37 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        <StyledFieldContainer
Le `for="..."` du `label` utilise l'`Id` du message d'erreur alors qu'il devrait utiliser celui de l'`input`

2022-01-17 19:37 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    autoComplete="new-password"
il semble être à `off` quand je regarde la code.
<img width="870" alt="Screen Shot 2022-01-17 at 2 26 42 PM" src="https://user-images.githubusercontent.com/3722754/149827350-9453d5ac-4663-4de8-a57e-9a598cbd3ae9.png">

2022-01-17 19:37 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    ariaInvalid={false}
Le `false` doit s'adapter selon ce qui est inscrit dans le champ.
Si le champ est invalid, il faut que le `aria-invalid="true"`, 
s'il est valid = `aria-invalid="false"`
Présentement il reste toujours à false.

2022-01-19 17:09 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    autoComplete="new-password"
![Capture d’écran, le 2022-01-19 à 12 08 37](https://user-images.githubusercontent.com/19400226/150179759-8b218bd6-9388-45e2-bfab-6e4b1b10fb95.png)
étrange je le vois moi peut-être à cause du id que je viens de corriger

2022-01-24 23:12 UTC, meriouma reviewed
Tu pourrais ajouter des tests pour tes sub-components. Il y en a seulement pour `password-creation-input`

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +    ariaInvalid?: boolean;
Ce serait peut-être mieux de faire comme les dataAttributes plutôt que de faire le mapping des `aria-*` manuellement

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/i18n/translations.ts
> +            error: 'Error,',
La virgule devrait probablement pas être dans la traduction si c'est dans `common`?

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/i18n/translations.ts
> +            error: 'Erreur,',
Same

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/i18n/translations.ts
> +            'password-is': 'Password strength: ',
`password-is` je suis pas certain que ce soit un bon nom de clé

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/components/password-creation-input/validation-condition.ts
> +export const hasALowerCaseLetter = (password: string): boolean => password.toUpperCase() !== password;
Ça prendrait des tests

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/components/password-creation-input/validation-condition.ts
> +export const isLongEnough = (minLength = 8) => (password: string): boolean => password.length >= minLength;
Les const vont bien dans les functional components parce que ça permet de mieux les typer et on a pas le choix avec certains hooks, mais quand c'est des fonctions, utilise plutôt la syntaxe `function`, ça améliore la visibilité. 
```
type PasswordValidationFunction = (password: string) => boolean;

export function isLongEnough(minLength = 8): PasswordValidationFunction {
    return (password) => password.length >= minLength;
}
```

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/components/password-creation-input/validation-condition.ts
> +export const isLongEnough = (minLength = 8) => (password: string): boolean => password.length >= minLength;
Peut-être renommer en `hasMinLength`?

2022-01-24 23:12 UTC, meriouma commented on packages/react/src/components/text-input/styles/inputs.tsx
> +    padding: 3px var(--spacing-1x);
Ça me semble un red flag. C'est pas un super bon signe si on a un padding qui n'est plus un multiple des spacings ici. C'est pour corriger quel espacement? Je sais pas si tu avais remarqué, mais ça a modifié tous les inputs.

2022-01-26 15:28 UTC, alexbrillant commented on packages/react/src/components/text-input/styles/inputs.tsx
> +    padding: 3px var(--spacing-1x);
demande de larry

2022-01-27 18:43 UTC, meriouma commented on packages/react/src/components/text-input/styles/inputs.tsx
> +    padding: 3px var(--spacing-1x);
@LarryMatte ?

2022-01-27 21:10 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-condition.tsx
> +const StyledLi = styled.li<{ isEmpty: boolean, isSuccess: boolean }>`
je vois pas grand raison que ça change mais ok

2022-01-27 21:15 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-condition.tsx
> +    condition: ValidationCondition;
la sous props est nécessaire étant donné que les conditions sont utilisés à l'extérieur de ce sous components et c'est une liste de ValidationCondition qui est passé au component au début. won'f fix

2022-01-27 21:24 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-condition.tsx
> +    condition: ValidationCondition;
ah ouin je pourrais ajouter 2 props is valid et label boff... mais bon je vais le faire. 
un component de présentation (dumb) peut très bien appeler des fonctions pour l'affichage sans problème. il ne doit juste pas gérer de state ;)

2022-01-27 21:26 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-condition.tsx
> +    condition: ValidationCondition;
je l'ai fait, mais je trouve pas que c'est une bonne solution.

2022-01-27 22:04 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        background-position: calc(100% - 40px) !important;
mm c'était pour adresser last pass justement. ça s'affichait bien de mon côté il me semble je vais vérifier. quel OS et navigateur tu utilise ?

2022-01-27 22:10 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        onChange(event, newPasswordIsValid);
le new password, on est capable d'aller le chercher avec event.target.value. je comprends pas trop pourquoi ça serait mieux ?

2022-01-27 22:17 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        background-position: calc(100% - 40px) !important;
Chrome sur Windows. Le visuel est correct, c'est la fonctionnalité qui l'est moins. Faut que je clique entre l'icône de LastPass et celle du component pour que le popup de LastPass s'ouvre. Quand je clique directement sur l'icône ça fait rien.

2022-01-27 22:21 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        onChange(event, newPasswordIsValid);
Pour simplifier la vie au consommateur. Il reçoit la valeur, pis si l'event l'intéresse, il peut toujours le recevoir en utilisant le 3e param, mais il est pas obligé. Ça me fait penser qu'il faudrait éventuellement le changer pour le TextInput aussi

2022-01-28 16:40 UTC, LarryMatte commented on packages/react/src/components/text-input/styles/inputs.tsx
> +    padding: 3px var(--spacing-1x);
Il y avait une différence de size entre le visuel de Figma et le composant _input_, ce qui venait causer du trouble avec tous les autres inputs qui sont basés sur le composant "parent".
Un genre de `34px` au lieu de `32px` ou un truc du genre. (il ajoute les `2px` du border top/bottom).
Modifier le `line-height` n'était pas la solution et pour que le `box-sizing` fonctionne il aurait fallu lui ajouter un `height: 32px;` et je ne suis pas fan ou un `min-height: 32px;`.
Vous pouvez remplacer le padding 3px -> 0 et ajouter le min-height, ça devrait être suffisant.

2022-02-01 20:44 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        onChange(event, newPasswordIsValid);
je trouve que ça complexifie la vie au consommateur plus que d'autres choses. n'importe quel dev frontend s'attends à recevoir un event au premier paramètre dans un onChange et non 3 paramètre et event à la fin

2022-02-14 17:52 UTC, LarryMatte requested changes
encore le `off` dans l'autocomplete et enlever le `focusable` sur l'icône d'alert après la vie est belle pour moi

2022-02-14 17:52 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-rule.tsx
> +                <StyledIcon
Il y a un `focusable="false"` dans la DOM de l'icone d'alert alors qu'il ne devrait pas y en avoir.

2022-02-14 17:52 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    autoComplete="new-password"
j'ai encore le `off` de mon côté.

2022-02-14 19:53 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-rule.tsx
> +                <StyledIcon
le focusable="false" est seulement sur l'icône succès. focusable est à true pour l'icône d'alerte.

2022-02-14 21:49 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +    }
ça fonctionnait pas avec just nth-child.

2022-03-15 02:52 UTC, meriouma requested changes
T'as aussi pas mal de checks qui fail

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                    iconName={showPassword ? 'eye' : 'eyeOff'}
Les icônes sont inversées

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-creation.test.tsx
> +    });
Tu pourrais te fier aux tests de `getPasswordStrength`, et mocker `getPasswordStrength` pour retourner la valeur que tu veux, plutôt que de revérifier les règles de mots de passe ici

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-rule.tsx
> +                    aria-label={`${t('error')},`}
Pourquoi on met une virgule dans le label?

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-strength-container.tsx
> +import { useTranslation } from '../../i18n/use-translation';
importe les fichiers après les packages. Le "Optimize Import" de IJ devrait tout arranger ça.

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-strength.ts
> +            return '';
Tu devrais pouvoir enlever le `default` vu que ton switch est sur une enum. TS devrait pas chialer.

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/text-input/styles/inputs.tsx
> +    padding: 0px var(--spacing-1x);
`0` plutôt que `0px`

2022-03-15 02:52 UTC, meriouma commented on packages/react/src/components/text-input/styles/inputs.tsx
> +    padding: 0px var(--spacing-1x);
Vérifie ce que ça donne partout, tu es en train de changer pour tous les text inputs.

2022-04-11 18:54 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-rule.tsx
> +                    aria-label={`${t('error')},`}
demande de larry pour l'accessibilité. ça sonne mieux avec une virgule. ça fait une pause il me semble

2022-04-19 02:08 UTC, LarryMatte requested changes
Petit glitch avec le Tooltips et un petit changement au CSS

2022-04-19 02:08 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                <Tooltip
Quand tu passes de l'icône de l'oeil à l'icône oeil barré, le tooltip pette.
<img width="231" alt="Screen Shot 2022-04-18 at 10 02 20 PM" src="https://user-images.githubusercontent.com/3722754/163905741-a051f070-82ac-454f-9172-27cf0044e386.png">

2022-04-19 12:22 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                <Tooltip
<img width="721" alt="Capture d’écran, le 2022-04-19 à 08 21 41" src="https://user-images.githubusercontent.com/19400226/164002472-7bf2cdf6-e845-41af-b804-22cf0588d5fa.png">

2022-04-19 12:22 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +                <Tooltip
<img width="1439" alt="Capture d’écran, le 2022-04-19 à 08 22 32" src="https://user-images.githubusercontent.com/19400226/164002594-58e4e0d1-d6b9-4648-88fd-7685a2e8806d.png">

2022-04-19 20:25 UTC, meriouma approved these changes
J'ai pas restesté le visuel. Je laisse Larry faire son approve là-dessus!

2022-04-19 20:25 UTC, meriouma commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        + span > button {
C'est pour targetter quoi exactement ça `+ span > button`? Je me demande si on peut target un component plus spécifiquement que par sa hiérarchie de tags.

2022-04-20 14:58 UTC, LarryMatte commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        + span > button {
C'est pour target le bouton qui toggle le "_show/hide_" password.
Dans le fond le bouton est à l'extérieur du `div` avec le `focus-within` il faut donc target l'élément qui le suit (le span du tooltip) et ensuite descendre dans les enfants (le bouton)... 
_btw va vraiment falloir trouver une meilleure façon de gérer les tooltips que de wrapper l'élément qui le trigger à l'intérieur._

Probablement que vous pourriez target un component plus spécifique, je laisse @alexbrillant regarder ça.

2022-04-20 21:11 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        + span > button {
@LarryMatte côté react, je ne vois pas de meilleur façon de faire que de wrapper l'élément qui le trigger à l'intérieur.

2022-04-20 21:16 UTC, alexbrillant commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +        + span > button {
@meriouma ça vient compliqué avec le focus-within d'appliquer le style sur le boutou directement avec styled-components. je ne trouve pas d'autres solution alors je vais fermer.

2022-04-21 18:42 UTC, LarryMatte approved these changes

2022-04-21 20:17 UTC, merged