refactor: use rem units for css attributes targeting fonts
kronostechnologies/design-elements pull request #401
Opened 2022-01-05 20:56 UTC by maxime-gendron

## PR Description
Refactor les utilisations de `px` pour `rem` pour les attributs css de fonts.

2022-01-06 22:51 UTC, jeremilc requested changes
Il reste encore `font-size: 24px;` dans `option-button.tsx`

2022-01-07 14:20 UTC, maxime-gendron commented
> Il reste encore `font-size: 24px;` dans `option-button.tsx`

Nice catch j'ai changé ça  🎣

2022-01-07 14:46 UTC, JsGarneau approved these changes

2022-01-07 16:10 UTC, jeremilc approved these changes

2022-01-07 16:12 UTC, merged