feat(Listbox): now supports group options with separator
kronostechnologies/design-elements pull request #409
Opened 2022-01-28 17:57 UTC by JsGarneau

## PR Description
Hello, j'ai tenté de ne pas introduire de breaking changes avec cette PR, d'où l'idée d'avoir plusieurs types possible dans `options`. Ca fait ajoutes un peu de code pas super beau, mais all-in-all je crois que c'est pas si mal.

## Bug fix checklist
- [ ] Units tests have been adjusted to account for bug.
- [ ] The fix has been tested in multiple Storybook stories.
- [ ] All GitHub checks are successful.

## New component checklist
- [ ] The new component and its tests are in the same component folder.
- [ ] The component is unit tested and/or snapshot tested.
- [ ] All of the relevant Storybook stories have been added to the `storybook` package.
- [ ] There are no linting errors or warnings in the modified/new code.
- [ ] All GitHub checks are successful.

2022-03-15 01:30 UTC, meriouma requested changes
Désolé pour le délai. J'ai testé et ça brise le Select.

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +        if (remainingNumberOfItems > 0) separatorsHeight += 16;
Pour éviter la confusion :
```
if () {
}
```

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +}
Pour réduire le nombre de boucles, tu pourrais changer `max-height` pour `max-height: ${getListMaxHeight};` et changer la fonction pour :
```
const separatorHeight = 16;

function getListMaxHeight({ numberOfItemsVisible, groups, isMobile }: BoxProps): string | null {
    if (!numberOfItemsVisible) {
        return null;
    }

    let items = 0;
    const separatorsHeight = groups.reduce((total, group) => {
        items += group.options.length;
        return items < numberOfItemsVisible ? total + separatorHeight : total;
    }, 0);

    return `${(numberOfItemsVisible * (isMobile ? itemHeightMobile : itemHeightDesktop)) + separatorsHeight}px`;
}
```
Je pense que ça donne le même résultat

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +                    id={id}
C'est pas bon, chacun des groupes a le même id

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +                    id={id}
Il te manque un `key=` sur `ListGroup`

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +                    { index > 0 && <ListSeparator label={group.label} /> }
Pas d'espace entre les `{}` et le code. T'as peut-être pas les bonnes configs de reformat?

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +                    { index > 0 && <ListSeparator label={group.label} /> }
Ça fait un élément de plus à l'intérieur du `ul`. Je sais pas si ça cause problème. Y'aurait pas moyen de le faire simplement en CSS @LarryMatte ?

2022-03-15 01:30 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +            ref={listRefCallback}
Ici, de ne plus passer le `ref` du `forwardRef`, ça brise le `Select`. Et enlever `listRefCallback` brise le scroll du `Select`. Je pense qu'il va falloir retravailler ce bout là 😕

2022-03-15 01:31 UTC, meriouma commented
Ah et j'ai oublié. Ça va être de la ***** à arranger, mais tu as squasher ton commit dans le merge commit.

2022-03-15 01:40 UTC, meriouma commented on packages/react/src/components/listbox/listbox.tsx
> +                    role="presentation"
Y'a une maquette avec des labels sur le groupes? J'ai essayé d'en ajouter un dans une story et c'est pas super heureux.
![image](https://user-images.githubusercontent.com/1082552/158289022-895bb2c2-6abf-4651-b095-ec5ab67782fe.png)

2022-04-08 14:51 UTC, LarryMatte requested changes

2023-10-18 17:13 UTC, meriouma commented
@JsGarneau @LarryMatte On fait quoi avec ça, c'est encore d'actualité?

2023-10-31 17:27 UTC, closed without merging