feat(Badge): add badge component
kronostechnologies/design-elements pull request #439
Opened 2022-05-12 14:06 UTC by pylafleur

## PR Description
DS-618

Ajout d'un composant pour afficher un badge sur une icône (ou tout autre élément).
- Affichage avec ou sans valeur (cercle ou point)
- Possibilité de configurer la valeur maximale (pour l'affichage du +)
- Option pour animer le badge (bounce)

<img width="168" alt="Screen Shot 2022-05-12 at 10 03 50" src="https://user-images.githubusercontent.com/1416333/168093632-d493c40b-5a2d-4995-b463-0855f6f22571.png">

## New component checklist
- [x] The new component and its tests are in the same component folder.
- [x] The component is unit tested and/or snapshot tested.
- [x] All of the relevant Storybook stories have been added to the `storybook` package.
- [x] There are no linting errors or warnings in the modified/new code.
- [x] All GitHub checks are successful.

2022-05-12 15:53 UTC, LarryMatte requested changes
Quelques details ici et là

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    height: 16px;
Utilises des rems

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    font-weight: 400;
Il y a une variable pour ca de créé dans le DS
Voir le fichier `_variables.scss`

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    border-radius: 8px;
Il y a des variables pour les radius dans le DS
Voir le fichier `_variables.scss`

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    min-width: 16px;
Utilises des rems

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    height: 8px;
Utilises des rems

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    min-width: 8px;
Utilises des rems

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    padding: 0 5px;
Remplace le `5px` par un `4px`.
Le `5` vient donner une largeur plus grande que le `16px` même s'il n'y a qu'un seul chiffre. (voir image)
Il y a une variable pour ca de créé dans le DS
Voir le fichier _variables.scss

<img width="279" alt="Screen Shot 2022-05-12 at 11 15 28 AM" src="https://user-images.githubusercontent.com/3722754/168109437-f66cd7bd-6513-4f3e-85b2-c9c5ffe949ed.png">

2022-05-12 15:53 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +        animation: ${bounceKeyframes} 2s ease-in infinite;
À moins que ce ne soit un requirement des designers, j'éviterais les animations pour tout suite. Surtout si elle sont en "infinite".
S'il fini par avoir beaucoup d'animation "infinite" dans l'app, ca va être vraiment demandant pour l'ordi et le CPU va etre dans le tapis.
Si tu tiens à la garder, changes le "infinite" et ajoutes un `prefers-reduced-motion`. Certains users ont vraiment de la difficulté avec les elements qui passent leur temps à bouger.
https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-reduced-motion

2022-05-12 17:45 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    position: absolute;
Je me demande si les attributs de positionnement devraient vraiment se retrouver dans le css du composant. Ça risque p-e de changer d'une utilisation à l'autre. Le positionnement pourrait se faire au moment de son utilisation.

2022-05-12 19:41 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +    position: absolute;
Est-ce que tu verrais un positionnement avec un attribut (genre `position="top-right | bottom-right | ..."`)? On pourrait laisser la position actuelle (top-right) par défaut?

2022-05-12 19:46 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +        animation: ${bounceKeyframes} 2s ease-in infinite;
Oui, ça avait été demandé par les analystes. Je trouve aussi que c'est un peu intense, surtout pour le use-case de Beamer... Je peux p-e laisser le comportement disponible, tenir compte du `prefers-reduced-motion` et on pourra décider si on l'active (il ne l'est pas par défaut).

2022-05-12 19:47 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +    padding: 0 5px;
Ah oui bien vu, au début le cercle était 20x20...

2022-05-14 19:56 UTC, alexbrillant commented on packages/react/src/components/badge/badge.tsx
> +const basePosition = 'translate(50%, -50%)';
on est certain que c'est responsive les styles ici ? l'animation est cool, mais je suis pas certain que c'est nécessaire pour l'instant. à voir avec team design

2022-05-14 19:57 UTC, alexbrillant commented on packages/react/src/components/badge/badge.tsx
> +    const visible = useMemo(() => (value !== 0 || showZero), [value, showZero]);
cette opération est assez simple. je suis pas certain que useMemo soit nécessaire ici. c'est okey de le laisser aussi I guess

2022-05-16 15:16 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +const basePosition = 'translate(50%, -50%)';
Oui, pas de problème pour le responsive. Pour ce qui est de l'animation, c'est un requis confirmé par les analystes pour l'intégration de Beamer.

2022-05-25 15:16 UTC, LarryMatte requested changes
de petits trucs ici et là

2022-05-25 15:16 UTC, LarryMatte commented on packages/react/src/components/badge/badge.tsx
> +    position: absolute;
Je crois que je n'en ajouterais tout simplement pas. Quand le dev va vouloir l'ajouter, il va pouvoir le positionner comme il veut.
@meriouma tu en penses quoi?

2022-05-25 17:47 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +    padding: 0 0.25rem;
Notre config stylelint a une règle pour avoir un _leading zero_, ça passe pas en l'enlevant:

![Screen Shot 2022-05-25 at 13 42 23](https://user-images.githubusercontent.com/1416333/170328904-a1d5e5d7-10a1-4d1d-8d14-5a403f94368f.png)

2022-05-25 17:52 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +    height: 0.5rem;
stylelint

2022-05-25 17:52 UTC, pylafleur commented on packages/react/src/components/badge/badge.tsx
> +    min-width: 0.5rem;
stylelint

2022-05-25 18:00 UTC, pylafleur commented
Concernant la position, je pense que c'est quand même pertinent d'avoir un comportement par défaut, qui devrait couvrir pas mal de cas d'utilisation.

2022-05-26 15:24 UTC, LarryMatte approved these changes

2022-05-26 15:36 UTC, merged