feat(SearchInput): add forwardRef to search input component
kronostechnologies/design-elements pull request #459
Opened 2022-08-18 21:03 UTC by alexbrillant

[DS-642](https://jira.equisoft.com/browse/DS-642)
Permet de passer une ref au component GlobalSearch.

2022-08-19 17:04 UTC, meriouma commented on packages/react/src/components/search/search-input.tsx
> +export const SearchInput = forwardRef<HTMLInputElement, SearchInputProps>(({
```suggestion
export const SearchInput = forwardRef(({
```

2022-08-19 17:04 UTC, meriouma commented on packages/react/src/components/search/search-input.tsx
> +}, ref) => {
```suggestion
}: SearchInputProps, ref: Ref<HTMLInputElement | null>) => {
```

2022-08-19 17:04 UTC, meriouma commented on packages/react/src/components/search/search-input.tsx
> +    useImperativeHandle(ref, () => innerInputRef.current as HTMLInputElement);
```suggestion
    useImperativeHandle(ref, () => innerInputRef.current);
```

2022-08-22 18:12 UTC, alexbrillant commented on packages/react/src/components/search/search-input.tsx
> +    useImperativeHandle(ref, () => innerInputRef.current as HTMLInputElement);
c'est nécessaire sinon typescript est pas content et si je mets le typings sur la props en haut ça fait une erreur dans global-search (voir autre commentaire)

2022-08-23 00:53 UTC, meriouma commented on packages/react/src/components/search/search-input.tsx
> +}, ref) => {
Si tu mets `props: SearchGlobalProps, ref: Ref<HTMLInputElement>`, tu devrais pas avoir de problème de Typescript.

2022-08-23 01:21 UTC, meriouma commented on packages/storybook/stories/search-global.stories.tsx
> +    }, [ref]);
Avec `useRef`, tu n'as pas besoin du effect, et `ref` changera jamais. Regarde mon commentaire original.

2022-08-23 17:11 UTC, alexbrillant commented on packages/storybook/stories/search-global.stories.tsx
> +    }, [ref]);
ça ça avait pas rapport pantoute. je sais pu trop pourquoi j'avais mis ça

2022-08-23 17:13 UTC, alexbrillant commented on packages/react/src/components/search/search-input.tsx
> +}, ref) => {
<img width="950" alt="Capture d’écran, le 2022-08-23 à 13 13 24" src="https://user-images.githubusercontent.com/19400226/186222597-fedda2d7-a179-417a-b52f-32d0d0d83f88.png">

2022-08-23 19:10 UTC, meriouma commented on packages/react/src/components/search/search-input.tsx
> +}, ref) => {
Parce que dans `SearchInput`, tu dois mettre `Ref<HTMLInputElement | null>`.

2022-08-24 15:16 UTC, alexbrillant commented on packages/react/src/components/search/search-input.tsx
> +}, ref) => {
si je fais ça, ça crée une autre erreur dans le global search. on la voit dans mon commentaire précédent.

2022-09-12 03:16 UTC, meriouma requested changes

2022-09-12 03:16 UTC, meriouma commented on packages/react/src/components/search/search-global.tsx
> +SearchGlobal.displayName = 'Button';
`SearchGlobal`, pas `Button`

2022-09-12 03:16 UTC, meriouma commented on packages/react/src/components/search/search-input.tsx
> +    useImperativeHandle(ref, () => innerInputRef.current as HTMLInputElement);
Faut que t'arranges les autres types. J'ai fait les suggestions que je t'ai proposé et tout fonctionne de mon côté.

2022-10-07 01:59 UTC, meriouma approved these changes

2022-10-07 01:59 UTC, meriouma commented on packages/storybook/stories/search-global.stories.tsx
> +    const ref = useRef<HTMLInputElement>();
Pour faire passer le CI:
```suggestion
    const ref = useRef<HTMLInputElement>(null);
```

2022-10-07 01:59 UTC, meriouma commented
(et n'oublies pas de squasher)

2023-10-18 17:15 UTC, meriouma commented
Salut @alexbrillant ! Une autre PR que je sais pas si c'est encore pertinent?

2023-11-22 18:43 UTC, closed without merging