feat(Toggletip): Added Toggletip component
kronostechnologies/design-elements pull request #472
Opened 2023-01-17 15:41 UTC by JsGarneau

## PR Description
Based à partir des specs ici: https://www.notion.so/equisoft/Toggle-Tip-1ba74138a2634b5694aa039df165a296

## Bug fix checklist
- [ ] Units tests have been adjusted to account for bug.
- [ ] The fix has been tested in multiple Storybook stories.
- [ ] All GitHub checks are successful.

## New component checklist
- [ ] The new component and its tests are in the same component folder.
- [ ] The component is unit tested and/or snapshot tested.
- [ ] All of the relevant Storybook stories have been added to the `storybook` package.
- [ ] There are no linting errors or warnings in the modified/new code.
- [ ] All GitHub checks are successful.

2023-01-23 19:46 UTC, LarryMatte requested changes
Tu sembles utiliser pas mal la composante "Tooltip" du DS pour créer le ToggleTip, mais ce n'est vraiment pas l'idéal.
Ce sont vraiment deux composantes différentes. 

- Le toggleTip va toujours être trigger par un bouton tandis que le Tooltip apparait sur le focus (ou hover) pour donner plus d'info à l'élément en focus/hover.
- Le tooltip est annoncé par l'accessibility API comme étant un "tooltip", le ToggleTip non.
- etc
 
Visuellement il y a des similarités, mais ça s'arrête pas mal à ça. Perso je partirais avec quelque chose de _fresh_ plutôt que d'utiliser la composante Tooltip.
Tu peux surement copier les styles et la logique pour avoir les arrows selon son emplacement...
À toi de voir.

2023-01-23 19:46 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +                aria-describedby={toggletipId}
Tu vas probablement faire le switch vers la composante de _Icon button_ mais au cas des fois, j'aime mieux te fournir l'info avec ce qui est déjà en place...
↓
Remplace le `aria-describedby` par un `aria-label`.
Un `aria-describedby` utilise le text d'un autre élément (id référencé) pour définir le label de l'élément courant. Ici nous voulons créer un label spécifique pour le bouton.

2023-01-23 19:46 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +                        focusable={false}
Ajoutes un `aria-hidden="true"`

2023-01-23 19:46 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +            <TooltipContainer
N'utilises pas la composante "Tooltip", ce n'est pas la même chose ou du moins modifies pour respecter ce qui est dans la [doc Notion](https://www.notion.so/equisoft/Toggle-Tip-1ba74138a2634b5694aa039df165a296#2080d67a0a244d88889dd5e2a6b05405).
Pas besoin du `role="tooltip"` & du `aria-hidden`

2023-01-23 19:46 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +                tabIndex={(children || disabled) ? -1 : 0}
Tu ne devrais pas à avoir à changer la valeur du `tabindex` pour un `button`. À enlever... 
À moins que tu y vois une nécessité mais en modifiant l'ordre du "tab/focus", on vient possiblement créer des problèmes de [navigation/accessibilité](https://www.w3.org/WAI/WCAG22/Techniques/failures/F44).

2023-01-24 16:13 UTC, JsGarneau commented on packages/react/src/components/toggletip/toggletip.tsx
> +                aria-describedby={toggletipId}
En faisant le switch vers un `IconButton`, est-ce que je dois tout de même mettre le `Id` comme `label`? Car c'est un champs optionnel et j'ai l'impression que ca voudrait plus faire référence au contenus du bouton?

2023-01-24 19:51 UTC, LarryMatte requested changes
Encore quelques petits trucs / possible recommandation.

2023-01-24 19:51 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +    min-height: ${({ isMobile }) => (isMobile ? '72px' : '32px')};
utilises des `rem` ici

2023-01-24 19:51 UTC, LarryMatte commented on packages/storybook/stories/toggletip.stories.tsx
> +    <Toggletip label="Toggletip Content" />
Il faudrait possiblement avoir un exemple aussi avec un Toggletip qui contient un lien dans la page de storybook.

2023-01-24 19:51 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +            <StyleIconButton
Il va toujours y avoir un `aria-label` pour l'icône donc à ajouter.

2023-01-24 19:51 UTC, LarryMatte commented on packages/react/src/components/toggletip/toggletip.tsx
> +            <StyleIconButton
Le bouton va toujours être du `type="button"` au lieu de `type="submit"`. Est-ce qu'il y aurait moyen de le mettre by default?
`<button type="button" ...>Blah blah blah</button>`

2023-01-26 19:32 UTC, faroukhoumaidi reviewed
Ça fonctionne de mon côté par contre j'ai deux commentaires :

- Ce n'est pas `288px` le `max-width` selon les specs sur Notion, ou essaie d'avoir le même width que les tooltips?
- Des tests fail a cause d'un autre component, je pense pas que tu serais en mesure de merge.

2023-01-27 16:14 UTC, LarryMatte requested changes
Dernier petit truc après la vie est belle pour moi
Good job!

2023-01-31 04:30 UTC, meriouma reviewed
J'ai reviewed le code et le comportement. Il faudrait enlever les 2 tests qui fail pour l'instant. Pour le reste, je fais confiance à Larry.

2023-01-31 04:30 UTC, meriouma commented on packages/react/src/components/toggletip/toggletip.test.tsx
> +        });
Je pense pas qu'il y ait moyen de faire passer ces test avec Enzyme. Il permet seulement de simuler les events de React en appelant la fonction en props de `onClick`. La lib `react-popper-tooltip` utilise `addEventListener` alors ça prendrait une vraie DOM pour simuler le comportement du click.

2023-01-31 15:29 UTC, meriouma submitted a review, later dismissed

2023-02-08 17:34 UTC, LarryMatte requested changes

2023-02-08 20:06 UTC, LarryMatte approved these changes

2023-02-09 13:48 UTC, meriouma approved these changes

2023-02-09 13:48 UTC, merged