fix(Theme): update theme properties to reflect new guide in Figma
kronostechnologies/design-elements pull request #473
Opened 2023-01-27 23:50 UTC by samuelguebo

## PR Description
Adjust theme properties to reflect information provided in Figma guide: https://www.figma.com/file/Rix8Euc5yoZTJHN6zoNA0K/R%C3%A9pertoire-de-th%C3%A8mes

## GitHub issues resolved by PR
No github issues; But an issue filed in JIRA: https://jira.equisoft.com/browse/ABF-5329

## Bug fix checklist
- [ ] Units tests have been adjusted to account for bug.
- [ ] The fix has been tested in multiple Storybook stories.
- [ ] All GitHub checks are successful.

## New component checklist
- [ ] The new component and its tests are in the same component folder.
- [ ] The component is unit tested and/or snapshot tested.
- [ ] All of the relevant Storybook stories have been added to the `storybook` package.
- [ ] There are no linting errors or warnings in the modified/new code.
- [ ] All GitHub checks are successful.

2023-01-31 04:38 UTC, meriouma requested changes

2023-01-31 04:38 UTC, meriouma commented on packages/react/src/themes/main.ts
> +    'secondary-4.1': '#006296',
Si je me fie au répértoire de thèmes, ce n'est vraiment pas la bonne couleur. C'est la même couleur que `primary-1.1`.
Je ne suis pas certain de comprendre le changement en fait.

2023-01-31 14:35 UTC, samuelguebo commented on packages/react/src/themes/main.ts
> +    'secondary-4.1': '#006296',
Merci @meriouma, ce changement n'est pas nécessaire. Je vais ajuster le commit.

2023-01-31 15:57 UTC, JsGarneau submitted a review, later dismissed

2023-02-01 04:59 UTC, meriouma commented
Je me questionne. Je pense qu'on devrait renommer la PR pour changer `fix` par `feat` puisque c'est plutôt un ajout au Theme et non une correction de bug. Ça a l'air anodin, mais ça détermine le prochain incrément de version (patch vs minor).

2023-02-01 09:29 UTC, samuelguebo commented
Hello @meriouma, si ca permet de rendre les prochains changements plus cohérents alors c'est correct pour moi. J'ai renommé la PR et ajusté le message du commit.

2023-02-01 15:54 UTC, meriouma approved these changes

2023-02-01 19:07 UTC, merged