feat(Tooltip): adjust style to fit doc
kronostechnologies/design-elements pull request #486
Opened 2023-03-21 15:12 UTC by JsGarneau

## Bug fix checklist
- [ ] Units tests have been adjusted to account for bug.
- [ ] The fix has been tested in multiple Storybook stories.
- [ ] All GitHub checks are successful.

## New component checklist
- [ ] The new component and its tests are in the same component folder.
- [ ] The component is unit tested and/or snapshot tested.
- [ ] All of the relevant Storybook stories have been added to the `storybook` package.
- [ ] There are no linting errors or warnings in the modified/new code.
- [ ] All GitHub checks are successful.

2023-03-21 21:13 UTC, meriouma reviewed
On dirait que le radius est pas tout à fait bon visuellement, même si c'est 2px comme dans Figma. Aussi on dirait qu'il y a un peu trop d'espace autour du texte, je pense que le tooltip est un peu plus haut que dans les maquettes. Ça prendrait le review de @LarryMatte je pense.

2023-03-23 19:20 UTC, LarryMatte requested changes
Quelques petites modifications.
@meriouma a raison pour le border de `2px` qui fit avec ce qui est dans les specs de figma mais qui ne fit pas vraiment visuellement...
Je crois que je laisserais comme c'est là.
Je vais probablement refaire une passe de CSS de tous les composants quand on aura le  feu vert et qu'on saura ce qui se passe avec tout ça.
D'ici là, disons que c'est bien correct.

2023-05-05 02:40 UTC, meriouma commented on packages/react/src/components/datepicker/datepicker.test.tsx.snap
> +          placeholder="MM/DD/YYYY"
Ta version de node doit pas être contrôlée par asdf. C'est un problème avec les versions plus récentes de node. Ça devrait être corrigé dans la prochaine, mais en attendant tu devrais t'assurer d'utiliser la version de node qu'il y a dans le `.tool-versions` pour le DS.

2023-07-17 16:19 UTC, JsGarneau commented on packages/react/src/components/datepicker/datepicker.test.tsx.snap
> +          placeholder="MM/DD/YYYY"
Ca ma fait investiguer les configs de mon `asdf`. On dirait que ca avait jamais été pluggué correctement 😅 

C't'un peu gênant

2023-07-17 17:18 UTC, meriouma commented on packages/react/src/components/tooltip/tooltip.tsx
> +    const [isVisible, setIsVisible] = useState(true);
Vestige de debug?

2023-07-25 17:39 UTC, JsGarneau commented on packages/react/src/components/tooltip/tooltip.tsx
> +    const [isVisible, setIsVisible] = useState(true);
🤦

2023-07-25 19:06 UTC, meriouma commented on packages/react/src/components/tooltip/tooltip.tsx
> +    const [isVisible, setIsVisible] = useState(true);
Je pense que t'as pas updater le snapshot 😅

2023-07-26 14:17 UTC, meriouma approved these changes

2023-08-08 17:11 UTC, LarryMatte approved these changes

2023-08-08 17:14 UTC, merged