fix: a11y zoom 200% all non-control components
kronostechnologies/design-elements pull request #487
Opened 2023-04-11 20:41 UTC by LarryMatte

## PR Description
### A11y success criteria
Si un utilisateur augmente la taille de la typo à 200%, il ne doit pas y avoir de perte de contenu.

### fix
J'ai changé les px pour des rem et adapté les composants en conséquence.

### To test
Chrome: Preferences... --> Appearance --> Font size (sélectionner "Very large" dans le dropdown-list)

## GitHub issues resolved by PR
...

## Bug fix checklist
- [ ] Units tests have been adjusted to account for bug.
- [ ] The fix has been tested in multiple Storybook stories.
- [ ] All GitHub checks are successful.

## New component checklist
- [ ] The new component and its tests are in the same component folder.
- [ ] The component is unit tested and/or snapshot tested.
- [ ] All of the relevant Storybook stories have been added to the `storybook` package.
- [ ] There are no linting errors or warnings in the modified/new code.
- [ ] All GitHub checks are successful.

2023-04-26 19:07 UTC, meriouma requested changes
Il y a une couple de petits trucs à corriger, notamment du eslint.

Sinon, il y a vraiment de quoi avec la police, pas mal de composantes ont un visuel un peu comprimé on dirait. J'ai l'impression qu'il manque des fractions de pixels à gauche et à droite qui font que c'est un peu squeezed par rapport à ce qu'on avait avant 🤔 .

Je sais pas si tu as changé de quoi de plus global qui pourrait avoir un side-effect, mais on dirait que je n'ai plus de scrollbar dans le storybook.

2023-05-08 19:34 UTC, LarryMatte commented on packages/react/src/components/toast/toast-container.tsx
Le size semble pas si mal de mon côté. Il y a petite différence de graisse mais sinon c'est close enough.
Image de Figma superposée au composant dans storybook:
<img width="305" alt="Screenshot 2023-05-08 at 3 18 34 PM" src="https://user-images.githubusercontent.com/3722754/236913180-30bad727-9082-458a-b556-d6b5ccf2152f.png">
Image de Figma superposée, avec un décallage, au composant dans storybook:
<img width="301" alt="Screenshot 2023-05-08 at 3 19 46 PM" src="https://user-images.githubusercontent.com/3722754/236913397-ad1f993f-d15d-4711-bdb3-7227ac76febe.png">

2023-05-08 19:34 UTC, LarryMatte commented on packages/react/src/components/toast/toast-container.tsx
Le size semble pas si mal de mon côté. Il y a petite différence de graisse mais sinon c'est close enough.
Image de Figma superposée au composant dans storybook:
<img width="305" alt="Screenshot 2023-05-08 at 3 18 34 PM" src="https://user-images.githubusercontent.com/3722754/236913180-30bad727-9082-458a-b556-d6b5ccf2152f.png">
Image de Figma superposée, avec un décallage, au composant dans storybook:
<img width="301" alt="Screenshot 2023-05-08 at 3 19 46 PM" src="https://user-images.githubusercontent.com/3722754/236913397-ad1f993f-d15d-4711-bdb3-7227ac76febe.png">

2023-05-08 20:12 UTC, LarryMatte commented on packages/react/src/components/card-link/card-link.tsx
> -        ${StyledIcon} {
Oui le border semble être géré par le box-shadow et sur le hover, il devient plus dark.
Les designers ont retravaillé le visuel dans les dernières semaines, il va y avoir une task Jira qui va venir pour aller faire des modifications au visuel. À voir quand nous serons rendu là.

2023-05-12 01:34 UTC, meriouma approved these changes

2023-06-30 16:42 UTC, meriouma approved these changes

2023-06-30 16:43 UTC, merged