DS-464: feat(ErrorSummary): add component
kronostechnologies/design-elements pull request #488
Opened 2023-04-24 18:55 UTC by pylafleur

## PR Description
Ajouter le composant Error Summary

## New component checklist
- [ ] The new component and its tests are in the same component folder.
- [ ] The component is unit tested and/or snapshot tested.
- [ ] All of the relevant Storybook stories have been added to the `storybook` package.
- [ ] There are no linting errors or warnings in the modified/new code.

2023-05-09 04:20 UTC, meriouma reviewed
Très cool!

2023-05-09 04:20 UTC, meriouma commented on packages/react/src/i18n/translations.ts
> +            message: 'Veuillez corriger avant de passer à l\'étape suivante.',
```suggestion
            message: 'Veuillez les corriger avant de passer à l\'étape suivante.',
```
?

2023-05-09 04:20 UTC, meriouma commented on packages/react/src/i18n/translations.ts
> +            title: 'Le formulaire contient une ou plusieurs erreur(s)',
```suggestion
            title: 'Le formulaire contient une ou plusieurs erreurs',
```
?

2023-05-09 04:20 UTC, meriouma commented on packages/react/src/i18n/translations.ts
> +            message: 'Please correct to process to the next step.',
```suggestion
            message: 'Please correct them to proceed to the next step.',
```

2023-05-09 04:20 UTC, meriouma commented on packages/react/src/components/error-summary/error-summary.tsx
> +    targetId: string;
Je me demande, est-ce qu'on devrait supporter de passer un ref vers le component plutôt (ou en alternative)? Je sais pas lequel serait le plus pratique.

2023-05-09 04:20 UTC, meriouma commented on packages/react/src/components/sectional-banner/sectional-banner.tsx
> +    focusable?: boolean;
La seule affaire qui m'embête ici, c'est que ça puisse rendre le SectionalBanner focusable si un dev passe true quand il l'utilise tout seul. @LarryMatte ?

2023-05-09 04:26 UTC, meriouma commented
J'ai reviewed un peu trop vite. Je pense qu'il manque que le Enter du clavier trigger le lien quand il a le focus.

2023-05-09 12:34 UTC, pylafleur commented on packages/react/src/i18n/translations.ts
> +            message: 'Veuillez corriger avant de passer à l\'étape suivante.',
Pour le texte j'ai pris directement ce qu'il y avait dans notion. Mais je suis d'accord tes suggestions! Si on modifie ici, faudrait probablement mettre à jour notion / figma.

2023-05-10 04:31 UTC, pylafleur commented
> J'ai reviewed un peu trop vite. Je pense qu'il manque que le Enter du clavier trigger le lien quand il a le focus.

Je me fiais sur le comportement natif du browser mais j'ai utilisé l'attribut `to` à la place de `href` 🤦 
J'ai fait quelques changements supplémentaires dans une PR à part (#498) et je vais corriger celle-ci basé sur ces autres changements.

2023-05-10 13:19 UTC, LarryMatte requested changes
Quelques commentaires ici et là sinon:

- Il faudrait que le titre du composant soit un Heading (`h2`, `h3`...).
- Est-ce qu'il serait possible de changer le `<div>` _container_ par un élément `<section>` ?
- Le contenu qui vient après le titre est wrappé dans un` <div>`. Le `<div>` n'est pas vraiment nécessaire donc si tu pouvais l'enlever ça ferait ça de moins dans le code.

2023-05-12 04:05 UTC, pylafleur commented on packages/react/src/components/error-summary/error-summary.tsx
> +                tabIndex={0}
Je pense que le `<a>` ne focusait pas vu que j'avais pas de `href` (j'avais utilisé l'attribut `to` par erreur). En tout cas, maintenant il a un `href="#id_du_input_en_erreur"` et ça focus par défaut.

2023-05-12 14:33 UTC, pylafleur commented
@LarryMatte Les différences notées (`<h2>`, `<section>` et la div de trop) viennent du fait que j'ai utilisé le Sectional Banner comme building bloc pour mon component. Est-ce que tu penses qu'il y aurait moyen de rendre les 2 structures compatibles? Est-ce que le h2 et le section auraient du sens dans le Sectional Banner?

2023-05-12 16:55 UTC, LarryMatte commented
> @LarryMatte Les différences notées (`<h2>`, `<section>` et la div de trop) viennent du fait que j'ai utilisé le Sectional Banner comme building bloc pour mon component. Est-ce que tu penses qu'il y aurait moyen de rendre les 2 structures compatibles? Est-ce que le h2 et le section auraient du sens dans le Sectional Banner?

@pylafleur Le heading `<h2>` pourrait possiblement être un `<h3>`, ça va dépendre à quel niveau de la hiérarchie de la page le composant est. Donc le tag du heading doit pouvoir changer (h2, h3, h4 etc) donc il ne faudrait pas qu'il soit "fix". Je regarde ça pour le sectional et je te reviens.

2023-05-17 13:55 UTC, LarryMatte commented
> Est-ce que le h2 et le section auraient du sens dans le Sectional Banner?

C'est good! tu peux utiliser un élément `<section>` et un heading pour le Sectional Banner

2023-06-02 02:42 UTC, meriouma commented on packages/react/src/components/error-summary/error-summary.tsx
> +    (typeof target === 'string') ? target : target?.current?.id
Plutôt que d'aller chercher l'id avec le ref, tu devrais plutôt aller chercher l'element quand c'est un id, sinon utiliser le ref pour faire directement `target.current?.focus()`.

2023-06-02 02:42 UTC, meriouma commented on packages/react/src/components/error-summary/error-summary.tsx
> +                href={`#${getTargetId(error.target)}`}
J'avais pas catché qu'on avait besoin d'un id anyway pour le href 🤔
Est-ce que c'est pour gérer le clavier? Sinon on pourrait peut-être juste gérer le keyboard event plutôt?

2023-06-07 14:57 UTC, pylafleur commented on packages/react/src/components/error-summary/error-summary.tsx
> +                href={`#${getTargetId(error.target)}`}
Ma question c'était mettons qu'on a un lien qui focus sur un input plus bas, est-ce que `<a href="#id_du_input">` a un avantage pour le a11y vs. `<a href="#">` tout court?

2023-06-07 15:18 UTC, LarryMatte commented on packages/react/src/components/error-summary/error-summary.tsx
> +                href={`#${getTargetId(error.target)}`}
accessibilité-ment parlant je ne crois pas que ca vient changer quelque chose. Si tu peux utiliser l'`id` c'est p-e mieux, mais mon point de vue est basé purement sur le fait que c'est la façon de faire en HTML bien simple...

2023-06-10 23:41 UTC, meriouma commented on packages/react/src/components/error-summary/error-summary.tsx
> +                href={`#${getTargetId(error.target)}`}
Ah, makes sense.

2023-06-10 23:48 UTC, meriouma approved these changes

2023-06-20 13:46 UTC, LarryMatte approved these changes
LGTM

2023-06-20 13:52 UTC, merged