feat(Toggletip, Tooltip): add inverted icons support
kronostechnologies/design-elements pull request #558
Opened 2023-08-11 17:50 UTC by faroukhoumaidi

https://jira.equisoft.com/browse/DS-785

- [ ] La composante `Tooltip` support les InvertedIcons
- [ ] Une bordure blanche est ajouté a la composante `Tooltip`
- [ ] La composante `Toggletip` support les InvertedIcons

2023-08-14 14:17 UTC, LarryMatte approved these changes

2023-08-14 14:33 UTC, meriouma commented
@LarryMatte Ça sort de où la bordure blanche? C'est pas dans le Figma.

2023-08-14 14:35 UTC, LarryMatte commented
> @LarryMatte Ça sort de où la bordure blanche? C'est pas dans le Figma.

@meriouma C'est une modification qui a dû être apporté car le tooltip sortait mal dur un fond plus dark. Marc a approuvé la modification jeudi passé mais il n'a pas eu le temps de faire la modification dans Figma avant de partir en vacance.

2023-08-14 14:38 UTC, meriouma commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-width: 0.5rem 0.4rem 0.5rem 0;
Je pense que 0.5rem ressemble plus à la forme dans la documentation. Je vais merger ma PR je pense, elle corrige seulement les régressions, et la tienne pourra se concentrer sur la modification de la feature.

2023-08-14 17:14 UTC, faroukhoumaidi commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-width: 0.5rem 0.4rem 0.5rem 0;
D'accord, je vais me rebaser alors sur master après ton merge 👍

2023-08-15 19:06 UTC, LarryMatte requested changes

2023-08-15 19:06 UTC, LarryMatte commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-color: transparent transparent transparent ${({ theme }) => theme.greys.white};
tu vas p-e devoir changer un peu le css, le `border` est tellement _thin_ qu'il n'est pratiquement pas visible.
<img width="149" alt="Screenshot 2023-08-15 at 3 05 51 PM" src="https://github.com/kronostechnologies/design-elements/assets/3722754/0699b91b-c6e2-4c9e-8316-d3707b8c5d99">

2023-08-16 14:18 UTC, faroukhoumaidi commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-color: transparent transparent transparent ${({ theme }) => theme.greys.white};
J'ai testé sur Chrome, Brave et Safari et je n'ai pas pu reproduire. 
Peux-tu me confirmer svp si ce n'est pas un problème de cache de ton coté pour que je creuse plus? 
![Capture d’écran, le 2023-08-16 à 10 18 07](https://github.com/kronostechnologies/design-elements/assets/96442116/ef113c27-885c-4afd-b8ce-0ee3262a6601)

2023-08-16 15:31 UTC, meriouma commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-color: transparent transparent transparent ${({ theme }) => theme.greys.white};
J'ai le même problème que Larry avec le left et le top. Les bottom et right ont l'air corrects.

2023-08-16 17:16 UTC, LarryMatte commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-color: transparent transparent transparent ${({ theme }) => theme.greys.white};
Firefox, Safari,Brave sont tous pareil

Pour que tout soit nickel de mon côté, il faudrait que le css soit

RIGHT
```
::before
	...
	left: 0.2rem;
	position: absolute;

::after
	...
	left: 0.3rem;
	position: absolute;
```
LEFT
```
::before
	...
	position: absolute;
	right: 0.2rem;

::after
	...
	position: absolute;
	right: 0.3rem;
```

BOTTOM
```
::before
	...
	position: absolute;
	top: -0.2rem;

::after
	...
	position: absolute;
	top: -0.1rem;
```

TOP
```
::before
	...
	bottom: -0.5rem;
	position: absolute;

::after
	...
	bottom: -0.4rem;
	position: absolute;
```

2023-08-16 17:17 UTC, LarryMatte commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-color: transparent transparent transparent ${({ theme }) => theme.greys.white};
Ou ce le patch de Max ahah j'avais manqué ses messages avant de post mon message précédent.

2023-08-16 18:43 UTC, LarryMatte approved these changes

2023-08-16 19:12 UTC, faroukhoumaidi commented on packages/react/src/components/tooltip/tooltip.tsx
> +        border-color: transparent transparent transparent ${({ theme }) => theme.greys.white};
Oui j'ai du tweaker une des valeurs du patch, mais oui en effet le problème était du coté  de mon build 🤦

2023-08-17 19:32 UTC, meriouma commented on packages/react/src/components/tooltip/tooltip.test.tsx.snap
> +  left: 0.1rem;
Je pense que ça devrait être `0.17rem` ici finalement 🤔

2023-08-17 19:40 UTC, meriouma commented on packages/react/src/components/tooltip/tooltip.tsx
> +        left: 0.1rem;
Je pense que ça devrait être `0.17rem` ici finalement 🤔

2023-08-18 18:14 UTC, faroukhoumaidi commented on packages/react/src/components/tooltip/tooltip.tsx
> +        left: 0.1rem;
Je viens de soumettre la suggestion, mais je pense que c'est un `0.13rem` qui fera l'affaire. 
Je t'invite a tester.

2023-08-21 14:28 UTC, meriouma approved these changes
C'est beau pour moi. Je demanderais peut-être à @LarryMatte de retester juste pour être certain.

2023-08-22 17:14 UTC, LarryMatte approved these changes
LGTM

2023-08-22 17:28 UTC, merged