feat(RadioCardGroup)!: added RadioCardGroup component
kronostechnologies/design-elements pull request #593
Opened 2023-09-12 18:28 UTC by JsGarneau

Basé sur ces maquettes figma

https://www.figma.com/file/s0iqD0TbWNNt6anLNGS9bQ/Documentation%2C-Notion?node-id=27748%3A128260&mode=dev

Et HTML Snippet ici
https://www.notion.so/equisoft/Radio-Card-f12bac23afbc4313896923bbe2d4d655?pvs=4#a3ad4f620f674616a042ff7e633c5c27

2023-09-18 21:19 UTC, LarryMatte requested changes
LGTM but a small addition that might be necessary if the cards are not stacked on top of each other but displayed side by side: You could wrap all the radio cards in a container and specify whether they are arranged horizontally or vertically.

2023-09-18 23:41 UTC, meriouma commented
Je suis un peu mêlé. Dans le JIRA ça parle de remplacer le `ChooserCard `par le `RadioCard`, mais on a encore le `ChooserButtonGroup` et là on rajoute le `RadioCardGroup`. Il y a peut-être une distinction qui m'échappe, mais on dirait que fonctionnellement, on a 2 groupes de composantes qui font la même chose, mais avec des visuels différents. Est-ce qu'on devrait en éliminer un?

2023-09-19 00:25 UTC, meriouma reviewed
Le visuel a l'air un mini-off par rapport aux maquettes. Le positionnement est un brin décalé, et le texte dans les maquettes est plus foncé.

2023-09-19 00:25 UTC, meriouma commented on packages/react/src/components/radio-card-group/radio-card-group.tsx
> +export const RadioCardGroup : VoidFunctionComponent<RadioCardGroupProps> = ({
```suggestion
export const RadioCardGroup: VoidFunctionComponent<RadioCardGroupProps> = ({
```

2023-09-19 00:25 UTC, meriouma commented on packages/react/src/components/radio-card-group/styled-components.ts
> +  border: none;
C'est plate parce qu'il y a un problème dans stylelint qui nous empêche de valider l'indentation, mais ça devrait être 4 spaces partout. Il y a plusieurs components dans ce fichier qui ont seulement 2 spaces 🫤
```suggestion
    border: none;
```

2023-09-19 09:33 UTC, LarryMatte commented
> Je suis un peu mêlé. Dans le JIRA ça parle de remplacer le `ChooserCard `par le `RadioCard`, mais on a encore le `ChooserButtonGroup` et là on rajoute le `RadioCardGroup`. Il y a peut-être une distinction qui m'échappe, mais on dirait que fonctionnellement, on a 2 groupes de composantes qui font la même chose, mais avec des visuels différents. Est-ce qu'on devrait en éliminer un?

C'est un truc que nous avions flaggé la semaine dernière avec les designers. Probablement que le "chooser button group" va se faire virer éventuellement. Ils ont le même style que des boutons mais agissent comme des radio buttons et ce n'est probablement pas l'idéal. Je m'étais laissé une note pour revenir là dessus et regarder avec les UX de l'avenir du composant dans le DS.

2023-09-19 10:16 UTC, LarryMatte requested changes

2023-09-19 12:29 UTC, LarryMatte commented on packages/react/src/components/radio-card-group/styled-components.ts
> +  border-radius: var(--border-radius-2x);
Ça a été fixé par marc dans Figma, tu n'as rien à changer

2023-09-19 13:34 UTC, JsGarneau commented
> Le visuel a l'air un mini-off par rapport aux maquettes. Le positionnement est un brin décalé, et le texte dans les maquettes est plus foncé.

Ouin, ces des couleurs qui ne sont présentement pas accessible, je peux mettre noir par contre. pour le positionnement je le vois pas vraiment. Il y a moyen d'être plus précis 🙃

2023-09-19 15:44 UTC, meriouma commented
> > Le visuel a l'air un mini-off par rapport aux maquettes. Le positionnement est un brin décalé, et le texte dans les maquettes est plus foncé.
> 
> Ouin, ces des couleurs qui ne sont présentement pas accessible, je peux mettre noir par contre. pour le positionnement je le vois pas vraiment. Il y a moyen d'être plus précis 🙃

Aaah my bad, j'avais pris un screenshot et je l'ai perdu dans mes back and forth de messages 🤦‍♂️

2023-09-19 15:54 UTC, savutsang commented on packages/react/src/components/radio-card-group/radio-card-group.tsx
> +    horizontal?: boolean;
I think it's more concise like this

```
orientation?: 'horizontal' | 'vertical'
```

2023-09-19 16:01 UTC, meriouma reviewed
Je sais pas si c'est voulu, mais les flèches naviguent entre tous les radio de la page, pas seulement celles du groupe dans le storybook.

2023-09-19 16:01 UTC, meriouma commented on packages/react/src/components/radio-card-group/radio-card-group.tsx
> +};
La fonction `isRadioCard` pourrait toujours être dans le "module" de radio-card aussi. J'hésite entre les deux.

2023-09-19 16:27 UTC, savutsang commented on packages/react/src/components/radio-card-group/radio-card-group.tsx
> +    horizontal?: boolean;
I think it's better named this way

```
orientation?: 'horizontal' | 'vertical'
```

2023-09-19 17:19 UTC, savutsang commented
> Je sais pas si c'est voulu, mais les flèches naviguent entre tous les radio de la page, pas seulement celles du groupe dans le storybook.

Ca se reproduit juste pour un couple de Stories car ils ont les meme "name".  Ca me fait realiser que puisque le premier Story est affiche aussi en duplicat au dessus des parameters, on aura toujours ce probleme sauf si on peut generer 2 exemple different.

2023-09-19 19:08 UTC, JsGarneau commented
@savutsang @LarryMatte @meriouma 
Les fixes on été fait

2023-09-19 19:19 UTC, savutsang commented
LBTM

2023-09-19 19:40 UTC, meriouma submitted a review, later dismissed
Nitpicking, sinon LGTM.

2023-09-19 19:40 UTC, meriouma commented on packages/react/src/components/radio-card-group/radio-card.tsx
> +    ChangeEvent, ReactElement,
Encore une fois que ça passe le lint 🤔 
```suggestion
import {
    ChangeEvent, 
    ReactElement,
    ReactNode
    isValidElement
```

2023-09-19 19:40 UTC, meriouma commented on packages/react/src/components/radio-card-group/radio-card-group.tsx
> +import { RadioCardProps, isRadioCard } from './radio-card';
```suggestion
import React, { ReactElement, useMemo, VoidFunctionComponent } from 'react';
import { RadioCardProps, isRadioCard } from './radio-card';
```

2023-09-19 19:40 UTC, meriouma commented on packages/react/src/components/radio-card-group/radio-card-group.tsx
> +    label?: string;
```suggestion
    label?: string;
    orientation?: 'horizontal' | 'vertical';
```

2023-09-19 19:40 UTC, meriouma commented on packages/storybook/stories/radio-card-group.stories.tsx
> +        <RadioCard data-testid="some-data-testid" name="story1" label="Card 1" value="card1">
Faudrait que les `name` soient uniques par story pour pas avoir le glitch des flèches. Tu pourrais changer pour le nom de la story. Genre
`RadioCard  name="Horizontal"`
Par contre j'ai pas trouvé comment arranger ça pour la default story qui apparait 2 fois dans la page.

2023-09-19 20:08 UTC, meriouma approved these changes

2023-09-20 07:06 UTC, LarryMatte commented on packages/react/src/components/radio-card-group/styled-components.ts
> +function getLabelBorderColor({ disabled, isChecked, theme }: CardProps): string {
border color selon l'état:
default: `#60666E`
checked: `#006296`
disabled: `#B7BBC2`
hover: `#1B1C1E`
Voir [Figma](https://www.figma.com/file/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?type=design&node-id=87-24921&mode=dev)

2023-09-20 07:12 UTC, LarryMatte commented on packages/react/src/components/radio-card-group/radio-card.tsx
> +                aria-describedby={`description-${id}`}
n'est plus nécessaire depuis les modifications fait au code dans Notion

2023-09-20 07:13 UTC, LarryMatte commented on packages/react/src/components/radio-card-group/radio-card.tsx
> +                <S.Description aria-hidden disabled={disabled} id={`description-${id}`} isMobile={isMobile} isChecked={isInputChecked}>
`aria-hidden` n'est plus nécessaire depuis les modifications fait au code dans Notion

2023-09-20 07:18 UTC, LarryMatte commented on packages/react/src/components/radio-card-group/styled-components.ts
> +    color: ${getContentColor};
Le label (title) et le texte (description) ont toujours la même couleur donc tu pourrais probablement bouger la propriété `color` dans ton container `Card` et la supprimer ici et dans `Description`

2023-09-20 07:18 UTC, LarryMatte commented on packages/react/src/components/radio-card-group/styled-components.ts
> +    color: ${getContentColor};
Le label (title) et le texte (description) ont toujours la même couleur donc tu pourrais probablement bouger la propriété `color` dans ton container `Card` et la supprimer ici et dans `Title`

2023-09-22 16:07 UTC, LarryMatte approved these changes

2023-09-22 17:19 UTC, meriouma approved these changes

2023-09-22 17:19 UTC, merged