feat(MenuButton): groups and icons
kronostechnologies/design-elements pull request #595
Opened 2023-09-14 14:14 UTC by savutsang

## PR Description
DS-638

New features:
- Options can now have icons.
- Options can now be grouped.

Fixes: 
- Add an aria-label on the button when it contains only an icon.
- Remove the "direction" attribute from the html (the menu position was now renamed to placement).
- Remove one unnecessary div.

![image](https://github.com/kronostechnologies/design-elements/assets/3039571/55ec1fe0-f8b2-4ee5-b569-d672212f6581)
![image](https://github.com/kronostechnologies/design-elements/assets/3039571/229c670a-2aa2-4136-92a2-685c935d87e4)

## New component checklist
- [x] The new component and its tests are in the same component folder.
- [x] The component is unit tested and/or snapshot tested.
- [x] All of the relevant Storybook stories have been added to the `storybook` package.
- [x] There are no linting errors or warnings in the modified/new code.
- [x] All GitHub checks are successful.

2023-09-14 16:48 UTC, savutsang commented
The bug for the Submenu will be done in another PR

2023-09-18 21:43 UTC, LarryMatte approved these changes
LGTM
tout semble fonctionner proprement (à l'exception du bug de sub-level)

2023-09-19 00:33 UTC, pylafleur reviewed
Quelques corrections mineures. En général, je trouve que le noms des types finit par être un peu mêlant mais j'ai pas de meilleure suggestion.

2023-09-19 00:33 UTC, pylafleur commented on packages/react/src/components/menu/menu.tsx
> +function getListOptions(options: MenuItem[]): ListItem[] {
Cette fonction devrait probablement s'appeler `getListItems`

2023-09-19 09:01 UTC, LarryMatte commented on packages/react/src/components/menu/menu.tsx
> +const IconArea = styled.div`
Tu peux probablement même enlever la `<div>` et ajouter les style directement sur le `svg`

2023-09-19 09:19 UTC, LarryMatte requested changes

2023-09-19 09:19 UTC, LarryMatte commented on packages/react/src/components/menu/menu.tsx
> +    width: 16px;
`px` --> `rem`

2023-09-19 13:02 UTC, pylafleur commented on packages/react/src/components/menu/menu.tsx
> +    width: 16px;
J'étais pas certain mais je viens de vérifier et on peut passer une dimension en `rem` dans les attributs `width` et `height` d'un élément `<svg>` . Donc on pourrait passer la valeur `1rem` dans la prop `size` du component `<Icon>`.

2023-09-19 18:10 UTC, savutsang commented on packages/react/src/components/menu-button/menu-button.tsx
> +                    aria-label="Menu"
@LarryMatte Est-ce que le user peut specifier le aria-label qu'il veut sur le icon?

2023-09-19 18:25 UTC, savutsang commented
> Quelques corrections mineures. En général, je trouve que le noms des types finit par être un peu mêlant mais j'ai pas de meilleure suggestion.

Oui moi avec ca me gosse aussi, j'ai pense longtemps sans trouver de quoi de mieux que ca.

2023-09-19 19:04 UTC, meriouma reviewed
J'ai fait un petit tour sur le code, Pierre-Yves et Larry ont l'air bien partis pour le reste 😛

2023-09-19 19:04 UTC, meriouma commented on packages/react/src/components/menu/menu.tsx
> +    const indexCounterPerLevel: { [key: string]: number } = {};
Tu pourrais utiliser une `Map<string, number>` à la place je pense.

2023-09-19 19:41 UTC, savutsang commented on packages/react/src/components/menu/menu.tsx
> +    width: 16px;
Le div sera enleve. Pour l'icon, pas sur du rem... je pense c'est mieux de garder la meme facon qu'on le fait ailleur avec `<Icon size="16" />`

2023-09-19 19:45 UTC, savutsang commented on packages/react/src/components/menu-button/menu-button.tsx
> +    menuPlacement?: MenuPlacement;
Est-ce que si je change la mon PR title c'est suffisant, genre le PR sera quash... ou si je doit carrement changer le commit lui-meme?

2023-09-19 20:09 UTC, meriouma commented on packages/react/src/components/menu-button/menu-button.tsx
> +    menuPlacement?: MenuPlacement;
Le nom de la PR ça devrait être suffisant si tu utilises le squash and merge.

2023-09-20 02:31 UTC, pylafleur commented on packages/react/src/components/menu/menu.tsx
> +    width: 16px;
Ouais, j'ai vu qu'on avait la valeur fixe de 16 ailleurs mais le résultat est mieux en `rem` selon moi. Exemple avec le listbox (le crochet de l'Option A est en rem, il s'adapte à la taille du texte, l'autre est fixe à 16px):
<img width="196" alt="image" src="https://github.com/kronostechnologies/design-elements/assets/1416333/a588a821-d4a5-4615-a297-43d29432e2c0">

2023-09-20 05:11 UTC, LarryMatte commented on packages/react/src/components/menu-button/menu-button.tsx
> +                    aria-label="Menu"
Oui l'utilisateur doit pouvoir choisir le label de l'icône. "Menu" en lui même n'indique pas grand chose aux utilisateurs donc le label va devoir être plus spécifique selon le contexte d'utilisation.
e.g., "_show more options_" pourrait être le label du bouton icône.

2023-09-20 18:31 UTC, savutsang commented on packages/react/src/components/menu/menu.tsx
> +    const indexCounterPerLevel: { [key: string]: number } = {};
Effectivement c'est plus correct avec un Map.

Done.

2023-09-25 17:23 UTC, savutsang commented
@LarryMatte J'ai corrige le submenu dans ce PR.
![image](https://github.com/kronostechnologies/design-elements/assets/3039571/91c723e5-633b-47f4-a1b5-56b36a6f782e)

2023-09-25 18:45 UTC, savutsang commented on packages/react/src/components/menu-button/menu-button.tsx
> +    menuPlacement?: MenuPlacement;
Puisque je ne suis pas sur qui et quand ca sera merge, pour avoir l'esprit tranquille, j'ai decide de edit mes commits pour ajouter le "!", en meme temps tant qu'a faire j'ai rebase et squash le tout.

2023-09-27 18:58 UTC, savutsang commented on packages/react/src/components/menu/menu.tsx
> +        const isSubMenu = listItems !== list;
J'ai essaye de benchmark avec <Profiler> mais les chiffres sont trop petit <1ms pour voir une difference.  J'ai essaye de wrapper la main list dans un `{useMemo(() => renderItems(list), [list])}` et la non plus je vois pas de gain.

2023-10-24 15:16 UTC, LarryMatte approved these changes

2023-10-24 18:51 UTC, pylafleur approved these changes
LGTM!

Il resterait p-e à valider avec @meriouma pour le concern de performance qui avait été soulevé

2023-10-26 01:31 UTC, meriouma approved these changes

2023-10-26 01:31 UTC, meriouma commented on packages/react/src/components/menu/menu.tsx
> +        const isSubMenu = listItems !== list;
Je pense que tes tests sont probablement bien suffisants pour l'instant!

2023-10-26 14:32 UTC, merged