feat(NumericInput): add new component
kronostechnologies/design-elements pull request #614
Opened 2023-10-11 19:26 UTC by savutsang

feat(MenuButton): groups and icons

## PR Description
DS-872

Numeric input that has adornment at the start or end of the input.

![image](https://github.com/kronostechnologies/design-elements/assets/3039571/c588b937-befa-414e-aade-e0641e989efa)

## New component checklist
- [x] The new component and its tests are in the same component folder.
- [x] The component is unit tested and/or snapshot tested.
- [x] All of the relevant Storybook stories have been added to the `storybook` package.
- [x] There are no linting errors or warnings in the modified/new code.
- [x] All GitHub checks are successful.

2023-10-11 20:07 UTC, pylafleur commented
Je vais poursuivre le review demain mais en attendant, j'ai cette erreur en démarrant le storybook

<img width="866" alt="image" src="https://github.com/kronostechnologies/design-elements/assets/1416333/2cb0c2c6-cd7c-4288-b614-66bddeb73380">

2023-10-12 13:40 UTC, kbeaulieu reviewed
J'ai la même erreur que PY au niveau du storybook.

Sinon, good job! 👌

2023-10-12 13:40 UTC, kbeaulieu commented on packages/storybook/stories/numeric-input.stories.tsx
> +        adornment="%"
Le _adornment_ semble avoir un background différent du reste de l'input. Je pense que ça diffère de la maquette.
<img width="259" alt="image" src="https://github.com/kronostechnologies/design-elements/assets/3943905/cfb31b1f-f02c-4850-9697-ce6cf319ffa8">

2023-10-12 13:40 UTC, kbeaulieu commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +    const fieldId = useMemo(() => id || uuid(), [id]);
On pourrait créer un hook `useId` / `useFieldId` et le réutiliser dans les autres components.

2023-10-12 13:40 UTC, kbeaulieu commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        }
Je testerais chaque branche idéalement.

2023-10-12 13:40 UTC, kbeaulieu commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        }
Même chose ici

2023-10-12 19:10 UTC, pylafleur commented
Erreur similaire encore 😅 

![image](https://github.com/kronostechnologies/design-elements/assets/1416333/62e7b08c-e380-47ba-966c-de31a324aad8)

2023-10-12 19:57 UTC, savutsang commented
> Erreur similaire encore 😅
> 
> ![image](https://user-images.githubusercontent.com/1416333/274707173-62e7b08c-e380-47ba-966c-de31a324aad8.png)

J'ai du faire un workaround a cause de ce problem ci (https://jira.equisoft.com/browse/DS-800), et je viens de me rendre compte que mon StoryBook manque certain typings a cause de ca. 

Je vais trouver un meilleur fix et push un autre PR pour corriger ca pour de bon.

2023-10-12 20:05 UTC, savutsang commented on packages/storybook/stories/numeric-input.stories.tsx
> +        adornment="%"
Nice, mais comment ca ton storybook a un background gris? t'a hack dans le browser? Anyway c'est fixed.

2023-10-13 15:06 UTC, kbeaulieu commented on packages/storybook/stories/numeric-input.stories.tsx
> +        adornment="%"
Non j'ai pas fait pas de changement 🤔

2023-10-13 19:35 UTC, savutsang commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        }
J'ai ajoute plus de unit tests

2023-10-13 19:35 UTC, savutsang commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        }
J'ai ajoute plus de unit tests

2023-10-13 20:31 UTC, pylafleur requested changes
Je bloque à cause de l'inversion du Home/End.

Aussi, il semble y avoir 1px de décalage entre le texte de l'input et l'_adornment_. J'ai pas exploré plus que ça, je sais pas si c'est quelque chose qu'on peut régler:
![image](https://github.com/kronostechnologies/design-elements/assets/1416333/767e8f7b-90c6-4b4f-89c6-48c14c3b7bd5)

2023-10-13 20:31 UTC, pylafleur commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        if (event.key === 'End') {
Le comportement de Home et End est inversé!

2023-10-13 20:31 UTC, pylafleur commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +            validationErrorMessage={validationErrorMessage ?? ''}
Pour la validation, est-ce qu'on voudrait afficher automatiquement le message d'erreur si la valeur déroge du min/max/step? Contrôler ce comportement avec une prop `validate: boolean`?

2023-10-13 21:03 UTC, pylafleur commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        if (event.key === 'End') {
Oh wow, t'as raison! Mais me semble que ça devrait être l'inverse, non? Home donne la plus petite valeur et End la plus grande?

2023-10-13 21:09 UTC, savutsang commented
> Je bloque à cause de l'inversion du Home/End.
> 
> Aussi, il semble y avoir 1px de décalage entre le texte de l'input et l'_adornment_. J'ai pas exploré plus que ça, je sais pas si c'est quelque chose qu'on peut régler d'une façon clean? ![image](https://user-images.githubusercontent.com/1416333/275042153-767e8f7b-90c6-4b4f-89c6-48c14c3b7bd5.png)

J'ai pas ce probleme dans mon Chrome.
![image](https://github.com/kronostechnologies/design-elements/assets/3039571/75466d30-35de-4bd4-a9b9-1dc99e006709)

Sans pouvoir le reproduire je sais pas trop quoi changer aveuglement, le CSS est quand meme bon pour le positionner bien au centre. C'est p-t du au fait que j'ai pas le meme OS?

2023-10-13 21:19 UTC, pylafleur commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        if (event.key === 'End') {
C'est aussi un comportement qui entre en conflit avec le positionnement du curseur à l'intérieur du input... Je sais pas s'il va falloir attendre @LarryMatte pour clarifier ça?

2023-10-13 21:23 UTC, savutsang commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        if (event.key === 'End') {
Ca fait du sens quand tu visualize en horizontal
```
Home <-----> End
0 <-----> 100
```

Mais dans notre cas, c'est du vertical et considerant les fleches aussi dans l'equation, ca fait du sens que Home et Up vont de pair.

```
Home
ArrowUp

ArrowDown
End
```

2023-10-14 00:53 UTC, pylafleur commented
Finalement oublie ça pour l'alignement, c'est probablement un truc de OS en effet. Quand je zoom ça devient correct.

Aussi, j'avais pas contre-vérifié avec ton screenshot dans la description, j'aurais vu que c'était ok pour toi, sorry!

2023-10-14 01:00 UTC, pylafleur commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        if (event.key === 'End') {
C'est pas fou, j'avais pas vu ça de cette façon!

J'ai cherché un peu dans d'autres librairies de composants et je n'ai pas vu ce comportement ailleurs. À cause de la possibilité de confusion et du fait que ça empêche de déplacer le curseur avec Home/End, mon avis personnel serait de laisser tomber cette mécanique.

J'aimerais quand même avoir un avis supplémentaire de la team, ou bien attendre Larry dépendamment de l'urgence de livrer ce component!

2023-10-14 01:35 UTC, savutsang commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +        if (event.key === 'End') {
Perso ca me gosse moi aussi, je prefere laisser le Home/End pour bouger le cursor comme nativement dans les textbox. On discutera avec @LarryMatte

2023-10-16 17:49 UTC, savutsang commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +    const fieldId = useMemo(() => id || uuid(), [id]);
J'ai creer la function mais je pense pas le changer dans tous les components pour le moment pour pas polluer le PR.

2023-10-16 18:32 UTC, savutsang commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +            validationErrorMessage={validationErrorMessage ?? ''}
J'hesite beaucoup dans ce point ci.  Je prefere plus des components qui font s'occupe juste de l'affichage UI avec ce que le user lui specifie explicitement dans les props, sans avoir de logique integre.  Des fois ca simplifie pour le user, mais des fois ca peut aussi etre nuisible (ex: des messages different entre erreurs de min ou max). 

Presentement le user a deja les champ "valid" et "validationErrorMessage" qui permet d'afficher explicitement les erreurs, je me demande si on voudrais un autre validate de plus.

Bref, ca merite une discussion en equipe car ce strategie sera probablement repris a travers les autre components ou future.

2023-10-17 23:48 UTC, pylafleur commented on packages/react/src/components/carousel/carousel.test.tsx
> +jest.mock('../../utils/uuid');
Le mock devrait avoir une implémentation alternative qui retourne une string quelconque. Sinon, plusieurs attributs ont une valeur `undefined` et disparaissent des snapshots, comme `aria-controls` pour le snapshot du carousel.

2023-10-18 17:50 UTC, savutsang commented on packages/react/src/components/carousel/carousel.test.tsx
> +jest.mock('../../utils/uuid');
Effectivement, ca permettrais de faire de meilleur snapshots

2023-10-23 18:06 UTC, kbeaulieu approved these changes

2023-10-25 18:12 UTC, pylafleur commented on packages/react/src/components/numeric-input/numeric-input.tsx
> +            validationErrorMessage={validationErrorMessage ?? ''}
Ça pourrait en effet être discuté pour le futur, on a d'autres composants qui font de la validation. Faudrait décider si on fournit un comportement de validation configurable (min/max/step, max length, etc...).

Mais on fera ça plus tard, c'est un peu hors scope pour cette PR!

2023-10-25 18:13 UTC, pylafleur approved these changes

2023-10-25 21:07 UTC, merged