feat(TextInput): added ariaDescribedBy for hint and validations
kronostechnologies/design-elements pull request #631
Opened 2023-10-24 16:47 UTC by JsGarneau

La partie du text (required) avait été fait dans la carte DS-801

J'ai modifier un peu le DOM pour que ca fit avec les specs de Larry, ca impact tout les inputs.

2023-10-24 18:35 UTC, pylafleur commented on packages/react/src/components/text-input/text-input.tsx
> +        let describedBy = ariaDescribedBy || '';
Utilise `undefined` comme fallback, ça va retirer l'attribut `aria-describedby` au lieu de le laisser vide

2023-10-24 18:35 UTC, pylafleur commented on packages/react/src/components/text-input/text-input.tsx
> +        if (!validity) describedBy += ` ${id}_invalid`;
De préférence, toujours des `{ ... }`

2023-10-25 18:34 UTC, savutsang commented on packages/react/src/components/text-input/text-input.tsx
> +    const [getAriaDescribedBy, setAriaDescribedBy] = useState('');
Le useState semble inutile ici, le value est plutot calculated, a la limite un usememo si c'est pour optimiser.

2023-10-31 18:04 UTC, pylafleur commented on packages/react/src/components/text-input/text-input.test.tsx.snap
> +    aria-describedby="undefined"
Il manquerait probablement juste un check qui retourne `undefined` (plutôt qu'une string) si les 3 parties sont vides (la prop, le hint et la validity).

2023-10-31 18:25 UTC, LarryMatte requested changes

2023-10-31 18:25 UTC, LarryMatte commented on packages/react/src/components/text-input/text-input.tsx
> +                aria-describedby={processedAriaDescribedBy}
Il y a un `undefined` quand un des éléments liés (hint, error message) n'est pas présent. 

<img width="529" alt="Screenshot 2023-10-31 at 2 20 23 PM" src="https://github.com/kronostechnologies/design-elements/assets/3722754/b224c46c-0463-49d0-abbd-2fefec091c5e">

2023-11-01 13:15 UTC, pylafleur approved these changes

2023-11-01 19:19 UTC, savutsang commented on packages/react/src/components/text-input/text-input.tsx
> +        return `${ariaDescribedBy || ''} ${invalidAria} ${hintAria}`.trim();
Nitpick: Juste une affaire de beautify le rendu, mais lorsque t'a juste ariaDescribedBy et hintAria, il y aurait 2 spaces entre les 2 ids.

2023-11-01 19:22 UTC, savutsang approved these changes

2023-11-03 15:20 UTC, merged