fix(DatePicker): Call calendar open/close events in CalendarButton on MouseDown callback
kronostechnologies/design-elements pull request #725
Opened 2024-02-06 17:22 UTC by ogermain-kronos

https://equisoft.atlassian.net/browse/DS-990

Le callback `handleCalendarButtonMouseDown` du component `CalendarButton` change le state open/close du calendrier et causait des problèmes avec les callbacks `onCalendarOpen/onCalendarClose` du component `DatePicker`

La solution est de caller ces callbacks dans le `handleCalendarButtonMouseDown` pour éviter de les caller aux moments où ils devraient pas.

Avant (clic pour ouverture du calendrier):
![image](https://github.com/kronostechnologies/design-elements/assets/6412423/373bba79-6592-4884-ada9-7d0918fb9640)

Après (idem)
![image](https://github.com/kronostechnologies/design-elements/assets/6412423/867bfab2-ef70-4b63-99c6-a2748f985133)

2024-02-06 19:48 UTC, meriouma requested changes
C'était pas une mauvaise idée, mais les callbacks ne sont plus appelés avec la navigation clavier 😬

2024-02-07 01:09 UTC, pylafleur reviewed
Petite suggestion de syntaxe et ça serait p-e pas pire d'ajouter un test unitaire pour s'assurer que le bon comportement est maintenu dans le futur!

2024-02-07 01:10 UTC, pylafleur commented on packages/react/src/components/date-picker/date-picker.tsx
> +                    }
Tu peux faire ça ici pis aux 3 autres places plus bas!
```suggestion
                    onCalendarClose?.();
```

2024-02-07 18:20 UTC, pylafleur approved these changes

2024-02-07 20:51 UTC, meriouma approved these changes

2024-02-07 20:53 UTC, merged