feat(ProgressTracker): non linear and clickable
kronostechnologies/design-elements pull request #726
Opened 2024-02-09 19:34 UTC by savutsang

- Updated UI
- Navigable with onclick or href
- Non linear progression
- Show incomplete icon for uncompleted steps

https://equisoft.atlassian.net/browse/DS-735
https://www.notion.so/equisoft/Progress-Tracker-9d6af548431144e8908970ff4602f851

2024-02-12 20:59 UTC, meriouma reviewed
Comme discuté tantôt, il reste aussi la question de la zone cliquable et du curseur pointer.

2024-02-12 20:59 UTC, meriouma commented on packages/react/src/components/progress-tracker/progress-tracker.tsx
> +        step.onClick!(stepNumber);
`step.onClick?.(stepNumber);` ?

2024-02-15 14:55 UTC, savutsang commented on packages/react/src/components/icon/icon.tsx
> +    alertFilledRound: AlertFilledRound,
Excellente idee

2024-02-15 15:12 UTC, savutsang commented on packages/react/src/components/progress-tracker/progress-tracker.tsx
> +        screenReaderText = 'completed';
J'ai ajoute la traduction que j'avais oublie, mais sinon pour les keys j'ai opte pour des striings statics a place car t'a des cas que ca n'utilise pas step.nonLinearState.

2024-02-15 15:26 UTC, savutsang commented
> Comme discuté tantôt, il reste aussi la question de la zone cliquable et du curseur pointer.

J'ai limite le zone clickable au contenu. J'imagine le cursor pointer c'est pour la meme chose.

2024-02-15 19:39 UTC, LarryMatte requested changes
quelques commentaires ici et là

2024-02-15 19:39 UTC, LarryMatte commented on packages/react/src/components/progress-tracker/progress-tracker.tsx
> +        <Container className={className} aria-label={ariaLabel} as={hasAnyLink ? 'nav' : undefined}>
Je ne suis pas certain si c'est déjà en place, mais serait-il envisageable de notifier le développeur s'il n'a pas utilisé l'attribut `aria-label` pour décrire la `section`, ou la balise `nav` ?

2024-02-15 19:39 UTC, LarryMatte commented on packages/storybook/stories/progress-tracker.stories.tsx
> +export const Normal: Story = () => (
Il n'y aura probablement jamais de progress tracker sans texte sous les steps. Est-ce que c'est pertinent de garder l'exemple? Je crains que ca puisse éventuellement encourager une utilisation inappropriée du composant.

2024-02-15 19:39 UTC, LarryMatte commented on packages/storybook/stories/progress-tracker.stories.tsx
> +export const Steps: Story = () => (
Il n'y aura probablement jamais de progress tracker sans texte sous les steps. Est-ce que c'est pertinent de garder l'exemple? Je crains que ca puisse éventuellement encourager une utilisation inappropriée du composant.

2024-02-15 19:39 UTC, LarryMatte commented on packages/react/src/components/progress-tracker/progress-tracker.tsx
> +            {showUncompletedIcon && <UncompletedIcon name='alertCircle' size='16' />}
Est-ce qu'on peut ajouter un `aria-hidden` sur l'icône uncompleted?

2024-02-16 14:36 UTC, maboilard commented
J'ai 2 soulevé 2 trucs:
- Dans le visuel de progress-tracker-step-completed, le style de texte pour le numéro devrait être  --font-semi-bold
- Sinon la couleur de backround de progress-tracker-step-completed ainsi que la couleur de border de progress-tracker-step-current (en plus du bridge) ne sont pas de la même couleur que dans Figma. La couleur dans Figma est #006296

À part ça tout est beau pour moi!

2024-02-16 17:46 UTC, savutsang commented on packages/storybook/stories/progress-tracker.stories.tsx
> +export const Normal: Story = () => (
Je vais mettre le `label` de chaque step a obligatoire puisque le sans label n'est pas un cas d'utilisation valide a ce moment ci.

2024-02-16 17:47 UTC, savutsang commented on packages/react/src/components/progress-tracker/progress-tracker.tsx
> +        <Container className={className} aria-label={ariaLabel} as={hasAnyLink ? 'nav' : undefined}>
J'ai ajoute un warning lorsque le ariaLabel est manquante

2024-02-16 18:48 UTC, LarryMatte approved these changes
All good en ce qui me concerne

2024-02-20 02:27 UTC, meriouma reviewed
Petits détails, sinon LGTM.

2024-02-20 02:27 UTC, meriouma commented on packages/react/src/components/progress-tracker/progress-tracker.test.tsx
> +            .map((w) => getByTestId(w, 'progress-tracker-label').text());
Ça faut pour tous les tests, mais j'aurais gardé la ligne vide après le wrapper.
```suggestion
        const wrapper = mountWithTheme(<ProgressTracker steps={steps} value={1} />);

        const allStepsLabels = findByTestId(wrapper, 'progress-tracker-step-', '^')
            .map((w) => getByTestId(w, 'progress-tracker-label').text());
```
Ça permet de mieux découper visuellement le given/when/then et d'identifier que ce que tu testes finalement c'est le render initial.

2024-02-20 02:27 UTC, meriouma commented on packages/react/src/components/progress-tracker/progress-tracker.test.tsx
> +            const wrapper = renderWithProviders(<ProgressTracker steps={steps} value={3} />);
```suggestion
            const wrapper = renderWithProviders(<ProgressTracker steps={steps} linear={false} value={3} />);
```

2024-02-20 23:22 UTC, meriouma commented on packages/react/src/components/progress-tracker/progress-tracker.test.tsx
> +            const wrapper = renderWithProviders(<ProgressTracker steps={steps} value={3} />);
Je suis un peu confus sur à quoi sert la prop `linear` si on la met pas à false sur le test `non linear`?

2024-02-21 14:59 UTC, savutsang commented on packages/react/src/components/progress-tracker/progress-tracker.test.tsx
> +            const wrapper = renderWithProviders(<ProgressTracker steps={steps} value={3} />);
Je me suis trompe en lisant lol,. C'est corrige.

2024-02-21 16:29 UTC, meriouma approved these changes

2024-02-21 16:29 UTC, merged