chore(global-banner, theme): update variants
kronostechnologies/design-elements pull request #751
Opened 2024-02-29 19:25 UTC by hebernardEquisoft

[DS-1003](https://equisoft.atlassian.net/browse/DS-1003)

## Description
Ici on vient mettre à jour les variantes de Global Banner par rapport aux maquettes [Figma](https://www.figma.com/file/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?type=design&node-id=4-74&mode=design&t=SqC6KQdUtLV20YxL-0)  de l'équipe design.

## Tests fonctionnels
- [ ] Valider le bon fonctionnement des global banners
- [ ] Valider minutieusement le bon theming de chacune des variantes de global banner par rapport aux maquettes

## Screenshots
![image](https://github.com/kronostechnologies/design-elements/assets/132286421/f94322dc-22a2-4068-82a6-6ce24878e485)

2024-03-06 19:31 UTC, maboilard commented
Je changerais la couleur background au hover du bouton tertiaire par warning-20. En ce moment, le texte en noir n'est plus lisible sinon. Aussi, dans la story de la Banner "Discovery", il est écrit "Discovery. Info message.". Peut-être juste remplacer le terme "Info" par "Discovery". À part ça, all good pour moi.
![image](https://github.com/kronostechnologies/design-elements/assets/52255752/bffd9e29-d67a-4af0-a225-6d7cc3466bc9)

2024-03-06 19:32 UTC, maboilard requested changes
La couleur du bouton au hover est différente de celui du Toast, ce qui ne devrait pas être le cas. Il faudrait donc changer la couleur pour qu'elle soit uniforme au Toast. 
![image](https://github.com/kronostechnologies/design-elements/assets/52255752/56cfe8b5-4d59-40dc-b0c6-1600f20ce385)

2024-03-12 19:28 UTC, savutsang commented
@meriouma l'a mentionne dans un PR precedent, ceci est un breaking change puisque on a change les valeurs des props.

2024-03-15 20:13 UTC, meriouma reviewed
Petits questionnements/suggestions, sinon LGTM.

2024-03-15 20:13 UTC, meriouma commented on packages/react/src/components/global-banner/global-banner.tsx
> +): FlattenSimpleInterpolation {
Je pense que je sortirais le state de l'objet pour utiliser les props `ActionButtonProps` directement
```suggestion
function getActionButtonColors(
    { bannerType, theme }: StyledProps<ActionButtonProps>,
    state: GlobalBannerButtonState,
): FlattenSimpleInterpolation {
```

2024-03-15 20:13 UTC, meriouma commented on packages/react/src/components/global-banner/global-banner.tsx
> +    }
```suggestion
    ${(props) => getActionButtonColors(props, 'default')};

    &:hover {
        ${(props) => getActionButtonColors(props, 'hover')};
    }
```

2024-03-15 20:13 UTC, meriouma commented on packages/react/src/components/global-banner/global-banner.tsx
> +`;
Je ferais la même chose ici je pense.

2024-03-18 13:34 UTC, maboilard approved these changes
Seems good to me!

2024-03-18 18:24 UTC, meriouma reviewed
Petit détail, sinon LGTM!

2024-03-18 18:24 UTC, meriouma commented on packages/react/src/components/global-banner/global-banner.tsx
> +): FlattenSimpleInterpolation {
```suggestion
): FlattenSimpleInterpolation | null {
```

2024-03-18 18:24 UTC, meriouma commented on packages/react/src/components/global-banner/global-banner.tsx
> +    return css``;
```suggestion
    return null;
```

2024-03-18 18:24 UTC, meriouma commented on packages/react/src/components/global-banner/global-banner.tsx
> +        color: ${theme.component[`global-banner-${bannerType}-dismiss-button${statePrefix}-text-color`]};
```suggestion
            background-color: ${theme.component[`global-banner-${bannerType}-dismiss-button${statePrefix}-background-color`]};
            color: ${theme.component[`global-banner-${bannerType}-dismiss-button${statePrefix}-text-color`]};
```

2024-03-19 14:22 UTC, pylafleur reviewed
LGTM, juste un alignement à corriger!

2024-03-19 14:22 UTC, pylafleur commented on packages/react/src/components/global-banner/global-banner.tsx
> +    `;
```suggestion
        `;
```

2024-03-19 14:47 UTC, pylafleur approved these changes

2024-03-19 14:49 UTC, merged