chore(storybook): update structure and themes
kronostechnologies/design-elements pull request #762
Opened 2024-03-06 20:13 UTC by Genmoree

DS-1017

- New storybook overall structure
- Themes and color update
- Equisoft logo added

2024-03-06 20:57 UTC, LarryMatte requested changes
Quelques petits commentaires ici et là.
GJ pour ta 1ere PR!

2024-03-06 20:57 UTC, LarryMatte commented on packages/storybook/.storybook/manager-head.html
> +        background-color:#F1F2F2;
Ajouter un espace avant le `#`

2024-03-06 20:57 UTC, LarryMatte commented on packages/storybook/.storybook/manager-head.html
> +        color: white;
remplacer `white` par `#FFFFFF`

2024-03-06 20:57 UTC, LarryMatte commented on packages/storybook/.storybook/manager
> +        BrandUrl: "https://equisoft.dev",
Ici ce serait probablement l'adresse vers le site web de la cie

2024-03-06 20:57 UTC, LarryMatte commented on packages/storybook/.storybook/manager
> +        brandImage: "/LogoEquisoft.png", // using publicly served /public directory
Ajoute un "." devant le premier "/". Ça ne load pas sinon de mon côté.
`brandImage: "./LogoEquisoft.png"`
<img width="241" alt="Screenshot 2024-03-06 at 3 35 44 PM" src="https://github.com/kronostechnologies/design-elements/assets/3722754/ee516e31-7c2d-413e-b6e9-79e771402745">

2024-03-06 20:57 UTC, LarryMatte commented on packages/storybook/.storybook/manager
> +
Ne laisse pas de ligne vide ici

2024-03-08 18:06 UTC, savutsang commented on packages/storybook/stories/0-intro.mdx
> +        <img src="avatar-Laury.png" alt="Laury's Avatar" style={{ marginBottom: '-14px' }} />
L'image de Laury est broken, le nom du fichier c'est un L minuscule.

2024-03-08 18:09 UTC, savutsang commented on packages/storybook/.storybook/manager.ts
> +        brandImage: "./LogoEquisoft.png", // using publicly served /public directory
Ca serait preferable d'utiliser des SVG, de meme que pour les avatars.

2024-03-08 20:18 UTC, savutsang commented on packages/storybook/stories/0-intro.mdx
> +        <img src="avatar-Laury.png" alt="Laury's Avatar" style={{ marginBottom: '-14px' }} />
L'image de Laury est broken

```suggestion
        <img src="avatar-laury.png" alt="Laury's Avatar" style={{ marginBottom: '-14px' }} />
```

2024-03-11 13:01 UTC, pylafleur commented
J'ai pas identifié la source mais le logo Equisoft est trop large, ce qui brise l'alignement dans le menu de gauche. Ça se règle lorsqu'on retire les propriétés `max-width` et `max-height` du CSS de l'image.

Avant:
![image](https://github.com/kronostechnologies/design-elements/assets/1416333/9bff8d53-e559-4eab-8024-88288d441d7e)

Après:
![image](https://github.com/kronostechnologies/design-elements/assets/1416333/bf977703-f499-456d-b498-01f5b5a77d9e)

2024-03-11 15:31 UTC, pylafleur submitted a review, later dismissed
LGTM! Good job!

2024-03-11 18:23 UTC, savutsang submitted a review, later dismissed

2024-03-12 17:47 UTC, LarryMatte requested changes

2024-03-12 17:47 UTC, LarryMatte commented on packages/storybook/stories/3-changelog.mdx
> +Lorem iosum
Ajoute un texte du genre "à venir" ou quelque chose de similaire. Lorem ipsum ca manque de serieux un peu

2024-03-12 20:06 UTC, LarryMatte approved these changes

2024-03-15 13:29 UTC, pylafleur approved these changes

2024-03-19 18:03 UTC, merged