chore(focus, theme): update focus border
kronostechnologies/design-elements pull request #770
Opened 2024-03-18 17:19 UTC by hebernardEquisoft

[DS-630](https://equisoft.atlassian.net/browse/DS-630)

## Description
Ici on vient mettre à jour les focus border colors pour chacune des composantes par rapport aux maquettes [Figma](https://www.figma.com/file/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?node-id=0%3A1&mode=dev) de l'équipe design. 

## Tests fonctionnels
- [ ]  Valider le bon fonctionnement du focus dans chacune des composantes avec différents paramètres
- [ ]  Valider minutieusement le bon theming du focus pour chacune des composantes par rapport aux maquettes

2024-03-20 16:23 UTC, savutsang commented on packages/react/src/components/tabs/tab-panel.tsx
> -    ${focus}
Le TabPanel est tabbable selon Notion, si on enleve le focus, il n'y a plus d'indicateur visuel.

2024-03-20 16:43 UTC, savutsang commented on packages/react/src/themes/tokens/component/password-input-tokens.ts
> +    'password-input-show-password-button-disabled-background-color': 'color-neutral-05',
Y a de quoi qui marche pas ici, le bouton n'est pas grise.

![image](https://github.com/kronostechnologies/design-elements/assets/3039571/dd596bd1-83a2-4507-b0af-1d39451f517f)

2024-03-20 16:57 UTC, savutsang commented on packages/react/src/components/password-input/password-input.tsx
> +    input,
Une ligne vide entre la fin des style et le debut d'une nouvelle selector.

2024-03-20 17:01 UTC, savutsang commented on packages/react/src/components/password-input/password-input.tsx
> +                $iconButtonFocused={iconButtonFocused}
Ca ne marcherais pas avec `:focus-within` ?

2024-03-20 17:16 UTC, savutsang commented on packages/react/src/components/password-input/password-input.tsx
> +                $iconButtonFocused={iconButtonFocused}
Vu les changements, on pourrait simplifier tout ca en mettant le bouton a l'exterieur en absolute par dessus le input. Du coup, ca sera le StyledTextInput qui aura le focus style au lieu du Container.

2024-03-20 17:25 UTC, savutsang commented on packages/react/src/components/password-creation-input/password-creation-input.tsx
> +    input,
`::-ms-reveal` n'a pas besoin d'etre sur les 4 selectors, c'est 2 concerns separe ici.

2024-03-20 17:35 UTC, hebernardEquisoft commented on packages/react/src/components/tabs/tab-panel.tsx
> -    ${focus}
Ah bien vu! 
J'avais pas remarqué sur Notion, dans le Figma y'avait pas mention de focus sur le TabPanel.
Je le remet rapidement!

2024-03-20 17:43 UTC, savutsang commented on packages/react/src/components/password-input/password-input.tsx
> +        border: none transparent;
C'est plus un hack dur a maintenir de meme. Il y a un isFocusable dans inputStyle(), on pourrait essayer de passer un flag jusqu'a la.  Sinon on pourrait faire un helper undoFocus() similaire a focus().

2024-03-20 18:38 UTC, hebernardEquisoft commented on packages/react/src/components/password-input/password-input.tsx
> +                $iconButtonFocused={iconButtonFocused}
J'ai de quoi qui simplifie en me fiant à ta suggestion. Par contre voici un use case qui remet ces changements en question:
![image](https://github.com/kronostechnologies/design-elements/assets/132286421/43955300-0efd-4234-b436-60302508b03d)

2024-03-20 19:34 UTC, savutsang commented on packages/react/src/components/password-input/password-input.tsx
> +                $iconButtonFocused={iconButtonFocused}
T'a ajoute un `padding-right: var(--size-2halfx)` sur le input lui-meme? Le text devrait arreter au padding.

2024-03-20 19:48 UTC, hebernardEquisoft commented on packages/react/src/components/password-input/password-input.tsx
> +                $iconButtonFocused={iconButtonFocused}
Ah c'est ce qui me manquait! Très fort!

2024-04-02 22:02 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/abstract-button.tsx
> +    ${props.focusable !== false && focus(props, { inverted: props.inverted })};
Ajout de l'option inverted au bouton pour que le focus puisse s'adapter à la situation.

2024-04-02 22:02 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/button.tsx
> +            onBlur={onBlur}
Ajout des propriétés onFocus & onBlur pour le focus des stepper buttons!

2024-04-02 22:03 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/icon-button.tsx
> +            onBlur={onBlur}
Ajout des propriétés onFocus & onBlur pour le focus des stepper buttons!

2024-04-02 22:04 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/search-button.tsx
> +            color: ${({ theme }) => theme.component['button-input-disabled-text-color']};
Renaming des component tokens! Ces tokens seront réutilisé pour certains use cases, comme le datepicker!

2024-04-02 22:05 UTC, hebernardEquisoft commented on packages/react/src/components/card-link/card-link.tsx
> +        border-color: ${({ theme }) => theme.component['card-link-hover-border-color']};
Remplacement de l'utilisation weird du box-shadow pour simuler un border.

2024-04-02 22:07 UTC, hebernardEquisoft commented on packages/react/src/components/checkbox/checkbox.tsx
> +    ${({ theme }) => focus({ theme }, { selector: `+ ${CustomCheckbox}` })};
Simple mise à jour de la fonction globale de focus!

2024-04-02 22:09 UTC, hebernardEquisoft commented on packages/react/src/components/chooser-button/styles/choose.ts
> +    ${({ theme }) => focus({ theme }, { selector: ', input[type="checkbox"]:focus + &, input[type="radio"]:focus + &' })}
Simple mise à jour de la fonction globale de focus!

Aussi j'ai retiré la déclaration du thème `${({ theme }: { theme: ResolvedTheme }) => ` afin qu'on puisse avoir un meilleur visuel dans l'ide du css. Je peux changer si ça cause problème!

2024-04-02 22:10 UTC, hebernardEquisoft commented on packages/react/src/components/combobox/combobox.tsx
> +    margin-top: var(--spacing-half);
Ajout d'un de spacing entre le input du combobox et le listbox. Afin de respecter le Figma!

2024-04-02 22:10 UTC, hebernardEquisoft commented on packages/react/src/components/combobox/combobox.tsx
> +    ${focus};
Mise à jour de la fonction globale de focus

2024-04-02 22:12 UTC, hebernardEquisoft commented on packages/react/src/components/date-picker/calendar-header.tsx
> +const StyledButton = styled(IconButton)`
Remplacement des boutons de navigation dans le header du `DatePickerCalendar` afin de réutiliser notre composante `IconButton` de manière atomique!

2024-04-03 15:42 UTC, savutsang commented on packages/react/src/components/chooser-button/styles/choose.ts
> +    ${({ theme }) => focus({ theme }, { selector: ', input[type="checkbox"]:focus + &, input[type="radio"]:focus + &' })}
Le selector n'est pas propre, c'est comme un hack pour contourner les lacunes du param "selector".

Le param selector n'est pas clair, dans la function c'est vu comme un childs selector (il n'y a rien dans la function qui m'indique autrement, sinon il faudrait faire des params separe ou documenter l'usage).
```
&:${focusTypeSelector} ${baseSelector} {
```

Avec la virgule, tu append d'autre selectors, mais le `&:focus` est encore la, donc ca laisse trainer des unwanted css aussi.

Aussi le ":not" ne functionne pas avec ca, ca donnerait
```
&:not(:focus), 
input[type="checkbox"]:focus + &, 
input[type="radio"]:focus + & {
```

Je me demande a quel point la transition est necessaire, ca ajoute trop de complexite. 

Faidrais p-t avoir une autre facon d'utiliser juste les styles sans les selectors, genre
```
input[type="checkbox"]:not(:focus) + &, 
input[type="radio"]:not(:focus) + & {
  ${unfocusedStyles(...)}
}

input[type="checkbox"]:focus + &, 
input[type="radio"]:focus + & {
  ${focusedStyles(...)}
}
```

2024-04-03 15:56 UTC, savutsang commented on packages/react/src/utils/css-state.ts
> +        &:not(:${focusTypeSelector}) ${baseSelector} {
Suite a l'autre commentaire, t'a probablement pas besoin du `:not()` c'est le meme que normal.

Genre
```
        ${baseSelector} {
            transition: ${transition};
            outline: ${insideFocusBorderWeight} solid transparent;
            outline-offset: ${insideFocusBorderOffset};
        }

        &:${focusTypeSelector} ${baseSelector} {
            transition: ${transition};
            box-shadow: 0 0 0 ${outsideFocusBorderWeight} ${outsideFocusBorderColor};
            outline: ${insideFocusBorderWeight} solid ${insideFocusBorderColor};
            outline-offset: ${insideFocusBorderOffset};
        }
```

2024-04-03 16:56 UTC, savutsang commented on packages/react/src/utils/css-state.ts
> +    const transition = 'all .25s ease-in-out;';
```suggestion
    const transition = 'all .25s ease-in-out';
```

2024-04-03 17:08 UTC, savutsang commented on packages/react/src/utils/css-state.ts
> +    focusTypeSelector?: FocusType;
Je le racourcisserais a `focusType`, c'est assez clair de quoi on parle.

2024-04-03 17:09 UTC, savutsang commented on packages/react/src/utils/css-state.ts
> +    focusTypeSelector?: FocusType;
Je le racourcisserais, c'est assez clair de quoi on parle.

```suggestion
    focusType?: FocusType;
```

2024-04-03 19:22 UTC, maboilard approved these changes
On a fait le testing ensemble et tout est beau pour moi!

2024-04-16 04:04 UTC, meriouma commented on packages/react/src/components/accordion/accordion-item.tsx
> +    z-index: 1;
Pourquoi le z-index ici?

2024-04-16 15:27 UTC, hebernardEquisoft commented on packages/react/src/components/accordion/accordion-item.tsx
> +    z-index: 1;
Probablement des tests que j'avais fait et j'ai oublié de retirer ça. nice catch!

2024-04-16 15:53 UTC, hebernardEquisoft commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding: 4px;
Ça donne ça sinon:
![image](https://github.com/kronostechnologies/design-elements/assets/132286421/93933fe4-4f62-49ae-bace-91432f0f8552)

![image](https://github.com/kronostechnologies/design-elements/assets/132286421/655adb1c-d874-4a48-abcb-e67cc9d0d38c)

2024-04-16 16:01 UTC, hebernardEquisoft commented on packages/react/src/components/date-picker/date-picker.tsx
Ouin ça fait ça aussi pour les composantes d'input similaires avec des boutons au bout (comme le search global & stepper input). Je vais réfléchir à une manière de corriger ça...

2024-04-16 16:05 UTC, meriouma commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding: 4px;
OK. Dans ce cas peut-être juste mettre du padding left et right? Ça me semble un peu gros en top et bottom par rapport aux côtés.
![image](https://github.com/kronostechnologies/design-elements/assets/1082552/f807d276-8349-424f-aeda-2f0998b9870f)

@maboilard ou @LarryMatte vous en pensez quoi?

2024-04-16 17:26 UTC, maboilard commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding: 4px;
Je viens de vérifier et c'est all good pour moi 👍

2024-04-18 20:22 UTC, LarryMatte requested changes

2024-04-22 18:23 UTC, hebernardEquisoft commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding-left: 4px;
Laissons le sans padding dans ce cas!

2024-04-24 19:31 UTC, meriouma submitted a review, later dismissed
J'ai pas retesté les components, mais pour le reste je pense que c'est bon.

2024-04-24 20:08 UTC, pylafleur commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding-left: 4px;
Par contre, le focus overlap le texte du lien présentement... 
![image](https://github.com/kronostechnologies/design-elements/assets/1416333/2f12bd3b-97ad-4f3a-afe5-bfc4077d7e50)
Figma:
![image](https://github.com/kronostechnologies/design-elements/assets/1416333/335144dd-bc1c-4180-9623-3a8476cd4265)

2024-04-24 20:23 UTC, pylafleur commented
J'avais pas donné beaucoup d'attention à cette PR mais je suis pas convaincu par la transition lors du focus.

Comme c'est pas mal le seul élément animé dans nos interfaces, il y a parfois un clash avec d'autres interactions qui n'ont pas de transition. Par exemple, dans le dropdown-list/combobox, le listbox apparait avant que l'animation ne soit complétée sur le focus du textbox.

Aussi, quand on navigue rapidement entre les éléments d'une liste (ex: tabs, icônes de la global navigation), j'ai l'impression que la transition diminue la performance perçue à cause du délai qui est introduit.

Ça reste ma perception personnelle mais je me demande à quel point ça s'inscrit bien dans le reste du langage de notre design.

2024-04-24 20:25 UTC, hebernardEquisoft commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding-left: 4px;
Ouais c'est ce que j'avais essayé avant ave cle padding-left et padding-right avant que Larry me fasse remarquer que ça venait créer trop d'espace dans les paragraphes.

2024-04-25 01:49 UTC, meriouma submitted a review, later dismissed

2024-04-25 01:52 UTC, pylafleur commented on packages/react/src/components/route-link/styles/styled-link.tsx
> +    padding-left: 4px;
C'est toi qui a le dernier mot @LarryMatte!

2024-04-25 01:58 UTC, pylafleur submitted a review, later dismissed
LGTM hormis le padding sur le `Link`

![image](https://github.com/kronostechnologies/design-elements/assets/1416333/fa70bec9-bd5d-4ec8-aed5-c58e153aa702)

2024-04-25 15:27 UTC, LarryMatte submitted a review, later dismissed
Un seul commentaire à fixer et tu es good

2024-04-25 15:27 UTC, LarryMatte commented on packages/react/src/components/chooser-button/styles/choose.ts
> +    transition: all 0.25s ease-in-out;
L'animation ici affecte également le focus. Je crois que l'animation avait été fait pour le background mais comme c'est le seul composant qui semble avoir une anim, j'enlèverais la transition au complet.

2024-04-25 17:53 UTC, LarryMatte approved these changes

2024-04-25 17:55 UTC, merged