docs(storybook): update accordion
kronostechnologies/design-elements pull request #772
Opened 2024-03-19 19:40 UTC by Genmoree

2024-03-19 19:54 UTC, LarryMatte requested changes

2024-03-19 19:54 UTC, LarryMatte commented on packages/storybook/stories/accordion.mdx
> +- **When the content has a deep hierarchy with multiple sublevels:** it may be too complex to be displayed in a flat hierarchy format like accordions. Instead, consider alternatives such as tabs [6].
Ajouter un lien vers le composant Tabs?

2024-03-19 19:54 UTC, LarryMatte commented on packages/storybook/stories/accordion.mdx
> +- To display more information, revealing additional content that is initially hidden due to space constraints. Use a "View/Read/Show more" button instead [6].
Ajouter un lien vers le composant Button?

2024-03-20 13:56 UTC, meriouma commented on packages/storybook/.storybook/main.ts
> +    defaultName: 'All Stories'
```suggestion
        defaultName: 'All Stories'
```

2024-03-20 13:56 UTC, meriouma commented on packages/storybook/stories/accordion.mdx
> +<br />
Mets pas de `<br />`. On ajustera le spacing avec le CSS. Tu peux enlever les autres aussi.

2024-03-20 13:56 UTC, meriouma commented on packages/storybook/stories/accordion.mdx
> +<br />
Mets juste une ligne vide.
```suggestion

```

2024-03-20 13:56 UTC, meriouma commented on packages/storybook/stories/accordion.mdx
> +- When the information contained in each section is independent, and users are unlikely to need simultaneous access to several sections [6].
C'est voulu que celui-ci ne soit pas en bold?

2024-03-20 13:56 UTC, meriouma commented on packages/storybook/stories/accordion.mdx
> +- To display more information, revealing additional content that is initially hidden due to space constraints. Use a "View/Read/Show more" button instead [6].
Et ici?

2024-03-20 15:52 UTC, LarryMatte commented on packages/storybook/stories/accordion.mdx
> +## Table of Contents
Remplacer par une liste, ca va être mieux sémantiquement
https://www.markdownguide.org/basic-syntax/#unordered-lists

2024-03-21 12:38 UTC, Genmoree commented on packages/storybook/stories/accordion.mdx
> +- When the information contained in each section is independent, and users are unlikely to need simultaneous access to several sections [6].
J'ai enlevé tous les bold finalement.

2024-03-21 12:56 UTC, Genmoree commented on packages/storybook/stories/accordion.mdx
> +- **When the content has a deep hierarchy with multiple sublevels:** it may be too complex to be displayed in a flat hierarchy format like accordions. Instead, consider alternatives such as tabs [6].
J'ai essayé plusieurs fois de le faire en écrivant ça [Tabs](#tabs.stories) ou ça [Tabs](#tabs.stories.tsx) mais le lien vers la page ne semble pas se faire.

2024-03-25 15:32 UTC, LarryMatte requested changes

2024-03-25 15:32 UTC, LarryMatte commented on packages/storybook/stories/accordion.mdx
> +   3. [Variants](#Variants)
les liens ne fonctionnes pas (variants et properties)

2024-04-11 12:42 UTC, pylafleur commented on packages/storybook/stories/accordion.stories.tsx
> +            control: { type: null },
En mettant `type: null`, la prop demeure listée dans le tableau de l'onglet Controls mais sa valeur n'est pas modifiable.

L'autre option, c'est de masquer la ligne complètement. Par contre, lorsqu'on les masque toutes, Storybook pense que les contrôles ne sont pas configurés et offre un lien vers la doc...

2024-04-15 14:05 UTC, LarryMatte approved these changes

2024-04-17 17:06 UTC, merged