docs(storybook): update avatar
kronostechnologies/design-elements pull request #773
Opened 2024-03-19 20:52 UTC by Genmoree

2024-03-20 15:51 UTC, LarryMatte requested changes
quelques commentaires ici et là. Enlever également les <br/> comme l'a mentionné max dans une autre PR

2024-03-20 15:51 UTC, LarryMatte commented on packages/storybook/stories/avatar.mdx
> +## Table of Contents
Remplacer par une liste. Ce serait probablement mieux sémantiquement

2024-03-20 15:51 UTC, LarryMatte commented on packages/storybook/stories/avatar.mdx
> +- Do not use to replace buttons.
lien vers la doc des boutons

2024-03-20 15:51 UTC, LarryMatte commented on packages/storybook/stories/avatar.mdx
> +## Variants
Est-ce que les variantes de size devraient également se retrouver ici?

2024-03-20 15:51 UTC, LarryMatte commented on packages/storybook/stories/avatar.mdx
> +## Variants
Est-ce que la variantes avec "a specific color" devrait se retrouver ici?

2024-03-21 14:08 UTC, Genmoree commented on packages/storybook/stories/avatar.mdx
> +## Variants
On doit faire un ménage dans ces variants, il y a beaucoup de stories pour la quantité de variants. Je vais laisser ça comme ça et y revenir après la première vague de migration des docs pour faire un ménage.

2024-03-25 15:31 UTC, LarryMatte submitted a review, later dismissed

2024-04-17 17:41 UTC, LarryMatte requested changes

2024-04-17 17:41 UTC, LarryMatte commented on packages/storybook/stories/avatar.mdx
> +Avatar is an atom that represents a user or an entity, that has the goal of **creating connections and humanizing online communities** [2][1].
J'enlèverais "atom" comme c'est pas mal le seul des composants qui utilise le terme.

2024-04-18 14:28 UTC, LarryMatte approved these changes

2024-04-18 14:28 UTC, merged