docs(storybook): update button
kronostechnologies/design-elements pull request #774
Opened 2024-03-20 12:40 UTC by Genmoree

2024-03-20 15:44 UTC, LarryMatte requested changes
quelques commentaires. Enlever également les <br/> comme max l'a mentionné dans une autre PR

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +## Table of Contents
utiliser une liste ici. Sémantiquement, ce serait mieux.
https://www.markdownguide.org/basic-syntax/#unordered-lists

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +- Do not use buttons component as navigational elements. Instead, use a Link when the desired action is to take the user to somewhere else or a new page [1].
ajouter un lien vers la doc des liens

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +### Primary
Est-ce que tu pourrais ajouter le bouton primaire ici

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +### Secondary
Est-ce que tu pourrais ajouter le bouton secondaire ici

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +### Tertiary
Est-ce que tu pourrais ajouter le bouton tertiaire ici

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +### Destructive
Est-ce que tu pourrais ajouter le bouton destructif ici

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +### Destructive secondary
Est-ce que tu pourrais ajouter le bouton destructif secondaire ici

2024-03-20 15:44 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +### Icon only
Le composant Icon button est dans sa propre section et il n'est pas une sous-section du composant `Button`. Est-ce que tu devrais bouger cette doc dans la page du composant `Icon button`.

2024-03-21 14:33 UTC, Genmoree commented on packages/storybook/stories/button.mdx
> +- Do not use buttons component as navigational elements. Instead, use a Link when the desired action is to take the user to somewhere else or a new page [1].
Je n'ai toujours pas trouvé comment.

2024-03-21 14:34 UTC, Genmoree commented on packages/storybook/stories/button.mdx
> +### Primary
Ce n'est pas possible parce que les boutons sont regroupés dans une seule story.

2024-03-21 14:34 UTC, Genmoree commented on packages/storybook/stories/button.mdx
> +### Icon only
On devrait plutôt bouger le icon button dans cette doc-ci.

2024-04-15 14:26 UTC, LarryMatte requested changes

2024-04-15 14:26 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +Coming soon!
La variante est dispo dans le snapshot donc tu pourrais probablement l'ajouter ici.

2024-04-15 17:28 UTC, LarryMatte approved these changes

2024-04-17 18:02 UTC, LarryMatte requested changes

2024-04-17 18:02 UTC, LarryMatte commented on packages/storybook/stories/button.mdx
> +- Use an icon to the right of the label to indicate a state *e.g.: loading state* or to indicate the role of the button *e.g.: Menu button*
J'enlèverais l'exemple "Menu button" et je trouverai un terme plus générique si jamais le "Menu button" change de nom ou qu'il est deprecated. e.g., open a popup/dropdown ou whatev

2024-04-18 14:26 UTC, LarryMatte approved these changes

2024-04-18 14:26 UTC, merged