feat(table-header,storybook): add header grouping in data-table
kronostechnologies/design-elements pull request #784
Opened 2024-03-25 19:39 UTC by mmorin-equisoft

Ref:

2024-03-25 20:25 UTC, mmorin-equisoft commented on packages/react/src/components/table/table-header.tsx
> +    const colSpan = isHeaderGroup(header) ? header.colSpan : undefined;
C'est pour éviter de render des éléments avec des `colSpan` de 1 partout

2024-03-26 15:11 UTC, mmorin-equisoft commented on packages/react/src/components/table/table-header.tsx
> +    const colSpan = isHeaderGroup(header) ? header.colSpan : undefined;
Effectivement, c'est mieux comme ça.

2024-03-26 15:20 UTC, savutsang commented
C'est un cas particulier ici car on a pas de Figma ni de Notion par rapport a ca. J'imagine on veut demontrer que c'est un truc fesable mais ce n'est pas encore officiellement supporte/documente. Pour moi c'est good.

2024-03-26 15:20 UTC, savutsang submitted a review, later dismissed

2024-04-01 19:15 UTC, alexbrillant submitted a review, later dismissed

2024-04-15 18:56 UTC, maboilard requested changes
J'ajouterais un séparateur entre les groupes de premier niveau (voir exemple [ici](https://www.notion.so/equisoft/Data-Table-42276c6414bb4d03981b93d4035f1c6a?pvs=4#cbabef5c34e2452c83e531be6598dd17)) afin de bien délimiter l'information lorsqu'il y a des éléments alignés à droite.

J'ai aussi remarqué que la hauter du column header n'est pas la même que les rows mais ça semble être le cas un peu partout. Je vais donc créer un autre ticket pour régler ce bug.

À part ça, c'est all good pour moi! :)

2024-04-17 12:44 UTC, maboilard submitted a review, later dismissed
C'est good pour moi, bon boulot!

2024-04-25 01:40 UTC, meriouma reviewed
Petits détails, sinon LGTM

2024-04-25 01:40 UTC, meriouma commented on packages/react/src/components/table/table-header.tsx
>          border-bottom: 1px solid ${({ theme }) => theme.greys.grey};
Henri s'en occupe dans #851

2024-04-25 01:40 UTC, meriouma commented on packages/react/src/components/table/table-header.tsx
> +    }[currentSort] as SortState;
Ce serait peut-être plus direct comme association
```suggestion
    switch (currentSort) {
        case 'asc':
            return 'ascending';
        case 'desc':
            return 'descending';
        default:
            return 'none';
    }
```

2024-04-25 01:40 UTC, meriouma commented on packages/react/src/components/table/utils/table-utils.ts
> +export function isColumnIsLastInAGroup<TData, TValue>(column: Column <TData, TValue>): boolean {
```suggestion
export function isLastColumnInAGroup<TData, TValue>(column: Column <TData, TValue>): boolean {
```

2024-04-25 01:40 UTC, meriouma commented on packages/react/src/components/table/table-row.tsx
> +        border-right: 1px solid ${({ theme }) => theme.greys.grey};
Mais ça risque de te prendre le même token pour ici

2024-04-25 12:30 UTC, mmorin-equisoft commented on packages/react/src/components/table/table-row.tsx
> +        border-right: 1px solid ${({ theme }) => theme.greys.grey};
Je vais l'aviser pour qu'il récupère les changements une fois la PR merged.

2024-04-25 14:41 UTC, meriouma approved these changes
Je te laisse voir avec Henri l'ordre dans lequel vous voulez merger vos affaires et pour vous assurer que le token est changé pour un nouveau.

2024-04-25 14:53 UTC, merged