docs(storybook): update tag
kronostechnologies/design-elements pull request #789
Opened 2024-03-26 13:43 UTC by Genmoree

2024-03-26 18:00 UTC, LarryMatte requested changes

2024-03-26 18:00 UTC, LarryMatte commented on packages/storybook/stories/tag.mdx
> +- Tapping on a clickable tag activates it and appends a leading checkmark icon to the starting edge of the tag label [6].
"_and appends a leading checkmark icon to the starting edge of the tag label_" Ce n'est pas encore fait dans le code donc à remettre à plus tard pour la doc.

2024-05-02 20:23 UTC, hebernardEquisoft commented
Je crois qu'il va falloir mettre la doc à jour pour les `ToggleTag` @Genmoree @LarryMatte

2024-05-13 18:16 UTC, LarryMatte approved these changes

2024-05-13 18:17 UTC, merged