docs(storybook): update toast
kronostechnologies/design-elements pull request #792
Opened 2024-03-26 17:44 UTC by Genmoree

2024-04-17 20:06 UTC, LarryMatte requested changes

2024-04-17 20:30 UTC, LarryMatte requested changes

2024-04-17 20:30 UTC, LarryMatte commented on packages/storybook/stories/toast.mdx
> +### Discovery
manque de texte ici

2024-04-18 15:13 UTC, LarryMatte commented
@pylafleur si on regarde les controls, il n'y a rien. C'est probablement causé par le fait que le toast est affiché seulement après avoir triggered le bouton. Est-ce qu'on pourrait avoir seulement les toasts déjà affichés sans avoir à triggerer le btn?

2024-04-26 15:26 UTC, LarryMatte commented on packages/storybook/stories/toast.mdx
> +## Variants
oui on devrait

2024-05-21 15:10 UTC, LarryMatte commented
@pylafleur est-ce que tu pourrais regarder cette PR, il y a plein de tests qui ne sont pas complétés

2024-06-03 18:54 UTC, pylafleur commented
> @pylafleur si on regarde les controls, il n'y a rien. C'est probablement causé par le fait que le toast est affiché seulement après avoir triggered le bouton. Est-ce qu'on pourrait avoir seulement les toasts déjà affichés sans avoir à triggerer le btn?

@LarryMatte C'est pas possible d'avoir des contrôles ici parce que ce le component du toast n'est pas réellement affiché dans l'encadré de la story, il est plutôt généré dans un contexte global. Pour cette raison, storybook n'a pas accès à passer les valeurs des contrôles aux props du toast.

2024-06-04 14:34 UTC, LarryMatte approved these changes

2024-06-04 14:34 UTC, merged