docs(storybook): update date picker
kronostechnologies/design-elements pull request #827
Opened 2024-04-17 12:35 UTC by Genmoree

2024-04-30 14:48 UTC, LarryMatte requested changes
Enlever la ligne 13 `const currentDate = new Date();` dans le fichier `date-picker.stories.tsx`. Elle ne semble pas utilisée.

2024-04-30 14:52 UTC, LarryMatte requested changes
Enlever la ligne 13 `const currentDate = new Date();` dans le fichier `date-picker.stories.tsx`. Elle ne semble pas utilisée.

2024-04-30 14:52 UTC, LarryMatte commented on packages/storybook/stories/date-picker.mdx
> +- Use only when you have a validation after.
Est-ce que c'est pertinent? s'il n'y a pas de validation après, on fait quoi?

2024-04-30 14:52 UTC, LarryMatte commented on packages/storybook/stories/date-picker.mdx
> +- Do not use when there is immediate effect on the content.
Tu entends quoi par "immediate effect"? Est-ce que je pourrais sélectionner une date et que ca change le contenu d'un calendrier qui affiche des activités par exemple?

2024-04-30 19:33 UTC, LarryMatte requested changes

2024-04-30 19:33 UTC, LarryMatte commented on packages/storybook/stories/date-picker.mdx
> +- Do not use for anything else than a date.
Quelle autre utilisation un utilisateur pourrait en faire étant donné que cela n'affiche que des dates ? Ici, il est tout de même évident que le calendrier sert à sélectionner des dates. Je pourrais comprendre la pertinence de la phrase s'il y avait des situations ambiguës comme celles entre les radio buttons et le dropdown list, mais ici, ce n'est pas vraiment le cas, je crois.

2024-04-30 19:49 UTC, Genmoree commented on packages/storybook/stories/date-picker.mdx
> +- Do not use for anything else than a date.
C'est un peu un placeholder. C'est évident effectivement mais sinon je n'ai rien à écrire dans ces sections.

2024-05-17 15:39 UTC, LarryMatte reviewed
@Genmoree enlever la ligne `const currentDate = new Date();` de packages/storybook/stories/date-picker.stories.tsx. Ça semble petter depuis que tu as fait le menage dans la story.

2024-05-21 18:25 UTC, LarryMatte commented
> @Genmoree enlever la ligne `const currentDate = new Date();` de packages/storybook/stories/date-picker.stories.tsx. Ça semble petter depuis que tu as fait le menage dans la story.

J'ai fixé le problème

2024-06-04 14:51 UTC, pylafleur commented
Le tableau des props n'apparaît plus depuis la migration vers Storybook 8. Il serait possible de réécrire toutes les définitions à la main mais c'est pas mal de job (incluant garder ça in-sync avec react-date-picker).

Pour l'instant, je suggère d'attendre un peu au cas où une update règlerait ça...

2024-06-04 14:58 UTC, LarryMatte commented
> Le tableau des props n'apparaît plus depuis la migration vers Storybook 8. Il serait possible de réécrire toutes les définitions à la main mais c'est pas mal de job (incluant garder ça in-sync avec react-date-picker).
> 
> Pour l'instant, je suggère d'attendre un peu au cas où une update règlerait ça...

Ça me va!

2024-06-04 15:00 UTC, LarryMatte approved these changes

2024-06-04 15:00 UTC, merged

2024-06-04 19:42 UTC, pylafleur commented
Finalement, le problème a été réglé de notre côté: #896