docs(storybook): update bento menu
kronostechnologies/design-elements pull request #831
Opened 2024-04-17 14:06 UTC by Genmoree

J'ai également déplacé ce composant dans la section « core » puisqu'il n'existe pas ailleurs que dans le global header.

2024-04-30 15:05 UTC, LarryMatte requested changes

2024-04-30 15:05 UTC, LarryMatte commented on packages/storybook/stories/bento-menu.mdx
> +Do not use when you have limited options: using a bento menu may be unnecessary and could introduce unnecessary complexity [3].
Ce serait quoi un nombre de "_limited options_"?

2024-04-30 15:29 UTC, Genmoree commented on packages/storybook/stories/bento-menu.mdx
> +Do not use when you have limited options: using a bento menu may be unnecessary and could introduce unnecessary complexity [3].
Je n'ai jamais trouvé l'info. Mais normalement notre use case est semi bon. On devrait avoir un bento qui correspond plus à celui de google disons...

2024-04-30 18:10 UTC, LarryMatte approved these changes
LGTM je vais attendre les changements de P-Y avant de merger

2024-05-03 13:52 UTC, hebernardEquisoft commented
J'ai déplacé la composante dans la section Core comme @Genmoree l'a mentionné!

2024-05-03 13:55 UTC, LarryMatte commented
> J'ai déplacé la composante dans la section Core comme @Genmoree l'a mentionné!

Voir ce commentaire: https://github.com/kronostechnologies/design-elements/pull/831#discussion_r1572893148

2024-05-03 14:12 UTC, hebernardEquisoft commented
My bad j'avais pas vu! 

reverting back...

2024-05-13 19:10 UTC, LarryMatte approved these changes

2024-05-13 19:10 UTC, merged