docs(storybook): update data table
kronostechnologies/design-elements pull request #841
Opened 2024-04-18 17:48 UTC by Genmoree

2024-04-19 18:08 UTC, LarryMatte requested changes

2024-04-19 18:08 UTC, LarryMatte commented on packages/storybook/stories/data-table.mdx
> +The data table is a structural component used to efficiently display and organize data [1].
comme nous avons changé la façon de regrouper les composants, j'enlèverais "is a structural component"

2024-04-19 19:57 UTC, LarryMatte approved these changes

2024-06-18 14:30 UTC, savutsang commented on packages/storybook/stories/data-table.mdx
> +import { Table } from '@equisoft/design-elements-react';
Il y a un des story "Optimization" qui contient du text, il faudrait le mettre dans MDX sinon on ne le voit plus.

![image](https://github.com/kronostechnologies/design-elements/assets/3039571/10e314b3-27ff-422c-b5e5-f700724d4fd9)

2024-08-16 17:34 UTC, WilliamsTardif commented on packages/storybook/stories/data-table.stories.tsx
>              <Button type="button" buttonType='secondary' onClick={() => setAllowEditing(!allowEditing)}>
Le visuel CSS du onClick du bouton est un peu câché par le tableau. Peut-être le décaler un peu vers le haut rendrais ça plus clean ?
<img width="188" alt="Capture d’écran, le 2024-08-16 à 13 26 41" src="https://github.com/user-attachments/assets/60192245-a4c7-4159-8a95-39c697152c10">

2024-08-16 17:34 UTC, WilliamsTardif commented on packages/storybook/stories/data-table.stories.tsx
>  export const Optimization: Story = () => {
Pourquoi on appel ça `Optimization` alors qu'il serait plus logique selon moi d'appeler ça `Editable`, `Editing`, etc. 🤔 
Qu'est-ce que vous en pensez ?

2024-09-09 20:51 UTC, pylafleur commented on packages/storybook/stories/data-table.stories.tsx
>              <Button type="button" buttonType='secondary' onClick={() => setAllowEditing(!allowEditing)}>
C'est corrigé!

2024-09-09 20:53 UTC, pylafleur commented on packages/storybook/stories/data-table.stories.tsx
>  export const Optimization: Story = () => {
L'objectif semblait de mettre en évidence l'optimisation expliquée dans le texte. Faudrait peut-être revoir le nommage et les stories elles-mêmes dans un 2e temps.

2024-09-10 13:35 UTC, LarryMatte approved these changes

2024-09-10 13:35 UTC, merged