docs(storybook): update error summary
kronostechnologies/design-elements pull request #845
Opened 2024-04-18 19:12 UTC by Genmoree

2024-04-19 17:33 UTC, LarryMatte requested changes

2024-04-19 17:33 UTC, LarryMatte commented on packages/storybook/stories/error-summary.mdx
> +- Use the default badge to display numbers within a container and/or to indicate a quantifiable status change [7].
texte de la badge??

2024-04-19 18:06 UTC, Genmoree commented on packages/storybook/stories/error-summary.mdx
> +- Use the default badge to display numbers within a container and/or to indicate a quantifiable status change [7].
Étrange... ce n'est pas ce que je vois

![Screenshot 2024-04-19 at 2 06 20 PM](https://github.com/kronostechnologies/design-elements/assets/145023291/a5e7d492-8bd7-4efc-956d-accbb7ef9bfd)

2024-04-19 20:01 UTC, LarryMatte submitted a review, later dismissed

2024-05-13 15:34 UTC, LarryMatte approved these changes

2024-05-13 15:34 UTC, merged