docs(storybook): update password creation input
kronostechnologies/design-elements pull request #846
Opened 2024-04-18 19:19 UTC by Genmoree

2024-04-30 15:49 UTC, LarryMatte requested changes
Pourquoi avoir enlever l'exemple de custom validation? Si vous voulez vraiment l'enlever, vous allez devoir enlever les lignes 5, 6, 7, 10 du fichier `password-creation-input.stories.tsx`

2024-04-30 15:49 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +The password creation input is a pattern that allows the users to create a password with instant feedback indicating if the typed password is secure enough.
Hum oui nous pouvons le voir comme un pattern par contre, ici c'est un composant à par entière, p-e à revoir la formulation.

2024-04-30 15:49 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +- Use to display all the conditions necessary to create or edit a password.
Est-ce que nous pouvons vraiment éditer un mot de passe? On peut changer de mot de passe mais de là à l'éditer je ne suis pas certain. Dans quel contexte ce serait possible?

2024-04-30 15:49 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +Do not use for anything else than a password creation or edition.
Voir commentaire dans la section "_When to use_" à propos de l'édition.

2024-04-30 18:56 UTC, LarryMatte requested changes

2024-04-30 18:56 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +- Use to display all the conditions necessary to create or edit a password.
oui exact mais est-ce que éditer et changer est la même chose?
Selon GPT: 
>"Changing a password" typically implies replacing the current password with a new one, often prompted by security measures or personal preference. On the other hand, "editing a password" could refer to making adjustments or modifications to an existing password, such as altering its complexity, length, or other attributes without necessarily replacing it entirely. 

Donc si nous prenons ça en considération, est-ce que nous pourrions permettre à un utilisateur d'éditer son mot de passe? Dans le sens, son mot de passe est déjà créé mais il veut l'éditer pour XYZ raison. Rendu là c'est plus un changement qu'une édition. Tu en penses quoi?

2024-04-30 18:56 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +- Use to display all the conditions necessary to create or edit a password.
Je crois que je changerais simplement le mot "_edit_" par "_change_" dans la doc.

2024-04-30 18:56 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +- Do not use for anything else than a password creation or edition.
Voir commentaire dans la section "_When to use_" à propos de "_edit_" vs "_change_".

2024-05-01 14:29 UTC, LarryMatte approved these changes
LGTM, un seul commentaire à régler mais rien de majeur.
je vais attendre les modifs pour la feature de Controls avant de merger

2024-05-01 14:29 UTC, LarryMatte commented on packages/storybook/stories/password-creation-input.mdx
> +- Use to help users create a new password
Il manque un "." à la fin de la phrase.

2024-05-13 17:56 UTC, mmorin-equisoft commented on packages/storybook/stories/password-creation-input.stories.tsx
> +    argTypes: {
Le props `validations` apparait comme un `object`. C'est pas super selon moi. 
J'ai hésité à le désactiver.

2024-05-13 20:08 UTC, LarryMatte commented
@Genmoree il reste https://github.com/kronostechnologies/design-elements/pull/846#discussion_r1586357927 à fixer et, je ne sais pas pourquoi, mais il y a deux boutons 'Toggle' dans l'exemple de code, le premier ne semble pas faire grand chose.

2024-05-21 13:25 UTC, merged