docs(storybook): update progress indicator
kronostechnologies/design-elements pull request #848
Opened 2024-04-18 19:42 UTC by Genmoree

2024-04-30 17:15 UTC, LarryMatte requested changes

2024-05-21 15:41 UTC, LarryMatte commented
@Genmoree refaire une passe pour les commentaires

2024-06-06 18:51 UTC, pylafleur approved these changes

2024-06-06 18:54 UTC, LarryMatte approved these changes

2024-06-06 18:54 UTC, merged