feat(dropdown-list, storybook): DS-1126: add icon in front of the options of dropdown-list
kronostechnologies/design-elements pull request #873
Opened 2024-05-09 20:29 UTC by WilliamsTardif

JIRA: https://equisoft.atlassian.net/browse/DS-1126

2024-05-09 21:20 UTC, savutsang commented on packages/react/src/components/dropdown-list/dropdown-list.tsx
> +     * Set icon
On met juste une description si c'est de l'information pertinente, sinon met rien.

2024-05-09 21:40 UTC, savutsang commented on packages/react/src/components/dropdown-list/dropdown-list.tsx
> +                    <TextIcon name={iconName} size={isMobile ? '24' : '16'} data-testid="textboxIcon" />
Il n'y a pas de regle ecrite, mais le kebab-case gagne en popularite pour les testid. De plus que TagWrapper plus bas utilise le kebab-case.

```suggestion
                    <TextIcon name={iconName} size={isMobile ? '24' : '16'} data-testid="textbox-icon" />
```

2024-05-09 22:00 UTC, savutsang commented on packages/react/src/components/dropdown-list/dropdown-list.test.tsx
> +            expect(iconComponent).toBeTruthy();
Pas la bonne condition.

```suggestion
            expect(iconComponent.exists()).toBe(false);
```

2024-05-10 12:53 UTC, LarryMatte requested changes
Il manque le `aria-hidden="true"` sur l'icône.

Si je superpose ce que tu as et ce qui est dans Figma, il y a un petit décalage. Ton icône est trop vers la droite comparé au visuel. Tu peux utiliser cette extension chrome: https://chromewebstore.google.com/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi
<img width="181" alt="Screenshot 2024-05-10 at 8 50 19 AM" src="https://github.com/kronostechnologies/design-elements/assets/3722754/927f4634-5b0f-4205-b266-c9e3e2c9a12c">

Tu vas pouvoir faire une capture d'écran (zoom à 100%) de ce qui est dans Figma et de l'importer par dessus ce sur quoi tu travailles dans chrome. Ça va te permettre d'être le plus 'pixel perfect' possible. _Pokes_ moi si tu veux que je te montre comment tout ca fonctionne.

2024-05-13 14:14 UTC, savutsang commented on packages/react/src/components/dropdown-list/dropdown-list.tsx
> +                    <TextIcon
La couleur de l'icon n'est pas la bonne, c'est un gris plus pale dans Figma.

2024-05-13 15:10 UTC, savutsang commented
Typo dans le title du PR `iinside`

Aussi IMHO, on ne devrait pas mettre "storybook" dans le scope lorsque c'est un feat ou fix. Ce n'est pas utile au point de le mentionner, ca fait juste polluer le git history. Je prefere mettre de l'emphase sur le feature principal `feat(dropdown-list)`

2024-05-13 20:55 UTC, savutsang commented on packages/react/src/components/dropdown-list/dropdown-list.tsx
> +const TextIcon = styled(Icon).attrs({ color: '#60666E' })`
Dernier points, faudrait utiliser le theming. Je pense il faudrait ajouter un token dans [dropdown-list-tokens.ts](https://github.com/kronostechnologies/design-elements/blob/master/packages/react/src/themes/tokens/component/dropdown-list-tokens.ts), genre 
```
'dropdown-list-input-icon-color': 'color-neutral-65'
``` 
@maboilard?

Y a 2 facons d'utiliser ca, la premiere est plus clean avec un prop bien controlle. Mais honnetement, l'un ou l'autre c'est pas un truc qui me gosse.

- https://github.com/kronostechnologies/design-elements/blob/66a5de7b02ceb292757534fbe35d6bbfeb2ef179/packages/react/src/components/table/sort-button-icon.tsx#L21
- https://github.com/kronostechnologies/design-elements/blob/66a5de7b02ceb292757534fbe35d6bbfeb2ef179/packages/react/src/components/tag/toggle-tag.tsx#L104

2024-05-17 13:54 UTC, maboilard commented on packages/react/src/components/dropdown-list/dropdown-list.tsx
> +const TextIcon = styled(Icon).attrs({ color: '#60666E' })`
En fait, ça donnerait ceci:
`'dropdown-list-input-icon-color': 'color-content-subtle'`
@hebernardEquisoft Est-ce que c'est quelque chose qui devrait être fait ici ou dans ta PR?

2024-05-17 13:58 UTC, hebernardEquisoft commented on packages/react/src/components/dropdown-list/dropdown-list.tsx
> +const TextIcon = styled(Icon).attrs({ color: '#60666E' })`
Ça peut se faire ici sans problème! les alias-tokens existent maintenant sur master! 💯

2024-05-21 19:17 UTC, LarryMatte reviewed
Bien parfait pour moi en ce qui me concerne.
Je laisse Savut, Max et PY être les juges pour le restant.

2024-05-21 22:35 UTC, savutsang commented
Il reste juste a changer la couleur pour 'color-content-subtle' (https://github.com/kronostechnologies/design-elements/pull/873#discussion_r1605050988) pis on est bon, le reste est LGTM.

2024-05-27 18:03 UTC, maboilard approved these changes
J'ai fait le tour et ça semble all good pour moi!

2024-05-27 19:20 UTC, savutsang approved these changes

2024-05-27 19:21 UTC, LarryMatte approved these changes

2024-05-27 19:32 UTC, alexbrillant approved these changes
🍆

2024-05-27 20:44 UTC, merged