feat(table): adds single row selection mode for data table
kronostechnologies/design-elements pull request #888
Opened 2024-05-28 16:15 UTC by ogermain-kronos

https://equisoft.atlassian.net/browse/DS-1101

![image](https://github.com/kronostechnologies/design-elements/assets/6412423/eb3feb14-e1af-41fb-95f6-715ad99c07b0)
![image](https://github.com/kronostechnologies/design-elements/assets/6412423/dbd38fe6-5716-4f37-b760-fbe5255462ae)

2024-05-29 18:57 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +const RadioButton = styled.input`
Ca n'a pas le design du Radio Button
Actuel
![image](https://github.com/kronostechnologies/design-elements/assets/3039571/5f74553c-68da-4158-a697-d2a47dd47408)

Expected
![image](https://github.com/kronostechnologies/design-elements/assets/3039571/1de0984e-cad9-4d3c-9359-e30ab60ad424)

On a deja ca dans Radio-Button-Group, il faudrait comme extraire juste le input pis faire un component Radio Button seul.

2024-05-29 19:05 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
J'ouvre la discussion, mais le radio button a un comportement de toggle presentement, si tu le re-click, ca va le deselectionner.

Je ne sais pas si c'est voulu de meme ou acceptable. Dans mon experience je n'ai jamais vu un radio qui peut se deselect. En meme temps, on a pas d'autre moyen d'enlever une selection non plus. C'est quoi vos opinions la dessus?

@LarryMatte @Genmoree

2024-05-29 19:13 UTC, ogermain-kronos commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
Je l'ai fait comme ça parce que j'étais pas certain qu'on devait locker le user dans un choix ou non. Je suis ouvert aux propositions.

2024-05-29 19:14 UTC, ogermain-kronos commented on packages/react/src/components/table/table.tsx
> +const RadioButton = styled.input`
On s'inspire du King, I see
![image](https://github.com/kronostechnologies/design-elements/assets/6412423/00dfc497-b2fa-4790-af23-677d51642449)

2024-05-29 19:44 UTC, pylafleur commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
Pas une réponse concrète mais un peu de recherche.

Les exemples que j'ai trouvés pour un single select avec bouton radio n'offraient pas de moyen de désélectionner:
https://www.lightningdesignsystem.com/components/data-tables/#Single-row-selection
https://www.naiveui.com/en-US/os-theme/components/data-table#select-single.vue

Celle-là le permet mais elle n'a pas de bouton radio. Ça retire l'ambiguité mais ça communique moins bien la possibilité d'interaction selon moi:
https://datatables.net/examples/api/select_single_row.html

2024-05-29 19:51 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +    selectionMode?: SelectionMode;
C'est un BREAKING CHANGE, il faut ajouter un `!` et documenter le breaking change.

https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer

2024-05-29 19:59 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
Yeah le datatable c'est pas trop clair que tu le selectionne pour faire un action. Ca peut confondre avec un action de juste highlighter un row pour faciliter la lecture.

2024-05-30 00:12 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +    selectionMode?: SelectionMode;
On a un `expandableRows?: 'single' | 'multiple';`, pourquoi on ne garderait pas la meme nomenclature.

```suggestion
    selectableRows?: 'single' | 'multiple';
```

2024-05-30 14:02 UTC, ogermain-kronos commented on packages/react/src/components/table/table.tsx
> +    selectionMode?: SelectionMode;
C'est débatable. Honnnêtement je trouve que `selectionMode` est pas mal plus clair sur la fonction de la prop que `selectableRows` imho.

2024-05-30 19:24 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +    selectionMode?: SelectionMode;
Yeah, pour moi c'est pas tant le nom mais plus le fait qu'on garde une certaine similitude entre les noms. Ca pourrait etre expandableRows qui se renomme a `expandMode` aussi.

2024-05-30 21:15 UTC, WilliamsTardif reviewed
J'ai testé la nouvelle fonctionnalité et dite moi si je sors du scope de la tâche.
Pas que j'ai le parkinson, mais j'ai trouvé ça un peu désagréable de devoir être précis pour clicker sur le bouton radio. Est-ce qui serait pas trop compliquer de toggle quand on click aussi la row ? 🤔 
Sa peut-être déjà été discuté, mais je pose quand même la question au cas où. 🤷‍♂️

2024-05-30 21:17 UTC, WilliamsTardif approved these changes

2024-05-30 21:17 UTC, WilliamsTardif commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
J'ai testé la nouvelle fonctionnalité et dite moi si je sors du scope de la tâche.
Pas que j'ai le parkinson, mais j'ai trouvé ça un peu désagréable de devoir être précis pour clicker sur le bouton radio. Est-ce qui serait pas trop compliquer de toggle quand on click aussi la row ? 🤔 
Sa peut-être déjà été discuté, mais je pose quand même la question au cas où. 🤷‍♂️

2024-05-31 13:15 UTC, LarryMatte commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
J'aime vraiment la réflexion. 
Par contre, disons que la row est clickable au complet:
- s'il y a une cell avec un lien `<a>` à l'intérieur, ça peut être tannant lorsque l'utilisateur va clicker sur le lien, ca va trigger le radio button, même chose s'il y a des `<button>`. 
- si l'utilisateur veut sélectionner le texte d'une cell pour faire un copier/coller, il va devoir clicker dans la cell pour le sélectionner et ca va trigger le radio button.
Je sais que nous pourrions contourner tout ça d'une manière xyz mais je préfère garder ca le plus simple possible. Ce que nous pourrions faire par contre serait d'avoir la cell clickable au lieu de toute la row.

2024-05-31 14:04 UTC, savutsang commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
+1 pour le cell cliquable.

2024-06-03 14:20 UTC, LarryMatte requested changes

2024-06-03 14:20 UTC, LarryMatte commented on packages/react/src/components/table/table.tsx
> +                    <RadioButton
La radio button devrait avoir un `<label>` d'associé. S'il n'y a pas de `<label>` les technologies d'assistances (lecteur d'écran) vont seulement annoncer que c'est un radio button et rien d'autre. Le `<label>` sert à identifier de quel radio button il s'agit. _e.g._, si le `<label>` est '_patate_' le lecteur d'écran va annoncer: '_patate, radio button_'
Il y a deux options possibles:

1. **aria-label**
ajouter un `aria-label="label du radio button"` à l'input.
Tu aurais donc: 
`<input data-testid="..." type="radio" class="..." aria-label="patate">`.

2. **hidden text**
ajouter une classe qui vient cacher visuellement le `<label>`.
`<input id="idInput" data-testid="..." type="radio" class="..."><label for="idInput" class="visually-hidden">patate</label>`

Comme mentionné dans un autre commentaire, il faudrait utiliser le composant de radio button du DS. Ça va p-e demander du boulot dans le composant radio-button par contre.
Je vais regarder le travaille qu'il y a à faire sur le composant et si c'est trop de boulot, je vais créer une carte pour y faire les modifications et on reviendra sur ta PR quand les modifications pour le radio button seront fait.

2024-06-07 18:28 UTC, meriouma commented on packages/react/src/components/table/table.tsx
> +    selectionMode?: SelectionMode;
Par contre je me demande si on ne devrait pas garder `row` ou `rows` dans les noms de props, vu que ça affecte les rows et non la table. `row(s)Selection` et `row(s)Expansion`?

2024-06-10 16:03 UTC, pylafleur commented on packages/react/src/components/table/table.tsx
> +                            table.toggleAllRowsSelected(false);
Comme on s'enligne pour créer notre propre component pour le radio button, il devrait inclure un élément `label` comme la checkbox. À ce moment-là, il serait possible d'ajouter un padding au label (même sans texte) pour grossir le _hit area_. Ça éviterait de faire une passe-passe avec le clic sur la cell.

Je ne pense pas que le `label` soit un problème pour l'a11y parce que les attribut `aria-labelledby` ont la priorité sur les éléments `<label>` lorsque les deux sont présents.

2024-08-05 13:41 UTC, closed without merging