feat(slider): add new slider component
kronostechnologies/design-elements pull request #893
Opened 2024-06-03 18:43 UTC by savutsang

DS-281

**Description**

- We use MUI as the base of the Slider.
- The input(s) are not part of the component.
- We had to use "::before" for the thumb because if we change the dimension or use scale, it would impact the tooltip also.

2024-06-04 12:59 UTC, savutsang commented on packages/react/src/themes/tokens/component/slider-tokens.ts
> +    'slider-rail-mark-disabled-background-color': 'color-neutral-30', // color-background-indicator-disabled
Beacucioup d'alias sont creer et renomme dans le PR de @hebernardEquisoft. Il faudra les re-ajuster.

2024-06-05 14:25 UTC, LarryMatte requested changes
- Il manquerait le tooltip lorsque l'utilisateur interagit avec le composant en utilisant les touches (flèches) du clavier. Présentement le tooltip est seulement affiché lorsqu'un user utilise la souris. [MUI semble avoir la feature](https://mui.com/material-ui/react-slider/#discrete-sliders).

- Présentement, il n'y a pas de label associé à l'input et ça vient créer une _failure_ au niveau de l'a11y. La valeur de l'attribut `for` du `label` pointe vers l'`id` du `<span>` qui englobe le slider au complet. Je ne sais pas à qu'elle point nous avons le contrôle là dessus, mais il faudrait qu'il soit associé à l'`id` de l'`input type="range"`. Sinon, en regardant ce que MUI ont, ils semblent avoir un `aria-label` sur les _thumbs_. Ça pourrait également venir fixer le problème.

Sinon un petit commentaire en lien avec une couleur.

2024-06-07 18:42 UTC, meriouma reviewed
Cool POC avec mui. LGTM pour le code. Je laisse Larry et Marc regarder le reste.

2024-06-07 18:42 UTC, meriouma commented on packages/react/src/components/slider/slider.tsx
> +    top: 41px;
C'est pas lié à la PR nécessairement, mais je me demande, ce serait pas mieux si on avait tout en `rem` pour le zoom?

2024-06-10 17:51 UTC, LarryMatte commented on packages/react/src/components/slider/slider.tsx
> +    top: 41px;
J'ai zoomé la page au complet, changé la taille du texte, et ca ne semble pas changer grand chose.
Par contre, je suis un peu du même avis de changer le `41px` pour `2.5rem`.

2024-06-20 15:05 UTC, maboilard requested changes
Quelques petits commentaires:
- Le font-size et le line-height du label et des numéros sont trop grands
- La couleur des numéros n'est pas la bonne. Le token devrait référer sur le alias token "color-content-subtle"
- La couleur de border du Slider-thumb n'est pas la même que sur les maquettes Figma

2024-07-18 11:50 UTC, savutsang commented
> * Il manquerait le tooltip lorsque l'utilisateur interagit avec le composant en utilisant les touches (flèches) du clavier. Présentement le tooltip est seulement affiché lorsqu'un user utilise la souris. [MUI semble avoir la feature](https://mui.com/material-ui/react-slider/#discrete-sliders).

Done

> * Présentement, il n'y a pas de label associé à l'input et ça vient créer une _failure_ au niveau de l'a11y. La valeur de l'attribut `for` du `label` pointe vers l'`id` du `<span>` qui englobe le slider au complet. Je ne sais pas à qu'elle point nous avons le contrôle là dessus, mais il faudrait qu'il soit associé à l'`id` de l'`input type="range"`. Sinon, en regardant ce que MUI ont, ils semblent avoir un `aria-label` sur les _thumbs_. Ça pourrait également venir fixer le problème.

Done, le input a maintenant le meme id que le `label for`.

2024-07-18 11:54 UTC, savutsang commented
> * Le font-size et le line-height du label et des numéros sont trop grands

Fixed

> * La couleur des numéros n'est pas la bonne. Le token devrait référer sur le alias token "color-content-subtle"

Done, j'ai ajoute un nouveau token pour ca `slider-rail-label-text-color`

> * La couleur de border du Slider-thumb n'est pas la même que sur les maquettes Figma

Done

2024-07-18 13:36 UTC, maboilard submitted a review, later dismissed
LGTM!

2024-07-18 14:00 UTC, LarryMatte requested changes
Dans la variant _Range_, les deux `input` ont le même `id`, il faudrait qu'il soit différent.
<img width="1159" alt="Screenshot 2024-07-18 at 9 59 51 AM" src="https://github.com/user-attachments/assets/bc23b03d-a91f-4f29-9c73-2437010fee8c">

2024-07-18 15:27 UTC, savutsang commented
> Dans la variant _Range_, les deux `input` ont le même `id`, il faudrait qu'il soit différent. 

Ah bien vu. Mais ca serait quoi la resolution dans ce cas? Si je fais comme cette exemple, je pourrais utiliser aria-label dans ce cas, mais faudrait le user me passe les 2 different labels
https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/examples/slider-multithumb/

2024-07-18 15:45 UTC, LarryMatte commented
> > Dans la variant _Range_, les deux `input` ont le même `id`, il faudrait qu'il soit différent.
> 
> Ah bien vu. Mais ca serait quoi la resolution pour l'accessibilite dans ce cas? Si je fais comme cette exemple, je pourrais utiliser aria-label dans ce cas, mais faudrait le user me passe les 2 different labels https://www.w3.org/WAI/ARIA/apg/patterns/slider-multithumb/examples/slider-multithumb/

Tu pourrais p-e avoir un `aria-label` sur chacun des inputs, utiliser le `label` associé au composant et lui ajouter le mot "range".
```
<label>Patate</label>
...
<input aria-label="Patate range" />
<input aria-label="Patate range" />
```
C'est ce que semble faire [MUI](https://mui.com/material-ui/react-slider/#range-slider)
<img width="600" alt="Screenshot 2024-07-18 at 11 40 05 AM" src="https://github.com/user-attachments/assets/1043f09d-7eab-4355-9eb4-c46a9136557a">

Si nous voulons y aller avec un truc similaire à ce que tu as partagé. Nous pourrions ajouter un min et max au label et ensuite ajouter le label.
```
<label>Patate</label>
...
<input aria-label="Minimum Patate" />
<input aria-label="Maximum Patate" />
```
Mais je crois que c'est p-e trop spécifique et p-e que dans certain cas, ça ne fonctionnerait p-e pas aussi bien tout dépendant du label associé.

2024-08-15 16:15 UTC, meriouma commented on packages/react/src/components/slider/slider.tsx
> +const SliderValueTooltip: FunctionComponent<SliderValueLabelSlotProps> = ({ children }) => (
Pour rester compatible avec React 18
```suggestion
const SliderValueTooltip: FunctionComponent<PropsWithChildren<SliderValueLabelSlotProps>> = ({ children }) => (
```

2024-08-15 16:15 UTC, meriouma commented on packages/react/src/components/slider/slider.tsx
> +// eslint-disable-next-line comma-spacing
Je suis confus, y'a pas de virgule sur la next-line?

2024-08-15 16:15 UTC, meriouma commented on packages/react/src/components/slider/slider.tsx
> +                {/* <BaseSlider slotProps={{ valueLabel: }}> */}
Code commenté?

2024-08-15 16:15 UTC, meriouma commented on packages/react/src/themes/tokens/alias-tokens.ts
> +    | 'color-border-brand-bold'
J'ai l'impression que ça va être à ajuster dans dans theme-directory? @hebernardEquisoft @pylafleur

2024-08-15 16:15 UTC, meriouma commented on packages/react/src/themes/tokens/component/slider-tokens.ts
> +    | 'slider-thumb-disabled-border-color';
Je suis pas certain de la différence entre `track` et `rail`, et `thumb`, c'est le gros rond?

2024-08-16 16:55 UTC, hebernardEquisoft commented on packages/react/src/themes/tokens/alias-tokens.ts
> +    | 'color-border-brand-bold'
Mmhhhm tant que c'est pas un renaming de tokens, tout devrait être beau!

2024-08-16 18:57 UTC, meriouma commented on packages/react/src/themes/tokens/alias-tokens.ts
> +    | 'color-border-brand-bold'
Faudra pas l'ajouter aux themes pour pas que ce soit weird? Quoiqu'en même temps, elle sert juste pour le slider en ce moment.

2024-08-21 21:04 UTC, savut-allomia commented on packages/react/src/themes/tokens/alias-tokens.ts
> +    | 'color-border-brand-bold'
Je pense c'est un renaming pour vous. J'explique ce qui se passe ici.

Le `global-header` utilisait avant 'color-border-brand', en regardant ca avec MA pourquoi le slider n'avait pas la bonne couleur malgre les bon token Figma, on s'est rendu compte que ce token n'avait pas bonne couleur.

On a renomme 'color-border-brand' a 'color-border-brand-bold' (utilise par global-header seulement)
On a ajoute le nouveau 'color-border-brand' avec la bonne couleur (utilise par Slider seulement)

2024-08-21 21:04 UTC, savutsang commented on packages/react/src/themes/tokens/alias-tokens.ts
> +    | 'color-border-brand-bold'
Je pense c'est un renaming pour vous. J'explique ce qui se passe ici.

Le `global-header` utilisait avant 'color-border-brand', en regardant ca avec MA pourquoi le slider n'avait pas la bonne couleur malgre les bon token Figma, on s'est rendu compte que ce token n'avait pas bonne couleur.

On a renomme 'color-border-brand' a 'color-border-brand-bold' (utilise par global-header seulement)
On a ajoute le nouveau 'color-border-brand' avec la bonne couleur (utilise par Slider seulement)

2024-08-21 23:11 UTC, savutsang commented on packages/react/src/components/slider/slider.tsx
> +const SliderValueTooltip: FunctionComponent<SliderValueLabelSlotProps> = ({ children }) => (
On ne le voit pas, mais le children est explicitement defini dans SliderValueLabelSlotProps.
https://github.com/mui/material-ui/blob/47329acc3f318c2a427c0d025d3aaf7aa6a13c66/packages/mui-base/src/Slider/Slider.types.ts#L219

2024-08-21 23:57 UTC, savutsang commented on packages/react/src/themes/tokens/component/slider-tokens.ts
> +    | 'slider-thumb-disabled-border-color';
Tu souleve un tres bon point, ca me semblais evident a force d'utiliser MUI, mais apres reflexion, c'est vrai que c'est pas si clair.

Pour MUI: 
1. Thumb = rond
2. Rail = barre complete en grise
3. Track = barre colore en bleu

J'ai regarde les autres DS pour comparer pis c'est tres varies

https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-thumb (rond)
https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-track (barre complete)
https://spectrum.adobe.com/page/slider/ (1. Handle (mais dans le html c'est Thumb), 2. Track, 3. Fill)
https://carbondesignsystem.com/components/slider/usage/ (1. Thumb, 2. Track, 3. Filled-track)
https://ant.design/components/slider (1. Handle, 2. Rail, 3. Track)
https://fluent2.microsoft.design/components/web/react/slider/usage (1. Thumb, 2. Rail, 3. Rail aussi)
https://developer.apple.com/documentation/uikit/uislider (1. Thumb, 2. Track)

Bon faque c'est quoi qui ferait le plus de sens pour vous? @LarryMatte @maboilard

2024-08-22 17:59 UTC, maboilard commented on packages/react/src/themes/tokens/component/slider-tokens.ts
> +    | 'slider-thumb-disabled-border-color';
Après consultation avec Larry, on en est arrivé à cette conclusion basé sur la nomenclature du Progress Tracker principalement :
- Thumb = Le Cercle avec lequel on peut intéragir
- Track empty = La barre complète du Slider
- Track filled = La partie remplie de la barre

Ce qui donnerait:
slider-track-empty-background-color’
‘slider-track-empty-disabled-background-color’
‘slider-track-empty-label-text-color’
‘slider-track-empty-mark-background-color’
‘slider-track-empty-mark-disabled-background-color’
‘slider-track-filled-background-color’
‘slider-track-filled-disabled-background-color’
‘slider-track-filled-mark-background-color’
‘slider-track-fiiled-mark-disabled-background-color’
‘slider-thumb-background-color’
‘slider-thumb-border-color’
‘slider-thumb-disabled-border-color’

2024-08-22 19:37 UTC, savutsang commented
> Tu pourrais p-e avoir un `aria-label` sur chacun des inputs, utiliser le `label` associé au composant et lui ajouter le mot "range".
> 
> ```
> <label>Patate</label>
> ...
> <input aria-label="Patate range" />
> <input aria-label="Patate range" />
> ```
> 

J'ai fait comme MUI "[label] range" pour les deux, car le code me fourni pas d'information si c'est le thumb min ou max.

2024-08-26 13:56 UTC, LarryMatte submitted a review, later dismissed
Perso c'est good. Je laisse Max, P-Y et Marc décider de la suite

2024-08-26 14:18 UTC, maboilard submitted a review, later dismissed

2024-09-20 15:18 UTC, WilliamsTardif approved these changes

2024-09-20 15:18 UTC, WilliamsTardif commented on packages/react/src/components/slider/slider.tsx
> +const StyledSlider = styled(BaseSlider)`
[MAY] Il y a beaucoup de styling ici, il serais peut-être intéressant d'avoir ce styling dans un autre fichier `style.ts` ? 🤔

2024-09-28 19:01 UTC, meriouma approved these changes

2024-09-28 19:01 UTC, meriouma commented on packages/react/src/components/slider/slider.tsx
> +const StyledSlider = styled(BaseSlider)`
Est-ce que certaines des dimensions devraient être exprimées en `rem` ou en variable css plutôt?

2024-10-24 16:22 UTC, savutsang commented on packages/react/src/components/slider/slider.tsx
> +    border: 1px solid ${({ theme }) => theme.component['tooltip-popper-container-border-color']};
Je comprend le point mais c'est plutot une emulation du component Tooltip. Idealement on utiliserait le component Tooltip ici s'il n'y avait pas de probleme visuel au dragging.

2024-10-24 16:54 UTC, savutsang commented on packages/react/src/components/slider/slider.tsx
> +const StyledSlider = styled(BaseSlider)`
Ca sera fixe dans un autre billet.

2024-10-24 17:14 UTC, savutsang commented
Ready for review

2024-10-28 17:39 UTC, meriouma reviewed
Dernier petit détail, sinon LGTM.

2024-10-29 19:26 UTC, savutsang commented on packages/react/src/components/slider/slider.tsx
> +    border: 1px solid ${({ theme }) => theme.component['tooltip-popper-container-border-color']};
On pourrait pt creer une version CSS du Tooltip dans le folder Tooltip a place, quoique c'est weird car le component Tooltip ne s'en sert pas.

2024-10-29 19:36 UTC, savutsang commented on packages/react/src/components/slider/slider.tsx
> +    border: 1px solid ${({ theme }) => theme.component['tooltip-popper-container-border-color']};
On pourrait pt creer une version CSS du Tooltip dans le folder Tooltip a place, c'est possible que ca soit reutilise ailleur si on a le meme concern. Le seul bemol c'est que le component Tooltip ne s'en sert pas et c'est bizarre de le mettre la.

2024-10-29 20:02 UTC, meriouma approved these changes

2024-10-29 20:33 UTC, meriouma approved these changes

2024-10-29 20:33 UTC, merged