feat(radio-button): standalone radio button component
kronostechnologies/design-elements pull request #903
Opened 2024-06-12 19:29 UTC by ogermain-kronos

https://equisoft.atlassian.net/browse/DS-1159

Notez que j'ai fait une couple de renames `radio-button` => `radio-button-group`, d'où les changements dans les stories que GitHub prend comme du cash comme un ajout.

2024-06-13 15:46 UTC, LarryMatte requested changes
quelques commentaires ici et là / suggestions

2024-06-13 15:46 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +    color: ${({ theme, disabled }) => (disabled ? theme.component['radio-button-disabled-background-color'] : theme.component['radio-button-background-color'])};;
il y a deux ";" à la fin de la ligne.

2024-06-13 15:46 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +    className?: string
manque le ";" à la fin

2024-06-13 15:46 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +            <StyledLabel
Le `<label>` devrait uniquement s'afficher s'il est explicitement défini par l'utilisateur.
De plus, il serait préférable que le `<label>` reprenne par défaut l'`id` de l'élément `<input>`. Ca éviterait aux développeurs de devoir l'ajouter manuellement et réduirait ainsi le risque d'oubli, ce qui pourrait compromettre l'accessibilité de l'interface.

À valider avec les autres devs mais tu pourrais avoir:
```suggestion
import { useId } from '../../hooks/use-id';
 ...
const generatedId = useId();
const inputId = id || generatedId;
...
<StyledInput
  data-testid={`radiobutton-${inputId}`}
  id={inputId}
... 
 {label && (
	<StyledLabel
		data-testid={`radiobutton-${inputId}_label`}
		htmlFor={inputId}
		className={`${className}_label`}
		disabled={disabled}
	>
	{
		visuallyHidden
		? <VisuallyHidden>{inputLabel}</VisuallyHidden>
		: inputLabel
	}
	</StyledLabel>
)}
```

2024-06-14 15:47 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +`;
Enleve l'interface, ces props ne sont pas utilise

```suggestion
const StyledLabel = styled.label`
    font-size: 0.875rem;
    line-height: 1.5rem;
    margin-left: var(--spacing-1x);
`;
```

2024-06-14 16:02 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const inputLabel = externalLabelId ? `${label} ${externalLabel}` ?? '' : label;
Je comprend pas le besoin de externalLabelId, que le user fasse ca lui-meme pis set le `label`.

2024-06-14 16:10 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +    visuallyHidden,
On n'a pas besoin de visuallyHidden, si t'a un label, t'affiche le label, sinon t'affiche pas.
Le ariaLabel et ariaLabelledBy sont justement la pour avoir la possibilite de override le label ou setter un label invisible.

Genre ce tag est complet, pas besoin d'ajouter `<VisuallyHidden>`
```
<input aria-label="Mon Label" />
```

2024-06-14 16:23 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +            <StyledLabel
Les indentations dans ce block a corriger

2024-06-14 16:38 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +                className={`${className}_label`}
Enleve ca, c'est non expected et c'est pas safe. Si le user set className="country", On peut pas etre 100% sur que le user n'a pas deja une class CSS "country_label" pour d'autre chose.

2024-06-14 22:19 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +    visuallyHidden,
Ça c'est de mon bord. Quand nous avions évalué les différents cas, nous avions ajouté le `visually hidden` en option et je l'avais documenté dans la story.
On pourra en reparlé au prochain meeting

2024-06-20 14:08 UTC, maboilard requested changes
Lorsqu'une option est Checked et Checked-disabled, il y a un effet hover qu'on a pas actuellement sur le Radio Button. Il faudrait que l'état Checked-hover ne change rien au design

2024-06-22 10:05 UTC, WilliamsTardif approved these changes

2024-06-22 10:05 UTC, WilliamsTardif commented on packages/react/src/components/radio-button/radio-button.tsx
> +export const RadioButton: FunctionComponent<RadioButtonProps> = ({
Le nouveau radio-button devrait-il être intégré dans `radio-button-group.tsx` ?
Présentement c'est seulement un input dans `radio-button-group.tsx` 🤔

2024-07-02 13:24 UTC, ogermain-kronos commented on packages/react/src/components/radio-button/radio-button.tsx
> +export const RadioButton: FunctionComponent<RadioButtonProps> = ({
Le but de cette PR c'est d'avoir le radio-button de prêt pour ensuite l'intégrer au radio-button-group dans c'te PR là https://github.com/kronostechnologies/design-elements/pull/888

2024-07-02 14:02 UTC, ogermain-kronos commented on packages/react/src/components/radio-button/radio-button.tsx
> +`;
`disabled` est utilisé.

2024-07-02 14:02 UTC, ogermain-kronos commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const inputLabel = externalLabelId ? `${label} ${externalLabel}` ?? '' : label;
C'est une feature demandée dans le Jira. @LarryMatte ?

2024-07-02 14:02 UTC, ogermain-kronos commented on packages/react/src/components/radio-button/radio-button.tsx
> +                className={`${className}_label`}
Il me semble que le Jira mentionnait une `class` dans la structure html souhaitée, non? @LarryMatte

2024-07-02 18:25 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +`;
C'est juste qu'il est passe dans le props, mais on ne fait rien avec. C'est mieux de l'enlever pour le moment, et on l'ajouterais a ce moment la.

```
<StyledLabel
    data-testid={`radiobutton-${inputId}_label`}
    htmlFor={inputId}
    className={`${className}_label`}
    disabled={disabled}  // enleve ici aussi
>
```

2024-07-02 18:42 UTC, ogermain-kronos commented on packages/react/src/components/radio-button/radio-button.tsx
> +`;
Désolé mais j'te suis pas pantoute. `disabled` est clairement pris en compte dans les components enfants et sert à les désactiver si `true`.

![image](https://github.com/kronostechnologies/design-elements/assets/6412423/f0f83cfa-64a3-4593-afa4-7dbf9c35ae41)

En plus, le Jira demande de prendre en compte le state `disabled`.

2024-07-02 21:08 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +`;
Oui pour le Component dans l'ensemble, mais pas pour l'element StyledLabel

2024-07-05 21:54 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +const StyledLabel = styled.label<StyledLabelProps>`
Enlever `disabled` de l'interface aussi, ca revient a enlever l'interface completement

```suggestion
const StyledLabel = styled.label`
```

2024-07-10 19:39 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +    visuallyHidden,
`<VisuallyHidden>` n'est plus nécessaire, nous allons seulement utiliser le `aria-label` pour définir un label non-visible.

2024-07-10 22:23 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const inputLabel = externalLabelId ? `${label} ${externalLabel}` ?? '' : label;
Ne plus en tenir compte.
Nous allons seulement utiliser le `aria-labelledby` pour référencer du texte autre que le label de l'input.
J'ai mis à jour la carte avec les plus récent requirements.

2024-07-10 22:29 UTC, LarryMatte requested changes

2024-07-10 22:29 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +
Deux lignes à ajouter ici:
1. ajouter un `flex-shrink: 0;`
lorsque le texte tombe sur 2 lignes le radio button se fait écrasé un peu.
2. ajouter un `margin-top: var(--spacing-half);`
lorsque le texte tombe sur 2 lignes, le radio button n'est plus centré avec le texte.

<img width="345" alt="Screenshot 2024-07-10 at 6 28 08 PM" src="https://github.com/kronostechnologies/design-elements/assets/3722754/eb115a1a-bf71-42d0-a5e8-b8fdd486c88c">

2024-07-10 22:33 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +
il va également falloir remplacer le `align-items: center` par `align-items: flex-start;` sur le `StyledContainer`

2024-07-15 13:48 UTC, LarryMatte commented
LGTM en ce qui me concerne.
Je laisse Savut, Max et P-Y mettre leur stamp d'_approval_.

2024-07-15 19:53 UTC, maboilard requested changes
Il n'y a pas de changement d'état lorsque je suis en état hover.

2024-07-15 20:30 UTC, savutsang commented on packages/react/src/components/radio-button/radio-button.tsx
> +    const inputId = id || generatedId;
Details mineure, c'est mieux de passer le id a useId, comme ca il ne va pas generer un uuid pour rien. Pis ca enleve l'autre variable superflu. Pis les snapshots vont etre plus clean aussi.

```suggestion
    const inputId = useId(id);
```

Sinon pour le reste c'est LGTM. Je laisse @maboilard valider les styling.

2024-07-15 20:31 UTC, savutsang commented
Le reste c'est LGTM. Je laisse @maboilard valider les styling.

2024-07-17 14:47 UTC, maboilard approved these changes

2024-07-17 15:07 UTC, LarryMatte commented on packages/react/src/components/radio-button/radio-button.tsx
> +    }
@maboilard est-ce que le `label` devrait avoir le texte grisé comme dans le figma pour l'état `disabled`? Tu as accepté la PR mais je lève le flag pareil.
Oli, si marc demande la modif, quelques options ou p-e que tu as mieux:
```suggestion
    &:disabled {
        & + label {
            color: [token de couleur];
        }
    }
    
    OU
    
    &:disabled {
        & + ${StyledLabel} {
            color: [token de couleur];
        }
    }
```

2024-07-17 15:11 UTC, maboilard commented on packages/react/src/components/radio-button/radio-button.tsx
> +    }
Tu as bien raison, ce détail m'a échappé. Il faudrait que le token réfère au alias token `color-content-disabled`

2024-07-17 15:12 UTC, maboilard requested changes
Comme l'a soulevé Larry, il faut changer la couleur du label en état "Disabled". Après ce sera tout.

2024-07-17 15:50 UTC, maboilard approved these changes

2024-07-17 19:17 UTC, maboilard approved these changes

2024-07-17 19:30 UTC, LarryMatte approved these changes
LGTM Good job et merci Oli

2024-07-17 19:32 UTC, merged