feat(TextInput): ajout adornment (DS-1140)
kronostechnologies/design-elements pull request #949
Opened 2024-07-22 16:07 UTC by WilliamsTardif

JIRA: https://equisoft.atlassian.net/browse/DS-1140

## Description des changements
- Possibilité d'ajouter un _adornment_.
L'adornement peut être un `Icon` ou du `text`.
- Possible d'ajouter _l'adornment_ au début ou la fin du `TextInput`.
- Lorsqu'on click sur _l'adornement_ le `TextInput` est `focus`.

2024-07-23 18:49 UTC, LarryMatte requested changes
quelques petites modifications ici et là.

2024-07-23 19:28 UTC, savutsang commented on packages/react/src/components/text-input/text-input.tsx
> +                    $textAlign={adornmentPosition === 'end' ? 'right' : 'left'}
Precision que dans NumericInput c'est deux settings separe. Ca devrait l'etre aussi pour le TextInput.

2024-07-23 19:30 UTC, LarryMatte commented on packages/react/src/components/text-input/text-input.tsx
> +                    $textAlign={adornmentPosition === 'end' ? 'right' : 'left'}
Écoute Savut ahha

2024-07-29 16:06 UTC, WilliamsTardif commented on packages/react/src/components/text-input/text-input.tsx
> +const Adornment = styled.span<{ $position: 'start' | 'end' }>`
J'ai pu adapter la couleur pour l'icon, mais puisqu'on ajoute directement l'icon dans le paramètre du TextInput, je ne peux pas modifier le _size_ de l'icon à part en appliquant directement le size au component passé en paramètre.
`adornment: <Icon size='16' name='user' />,`

Cela signifie que la grosseur de l'icon ne seras pas nécessairement responsive de base, mais il sera possible d'intégré la responsibilité lorsqu'on utilise le component et en passant un size responsible à l'adornment Icon passé en paramètre.
Exemple:
`adornment: <Icon size={ isMobile ? '24' : '16' } name='user' />,`

Est-ce que ce comportement vous convient ?
Si nous voulons gérer ce comportement, je vais probablement ajouter un prop au component pour ajouter un Icon.
Donc, nous nous retrouverons avec un prop pour le text et un pour l'icon.

Qu'est-ce que vous en pensez ?

2024-07-29 18:17 UTC, LarryMatte commented on packages/react/src/components/text-input/text-input.tsx
> +const Adornment = styled.span<{ $position: 'start' | 'end' }>`
Est-ce que tu pourrais avoir un truc du style:
```suggestion
const Adornment = styled.span<{ $position: 'start' | 'end' }>`
    ...

    > svg {
        height: ${isMobile ? 1 : 1.5}rem; // ajuste les valeurs en consequence
        width: ${isMobile ? 1 : 1.5}rem; // ajuste les valeurs en consequence
    }
`;
```

2024-08-02 13:16 UTC, hebernardEquisoft commented on packages/react/src/components/text-input/text-input.tsx
> +    adornmentPosition?: 'start' | 'end';
Ma suggestion:
```
leftAdornment?: ReactNode;
rightAdornment?: ReactNode;
```

2024-08-02 13:16 UTC, hebernardEquisoft commented on packages/react/src/components/text-input/text-input.tsx
> +            <Wrapper $disabled={disabled} $valid={validity}>
Ma suggestion:

```suggestion
const StyledWrapper = styled.div`
    position: relative;
    display: flex;
    align-items: center;
`;

const Adornment = styled.div<{ position: 'left' | 'right' }>`
   color: ${({ theme }) => theme.component['text-input-placeholder-text-color']};
    position: absolute;
    ${({ position }) => (position === 'left' ? 'left: 0;' : 'right: 0;')}
    display: flex;
    align-items: center;
    height: 100%;
`;

const StyledInput = styled.input<{ $isMobile: boolean; $hasLeftAdornment: boolean; $hasRightAdornment: boolean }>`
    ...
    
    padding-bottom: 0;
    padding-top: 0;
    padding-right: ${({ $hasRightAdornment }) => ($hasRightAdornment ? 'var(--spacing-4x)' : 'var(--spacing-1x)')};
    padding-left: ${({ $hasLeftAdornment }) => ($hasLeftAdornment ? 'var(--spacing-4x)' : 'var(--spacing-1x)')};
    
    ...
`;
    const WrapperComponent = (leftAdornment || rightAdornment) ? StyledWrapper : Fragment;

        <WrapperComponent>
            {leftAdornment && <Adornment position="left">{leftAdornment}</Adornment>}
            <StyledInput
                ...
                $hasLeftAdornment={!!leftAdornment}
                $hasRightAdornment={!!rightAdornment}
            />
            {rightAdornment && <Adornment position="right">{rightAdornment}</Adornment>}
        </WrapperComponent>
```

2024-08-02 15:56 UTC, maboilard commented on packages/react/src/components/text-input/text-input.tsx
> +const Adornment = styled.span<{ $position: 'start' | 'end' }>`
Exactement! Désolé, ce commentaire est passé sous mon radar. J'en profite également pour mentionné que la taille de l'icône est plus grande que ce qui est actuellement dans Figma. L'icône devrait avoir une taille de 16x16 et non pas de 24x24.

2024-08-02 16:16 UTC, WilliamsTardif commented on packages/react/src/components/text-input/text-input.tsx
> +const Adornment = styled.span<{ $position: 'start' | 'end' }>`
J'ignorais que s'était possible de faire ça. Merci de la proposition.
Sa fonctionne bien avec ça. ✅

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +    hasRightAdornment: boolean;
```suggestion
    $isMobile: boolean;
    $hasLeftAdornment: boolean;
    $hasRightAdornment: boolean;
```

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +    color: ${({ theme }) => (theme.component['text-input-adornment-text-color'])};
```suggestion
    color: ${({ theme }) => theme.component['text-input-adornment-text-color']};
```

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +    rightAdornment,
Les props sont preeesque en ordre alpha, sans réorganiser les autres, peux tu mettre `leftAdornment` après `label` et `rightAdornment` après `required`.

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +`;
Je pense que j'exploserais en 3 components. Ça simplifierait le render plus bas.
```suggestion
interface AdornmentProps {
    $isMobile: boolean;
}

const Adornment = styled.span<AdornmentProps>`
    align-self: center;
    color: ${({ theme }) => theme.component['text-input-adornment-text-color']};
    display: flex;

    > svg {
        height: ${({ $isMobile }) => ($isMobile ? '24px' : '16px')};
        width: ${({ $isMobile }) => ($isMobile ? '24px' : '16px')};
    }
`;

const LeftAdornment = styled(Adornment)`
    padding-left: var(--spacing-1x);
`;

const RightAdornment = styled(Adornment)`
    padding-right: var(--spacing-1x);
`;
```

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +    ), [leftAdornment, rightAdornment, isMobile]);
C'est bizarre d'avoir un memo pour un render conditionnel. C'est mieux de laisser React gérer ça.

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +                <StyleInput
```suggestion
                {leftAdornment && (
                    <LeftAdornment
                        onClick={handleAdornmentClick}
                        $isMobile={isMobile}
                    >
                        {leftAdornment}
                    </LeftAdornment>
                )}

                <StyleInput
```

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +                {rightAdornment && adornmentContent}
```suggestion
                />

                {rightAdornment && (
                    <RightAdornment
                        onClick={handleAdornmentClick}
                        $isMobile={isMobile}
                    >
                        {leftAdornment}
                    </RightAdornment>
                )}
```

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +    ), [leftAdornment, rightAdornment, isMobile]);
En plus en fait y'a un bug, ça empêche d'avoir un left et un right. Si on met un left et un right, le left va se ramasser aux deux places.

2024-08-16 15:55 UTC, meriouma commented on packages/react/src/themes/tokens/component/text-input-tokens.ts
> +    | 'text-input-adornment-text-color';
Est-ce que `text-color` c'est le bon nom? Ça devrait pas juste être `...adornment-color`?

2024-08-16 15:55 UTC, meriouma commented on packages/storybook/stories/text-input.mdx
> -Text input allows users to enter a single line of text into a form.
J'ai l'impression que ton `.editorconfig` est pas bon. Les trailing whitespaces devraient pas être enlevées par ton éditeur.

2024-08-16 15:56 UTC, meriouma commented on packages/react/src/components/text-input/text-input.tsx
> +`;
Et corrigerait le bug aussi.

2024-08-19 15:45 UTC, LarryMatte commented on packages/react/src/themes/tokens/component/text-input-tokens.ts
> +    | 'text-input-adornment-text-color';
@maboilard voir le commentaire de Max

2024-08-26 13:53 UTC, maboilard approved these changes

2024-08-26 17:59 UTC, LarryMatte requested changes
Petit commentaire en ce qui me concerne, pour le reste, je laisse Max, P-Y et Savut faire le tour.

2024-08-26 17:59 UTC, LarryMatte commented on packages/react/src/components/text-input/text-input.tsx
> +    display: flex;
Ajouter un `flex-shrink: 0;`. Si pour XYZ raison, l'adornment a plus d'un mot, il tombe sur deux lignes.
<img width="164" alt="Screenshot 2024-08-26 at 1 28 59 PM" src="https://github.com/user-attachments/assets/29f9cef6-91bc-4c74-8d06-68a3321ed434">

2024-09-06 17:22 UTC, WilliamsTardif commented on packages/react/src/components/money-input/money-input.test.tsx.snap
> +    <div
Je ne crois pas que sa soit voulu 😅

2024-09-06 17:33 UTC, WilliamsTardif commented on packages/react/src/components/text-input/text-input.tsx
> +`;
Bonne idée, c'est une fasson de faire qui m'avait pas passé par la tête.
Merci !

2024-09-06 17:35 UTC, WilliamsTardif commented on packages/react/src/components/text-input/text-input.tsx
> +    ), [leftAdornment, rightAdornment, isMobile]);
Good catch. Je fix ça 👍

2024-09-06 17:39 UTC, WilliamsTardif commented on packages/react/src/components/text-input/text-input.tsx
> +    display: flex;
Good catch Merci !

2024-09-10 14:31 UTC, pylafleur commented on packages/storybook/stories/text-input.mdx
> -Text input allows users to enter a single line of text into a form.
Pourquoi on override ça pour les mdx? Quels sont les cas légitimes pour laisser des trailing whitespaces?

2024-09-10 14:39 UTC, pylafleur submitted a review, later dismissed
LGTM

2024-09-20 14:07 UTC, LarryMatte submitted a review, later dismissed
Ça semble good pour moi. Je fais confiance aux autres pour le reste.
Good job!

2024-09-23 13:11 UTC, maboilard approved these changes

2024-09-25 21:11 UTC, maboilard approved these changes
Good pour moi!

2024-09-27 14:40 UTC, pylafleur approved these changes

2024-09-27 14:41 UTC, merged

2024-09-30 00:44 UTC, meriouma commented on packages/storybook/stories/text-input.mdx
> -Text input allows users to enter a single line of text into a form.
2 espaces = 1 saut de ligne normalement. Alors si tu veux un vrai saut de ligne, ça arrive que la ligne finisse par 
```
Ma première ligne.<espace> 
Ma deuxième ligne.
```