feat(fieldset)!: adds fieldset component
kronostechnologies/design-elements pull request #952
Opened 2024-07-23 21:25 UTC by hebernardEquisoft

[DS-1161](https://equisoft.atlassian.net/browse/DS-1161)

## Description
Ici on vient ajouter la composante `fieldset` à notre merveilleux Design System!

## Tests fonctionnels
...

2024-07-25 15:11 UTC, savutsang commented on packages/react/src/components/fieldset/fieldset.component.tsx
C'est pas la meme naming qu'on utilise pour ce projet.

2024-07-25 15:40 UTC, savutsang commented on packages/react/src/components/fieldset/legend.component.tsx
> +        <StyledLegend datatest-id='legend' {...props} isMobile={isMobile}>
Il y a des attributs invalid pour l'element Legend (bold, disabled, etc.) qui vont etre render dans le DOM lorsqu'on va upgrade a SC 6, ce qui va causer plein de warning React. Aussi meme si nous on upgrade pas encore, les projets qui eux utilisent SC 6 et importe le DS, ils vont avoir ce problem pareil (dont l'equipe d'Analyze).

Pour prevenir ca, on a deja commence a utiliser les transient props un peu partout depuis un bout (https://styled-components.com/docs/api#transient-props).

2024-07-25 16:39 UTC, savutsang commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +                <Fieldset id='customId' legend={{ children: 'Legend Text' }}>
Y a de quoi qui me tracasse de passer par children pour setter le text pour le legend, je le trouve pas assez clair pour de quoi qu'on expose publiquement, et c'est pas uniforme avec nos autre components. 

J'aurais dit que ca serait p-t mieux de meme...

```
<Fieldset id='customId' legend="Legend Text" legendProps={{ disabled : true }}>
```

2024-07-25 17:23 UTC, hebernardEquisoft commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +                <Fieldset id='customId' legend={{ children: 'Legend Text' }}>
Au lieu de créer 2 props différentes pour le legend, j'ai permis que la legend prop de fieldset soit un string ou un LegendProps... 

J'ouvre la possibilité de pouvoir peut-être passer un ReactElement pour la prop de legend et ainsi avoir ces différentes possibilités:

```
<Fieldset id='customId' legend="Text">
<Fieldset id='customId' legend={{ disabled : true, bold: true }}>
<Fieldset id='customId' legend={<Legend disabled bold>Text</Legend>}>
```

On en pense quoi de ça?

2024-08-09 15:52 UTC, WilliamsTardif reviewed
Il manque la DOC pour le storybook ou ce sera faite dans une autre tâche ?

2024-08-09 15:52 UTC, WilliamsTardif commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +            expect(legend.exists()).toBeTruthy();
Le expect exist n'est pas nécessaire selon, moi. Le premier est suffisant pour prouver l'existance de `legend`.
Le premier expect, ne fonctionnerait pas si `legend` n'existerait pas, right ?
Même chose pour le test qui suit. 👇

2024-08-09 15:52 UTC, WilliamsTardif commented on packages/react/src/components/fieldset/legend.test.tsx
> +        it.each(sizes)('renders with size %s', (size) => {
Cool les tests avec paramètres, j'ignorais qu'on pouvait faitre ça.
Je suis bien content d'avoir review ça.

2024-08-09 16:10 UTC, hebernardEquisoft commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +            expect(legend.exists()).toBeTruthy();
Bien d'accord avec toi! J'ai tendance à vouloir beurrer épais eheh

2024-08-12 13:00 UTC, WilliamsTardif approved these changes

2024-08-20 18:17 UTC, meriouma commented on packages/react/src/components/fieldset/legend.tsx
> +export const Legend: FC<LegendProps> = ({
Ici aussi je ramènerais l'interface de props

2024-08-20 18:17 UTC, meriouma commented on packages/react/src/components/fieldset/index.ts
> +export * from './legend';
J'exporterais pas le component s'il est pas supposé être utilisé à l'exterieur du moduel fieldset

2024-08-20 18:17 UTC, meriouma commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +                <Fieldset id='customId' legend={{ children: 'Legend Text' }}>
Je pense que si on va avec une seule prop comme tu as fait, `legend` devrait être quelque chose comme ça mais peut-être plus clean : `legend?: string | (Omit<LegendProps, 'children'> & { text: string });`. Et ensuite dans le component fieldset, mapper le texte vers le children :
```
const { text, ...legendProps } = legend;
return (
    <Legend
        id={`${id}-legend`}
        disabled={disabled}
        {...legendProps /* eslint-disable-line react/jsx-props-no-spreading */}
    >
        {text}
    </Legend>
);
```

Rendu là, peut-être que legend devrait juste être `legend?: Omit<LegendProps, 'children'> & { text: string };` et pour une légende simple, on passe `legend={{ text: "My legend" }}`? 🤔

2024-08-23 15:46 UTC, hebernardEquisoft commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +                <Fieldset id='customId' legend={{ children: 'Legend Text' }}>
Je penche avec la dernière proposition!

2024-08-23 17:22 UTC, hebernardEquisoft commented on packages/react/src/components/fieldset/fieldset.tsx
> +export const Fieldset = forwardRef(({
Ça crée des cycles de dépendances puisqu'ils sont utilisés dans les styled components également.
Pour remédier à la situation, je devrai également ramener les styled components au niveau de la composante principale et/ou changer les props des styled components afin qu'elles n'utilise pas le cloning de props du type principales.

2024-09-19 18:40 UTC, meriouma reviewed
Petits commentaires pour les tests, sinon LGTM

2024-09-19 18:40 UTC, meriouma commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +            expect(tree.find(Legend).text()).toContain('Updated Legend Text');
Commentaire général pour les tests. On essaie habituellement de séparer un peu chaque bloque logique d'un test en given/when/then en séparant avec une ligne vide. Ça permet rapidement de voir quelle action est testé et quels sont les résultats attendus.

Aussi, on a habituellement qu'un seul "when". Ici tu as deux validations, l'était initial, et ce qui se passe quand on update les props. Normalement ce serait 2 tests plutôt que d'avoir le setProps dans le milieu. Le "when" de ton premier test serait le `mountWithProviders`, alors que dans ton 2e, ce serait le `setProps`.

2024-09-19 18:40 UTC, meriouma commented on packages/react/src/components/fieldset/fieldset.test.tsx
> +            expect(tree).toMatchSnapshot();
Ici aussi ça mériterait 2 tests plutôt que d'avoir 2 snapshots dans le même test

2024-09-19 18:40 UTC, meriouma commented on packages/react/src/components/fieldset/fieldset.tsx
> +});
Je me demande si c'est pas plus simple en mettant le Legend inline plutôt qu'avec `renderLegend`
```suggestion
    const id = useId(providedId);
    const { text, ...legendProps } = legend || {};

    return (
        <StyledFieldset
            data-testid="fieldset"
            id={id}
            $orientation={orientation}
            data-orientation={orientation}
            aria-disabled={disabled}
            disabled={disabled}
            ref={ref}
            {...props /* eslint-disable-line react/jsx-props-no-spreading */}
        >
            {legend && (
                <Legend
                    {...legendProps /* eslint-disable-line react/jsx-props-no-spreading */}
                    id={`${id}-legend`}
                >
                    {text}
                </Legend>
            )}
            {children}
        </StyledFieldset>
    );
});
```

2024-09-20 15:04 UTC, WilliamsTardif commented on packages/storybook/stories/fieldset.stories.tsx
> +};
Dans le storybook, le checkbox sont aussi disabled. Est-ce que c'est voulu ?
On ne peut pas le cocher.

2024-09-20 15:04 UTC, WilliamsTardif commented on packages/storybook/stories/fieldset.stories.tsx
> +};
Le problème avec les les boutons radio ici, c'est qu'ils peuvent tous être côché. 🤷‍♂️ 
Normalement, lorsque tu selection un nouveau bouton radio, l'autre devrait être déselectionné, right ?

2024-09-23 14:44 UTC, hebernardEquisoft commented on packages/storybook/stories/fieldset.stories.tsx
> +};
C'est un bon point que tu soulève! 
J'avais posé la question au départ si on voulait gérer la logique des différents inputs, et je crois que ça se ferait dans un deuxième temps dans une composante comme `RadioButtonGroup`. @LarryMatte corrige moi si je me trompe?

2024-09-24 14:33 UTC, LarryMatte requested changes

2024-09-24 14:33 UTC, LarryMatte commented on packages/storybook/stories/fieldset.stories.tsx
> +};
Comme mentionne henri, le fieldset sert principalement à grouper des champs / composants de formulaire. Nous allons nous en tenir à ca pour le moment. Pour la logique des différents inputs, ça va être géré au niveau des composants qui vont se retrouver dans le composant Fieldset.

2024-09-25 11:44 UTC, hebernardEquisoft commented on packages/react/src/components/fieldset/styled.ts
> +    display: table;
aucune idée lol

2024-09-26 13:30 UTC, WilliamsTardif approved these changes

2024-09-28 20:18 UTC, meriouma approved these changes

2024-09-30 13:53 UTC, LarryMatte approved these changes

2024-09-30 19:34 UTC, merged