feat(Link): implements link component
kronostechnologies/design-elements pull request #953
Opened 2024-07-25 03:37 UTC by hebernardEquisoft

[DS-1132](https://equisoft.atlassian.net/browse/DS-1132)

## Description
...

## Tests fonctionnels
... critères d'acceptation

2024-07-25 14:12 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/abstract/styled.ts
> +}
Ajout de l'interface BaseButtonStyles contenant les attributs nécessaire pour le styling d'un bouton de base

2024-07-25 14:17 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/abstract/abstract-button.tsx
> +        $isMobile={isMobile}
Maintenant que le StyledAbstractButton utilise l'interface BaseButtonStyles, il était nécessaire de changer l'assignation de ceux. C'est ce qui a affecté la plus part des snapshots.

2024-07-25 15:57 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/button.tsx
>      ${getButtonTypeStyles}
Je n'ai pas déplacé ce styled button dans le nouveau fichier `styled.ts` puisqu'il causait plusieurs changements dans l'ordonnancement des attributs au niveau des snapshots pour quelques composantes. Pour éviter trop de changement, j'ai laissé ça là pour le moment.

2024-07-25 15:59 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/styled.ts
> +`;
Nouvelle fonction utilitaire réutilisable de styling permettant d'obtenir le style de nos boutons

2024-07-29 16:56 UTC, LarryMatte requested changes

2024-08-02 15:50 UTC, maboilard reviewed
Je lance la suggestion. Dans les stories, c'est un peu pêle-mêle, comme par exemple, dans "Disabled" on ne montre la version "Default" et pas les autres. Est-ce qu'il y aurait moyen d'avoir, dans un premier temps, chaque variants de la composante et, dans un deuxième temps, les états des variants concernés? J'imagine qu'on pourrait aussi avoir l'état "Visited" aussi.

2024-08-05 13:17 UTC, LarryMatte commented
> Je lance la suggestion. Dans les stories, c'est un peu pêle-mêle, comme par exemple, dans "Disabled" on ne montre la version "Default" et pas les autres. Est-ce qu'il y aurait moyen d'avoir, dans un premier temps, chaque variants de la composante et, dans un deuxième temps, les états des variants concernés? J'imagine qu'on pourrait aussi avoir l'état "Visited" aussi.

Lien vers l'état _visited_: https://www.figma.com/design/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?node-id=7070-136466&t=m8C750qmvbTzfwf9-4

2024-08-16 03:42 UTC, meriouma reviewed
Première round. Je pense que certaines des suggestions vont modifier pas mal de choses alors je referai une autre passe un peu plus tard. Il me semble y avoir une relation un peu complexe entre les différents types pour pouvoir réutiliser certaines props. Il faudrait peut-être faire une petite passe pour s'assurer que les types qui sont utilisés à certains endroits sont bien liés aux concepts dans lesquels ils sont utilisés. Si jamais ce n'est pas le cas, il faudrait peut-être faire un peu de découpage et faire des intersections.

2024-08-16 03:42 UTC, meriouma commented on packages/react/src/components/buttons/styled.ts
> +}: ButtonProps, $isMobile: boolean, theme: ResolvedTheme): FlattenInterpolation<ThemeProps<ResolvedTheme>> => css`
Je me questionne si je mettrais pas `$isMobile` et `theme` aussi dans l'objet en paramètre. Ça fait weird de les avoir après en paramètres on dirait.

2024-08-16 03:42 UTC, meriouma commented on packages/react/src/components/disclosure/disclosure.tsx
> +import { ButtonProps, Size } from '../buttons/types';
Le dossier `buttons` devraient peut-être plutôt avoir un `index` et qu'on réexport ce qui peut être utilisé en dehors du module `button`.

2024-08-16 03:42 UTC, meriouma commented on packages/react/src/components/link/types.ts
> +    buttonProps?: LinkButtonProps;
Je pense que je renommerais simplement `button` plutôt que `buttonProps`

2024-08-16 03:42 UTC, meriouma commented on packages/react/src/components/link/types.ts
> +    label?: string;
Regrouper avec
```
icon?: {
    name: IconName;
    label: string;
```

2024-08-16 03:42 UTC, meriouma commented on packages/react/src/components/link/types.ts
> +    label?: string;
Et enlever `label` d'ici. Le texte pour le link devrait être passé en children plutôt je crois.

2024-08-16 03:42 UTC, meriouma commented on packages/react/src/components/skip-link/skip-link.tsx
>  const StyledLink = styled.a<{ isMobile: boolean }>`
Ça devrait plutôt être `$isMobile` ici si ça cause pas trop de changements.

2024-08-16 18:48 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/styled.ts
> +            ${buttonType === 'destructive-primary' && css`
Stylelint y chiale quand je fais ça et j'ai aucune idée pourquoi!
J'ai ça comme erreur:
  53:9  ✖  Unexpected empty     @stylistic/block-closing-brace-empty-line-before
           line before closing
           brace

2024-08-19 14:18 UTC, hebernardEquisoft commented on packages/react/src/components/buttons/styled.ts
> +}: ButtonProps, $isMobile: boolean, theme: ResolvedTheme): FlattenInterpolation<ThemeProps<ResolvedTheme>> => css`
bin d'accord!

2024-08-26 13:28 UTC, maboilard submitted a review, later dismissed

2024-09-16 15:59 UTC, WilliamsTardif approved these changes

2024-09-16 15:59 UTC, WilliamsTardif commented on packages/react/src/components/link/styled.ts
> +export const getLinkStyles = ({
[May] Tu n'as pas besoin de export ici il me semble, puisque `getLinkStyles` est seulement appelé dans ce fichier.

2024-09-16 15:59 UTC, WilliamsTardif commented on packages/react/src/components/link/types.ts
> +    icon?: {
[May] Tu peux enlever les commentaire, sa me semble quand même _straightforward_ la définition de chaque _props_. Peut-être renommer `external` pour `exteralLink` c'est plus claire 🤷‍♂️

2024-09-20 20:16 UTC, meriouma commented on packages/react/src/components/buttons/abstract/styled.ts
> +}
Le default case sert quand `$size` est undefined. Je garderais ça comme ça, je pense que le switch rend ça plus explicite tout en étant plus compact. Avec ta suggestion il faudrait aussi dupliquer la map pour le padding.

2024-09-20 20:16 UTC, meriouma commented on packages/react/src/components/buttons/types.ts
> +     */
C'est un des _drawbacks_ d'avoir le type séparé. Le `@default` avait plus de sens quand l'interface était à côté du component. C'est vrai qu'ici c'est plus difficile d'affirmer que c'est bien le cas comme c'est enforced au niveau de la component.

2024-09-20 20:16 UTC, meriouma commented on packages/react/src/components/link/link.test.tsx
J'ai fait le commentaire dans une autre PR aussi, mais dans tes tests on a souvent plusieurs `when/then`. C'est un indice qu'il faudrait peut-être séparer au moins en deux tests.

2024-09-20 20:16 UTC, meriouma commented on packages/react/src/components/link/types.ts
> +    icon?: {
Faut que tu le vois comme `<Link external />`. Je pense que ce serait redondant d'avoir `<Link externalLink />`

2024-09-20 20:16 UTC, meriouma commented on packages/react/src/components/buttons/abstract/abstract-button.tsx
> +            // eslint-disable-next-line react/jsx-props-no-spreading
C'est un bon point, ça vaudrait peut-être la peine de la désactiver.

2024-09-24 15:03 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +    $disabled: LinkProps['disabled'],
Je ne sais pas si c'est une limitation de Storybook, mais quand je suis sur la variante _Button Link_ et dans les controls j'active l'option `disabled`, la valeur du `aria-disabled` est `[object object]` alors que ca devrait être `true`.

<img width="767" alt="Screenshot 2024-09-24 at 11 02 52 AM" src="https://github.com/user-attachments/assets/c6ddd621-3b64-432b-9e97-3e684b175491">

2024-09-24 15:19 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +    line-height: 20px;
utiliser des `rem`. Si l'utilisateur augmente la font-size dans les settings de son navigateur, et que le liens est sur 2 lignes, les lignes vont se chevaucher.

2024-09-24 15:21 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +    letter-spacing: 0.2px;
utiliser des `rem`. Si l'utilisateur augmente la font-size dans les settings de son navigateur, il se pourrait que les lettres soit vraiment collé les une sur les autres ou même qu'elles soient les une par dessus les autres.

2024-09-24 15:22 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +    padding: 0 4px;
utiliser les var que nous avons
`padding: 0 var(--spacing-half);`

2024-09-24 15:28 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +        text-decoration-color: ${theme.component['link-visited-text-color']};
Je ne crois pas que ce soit utile. Le `text-decoration-color` est surtout utilisé si la couleur du text est différente de celle de la décoration (l'_underline_ dans ce cas ci). Comme l'_underline_ va toujours avoir la même couleur que le texte, tu peux enlever la ligne.

2024-09-24 15:33 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +        text-decoration-color: ${theme.component['link-hover-text-color']};
Je ne crois pas que ce soit utile. Le text-decoration-color est surtout utilisé si la couleur du text est différente de celle de la décoration (l'underline dans ce cas ci). Comme l'underline va toujours avoir la même couleur que le texte, tu peux enlever la ligne.

2024-09-24 15:33 UTC, LarryMatte commented on packages/react/src/components/link/styled.ts
> +        text-decoration-color: ${$disabled && theme.component['link-disabled-text-color']};
Je ne crois pas que ce soit utile. Le text-decoration-color est surtout utilisé si la couleur du text est différente de celle de la décoration (l'underline dans ce cas ci). Comme l'underline va toujours avoir la même couleur que le texte, tu peux enlever la ligne.

2024-09-25 11:49 UTC, hebernardEquisoft commented on packages/react/src/components/link/styled.ts
> +    $disabled: LinkProps['disabled'],
Perso j'ai essayé et j'ai pas ça!

2024-09-25 12:19 UTC, hebernardEquisoft commented on packages/react/src/components/link/styled.ts
> +    $disabled: LinkProps['disabled'],
Par contre j'ai hit _Set object_ sur aria-disabled et en effet c'est devenu `[object object]`.

2024-09-26 19:45 UTC, WilliamsTardif commented on packages/react/src/components/buttons/types.ts
> +     */
Je comprend, alors je les enlèverais. C'est toujours mieux d'avoir moins de commentaire dans du code, surtout que celui-ci n'a pu vraiment de sens.

2024-10-10 14:05 UTC, WilliamsTardif reviewed
Le component `Link` est brisé.
<img width="1142" alt="Capture d’écran, le 2024-10-10 à 10 04 30" src="https://github.com/user-attachments/assets/a6f503c5-ec7e-427d-9dcd-f24c7c11ddc4">

2024-10-10 14:07 UTC, hebernardEquisoft commented
@WilliamsTardif avec quelles values pour les props?

2024-10-11 14:18 UTC, WilliamsTardif submitted a review, later dismissed
Le component link semble fonctionner maintenant.
Je sais pas pourquoi j'avais eu une erreur sur ma dernière review. 🤷

2024-10-15 14:05 UTC, maboilard submitted a review, later dismissed

2024-10-18 13:50 UTC, LarryMatte submitted a review, later dismissed
LGTM,
@savutsang @meriouma @pylafleur Est-ce que l'un de vous pourrait refaire une passe et donner son check si la vie est belle.
I thank you

2024-10-22 19:08 UTC, meriouma reviewed
2 petits nitpicks, sinon LGTM

2024-10-22 20:12 UTC, meriouma approved these changes

2024-10-22 20:16 UTC, merged