feat(Modal): adjust styling, adds width flexibility and header is now bold
kronostechnologies/design-elements pull request #984
Opened 2024-09-03 17:55 UTC by hebernardEquisoft

[DS-1196](https://equisoft.atlassian.net/browse/DS-1196)

## Description
Ici on vient;
1. Ajuster le styling aux [maquettes](https://www.figma.com/design/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?node-id=4-49&m=dev) de modales.
2. Ajouter une propriété `width` permettant de modifier de la modale
3. Rendre le titre de la modale en gras (`bold`)

## Tests fonctionnels
- [ ] Valider le bon fonctionnement de la composante de modale
- [ ] Valider le styling avec les [maquettes](https://www.figma.com/design/EIJItUlyeIymb2dfgeoQJp/Design-System%2C-Desktop?node-id=4-49&m=dev) design
- [ ] Valider le styling en mobile

2024-09-03 19:44 UTC, LarryMatte requested changes
Petit commentaire à valider. 
Sinon en ce qui concerne la tâche, c'est good pour moi. Je laisse les devs faire le tour pour les modifications au code.

2024-09-03 19:44 UTC, LarryMatte commented on packages/react/src/components/modal/dialog/styled.ts
> +    gap: var(--spacing-2x);
Est-ce que tu as vraiment besoin d'ajouter un `div` à l'intérieur de l'élément `<main>` pour y ajouter ces propriétés ou elles auraient pu être directement sur le `<main>`.

2024-09-03 19:44 UTC, LarryMatte commented on packages/react/src/components/modal/dialog/styled.ts
> +    gap: var(--spacing-2x);
Je comprends que le `gap` vient ajouter le même espace entre chacun des éléments, mais est-ce que ca peut être trop restrictif dans le cas où un élément a un espace moins grand que l'espace attribué ici?
Je sais que rendu là nous pourrions ajouter un `margin` négatif sur l'élément mais je pose quand même la question.

2024-09-03 19:44 UTC, LarryMatte commented on packages/react/src/components/modal/dialog/styled.ts
> +    gap: var(--spacing-2x);
@maboilard peux-tu confirmer que tous les éléments à l'intérieur d'une modale auront toujours un espace entre eux de `var(--spacing-2x)` (c'est-à-dire `16px`), peu importe les éléments qui les précèdent ou les suivent ?

2024-09-03 19:50 UTC, maboilard commented on packages/react/src/components/modal/dialog/styled.ts
> +    gap: var(--spacing-2x);
De ce que je vois, oui, mais c'est certain qu'il pourrait y avoir des exceptions.

2024-09-05 17:26 UTC, maboilard approved these changes

2024-09-05 20:52 UTC, LarryMatte commented on packages/react/src/components/modal/styled.ts
> +    padding: ${getHeightPadding} ${getWidthPadding};
ah nvm, je croyais que c'était un improvement que tu avais fait. Je viens de voir que c'était déjà comme ça. Stress pas pour ça, nous y reviendrons plus tard.

2024-09-12 16:19 UTC, savutsang commented on packages/react/src/components/modal/dialog/modal-dialog.tsx
> +const ModalRoles: Record<DialogType, string> = {
Ca ne devrait pas etre PascalCase puisque ce n'est pas un enum ou equivalent (constants pour ces valeurs), c'est plutot un mapping entre 2 types de valeurs.

```suggestion
const modalRoles: Record<DialogType, string> = {
```

2024-09-12 16:42 UTC, savutsang commented on packages/react/src/components/modal/dialog/types.ts
> +
Y a tu un structure lie a ces sauts de lignes? Ca me semble random un peu.

2024-09-12 16:54 UTC, savutsang commented on packages/react/src/components/modal/dialog/types.ts
> +
Y a tu une raison pour ces sauts de lignes? Ca me semble random un peu.

2024-09-12 17:22 UTC, savutsang commented on packages/react/src/components/modal/dialog/modal-dialog.tsx
> +    const titleId = useMemo(uuid, []);
```suggestion
    const titleId = useId();
```
https://github.com/kronostechnologies/design-elements/blob/master/packages/react/src/hooks/use-id.ts

2024-09-12 18:50 UTC, savutsang commented on packages/react/src/components/modal/dialog/styled.ts
> +export const Subtitle = styled(Heading)`
Chaque fois qu'on wrap d'un styled, ca va ajouter 2 CSS classes qui sont inutile ici. J'eviterais de faire ca.

2024-09-12 19:03 UTC, savutsang commented on packages/react/src/components/modal/dialog/styled.ts
> +export const Subtitle = styled(Heading)`
Chaque fois qu'on wrap d'un styled, ca va ajouter 2 classes CSS de plus qui ne sont pas utilise ici. 

J'eviterais de faire ca pour pas polluer le html inutilement.

2024-09-12 19:37 UTC, savutsang commented on packages/react/src/components/modal/dialog/styled.ts
> +    ${({ $dialogType, theme }) => ($dialogType === 'alert' ? `color: ${theme.component['modal-dialog-alert-icon-color']}` : '')};
Le style est plus visible de meme. Et en retournant null, il va pas output ce style.

```suggestion
    color: ${({ $dialogType, theme }) => $dialogType === 'alert' ? theme.component['modal-dialog-alert-icon-color'] : null};
```

2024-09-12 20:12 UTC, savutsang commented on packages/react/src/components/modal/styled.ts
> +export const StyledCloseButton = styled(IconButton)<ContentProps>`
Je trouve ContentProps un peu trop shared, ca devient un gros pele-mele, ca ne dicte pas exactement ce que chaque Styled a besoin.

Exemple dans l'interface ContentProps, $hasHeader est optionel. Cependant $hasHeader est requis pour StyledCloseButton, on n'utilisera jamais ce Styled sans lui passer cette info.

2024-09-14 00:38 UTC, WilliamsTardif commented on packages/react/src/components/modal/modal.tsx
>              {modalHeader && (
Pas trop sûr de comprendre à quoi cert cette condition 🤔 
`{!modalHeader && renderCloseButton()}`

2024-09-14 00:38 UTC, WilliamsTardif commented on packages/react/src/components/modal/types.ts
> +    parentSelector?: () => HTMLElement;
L'explication est t'il nécessaire ? Selon moi le code devrait être assez explicite pour qu'on puisse savoir ce que c'est props fait 🤔 .
De plus, le `Should only be used for test purposes.`. J'ignore si c'est vraiment la seule manière de le tester, mais je n'aime pas trop l'idée de créer un props juste pour les tests. 
Personnellement, il y a un truc d'agaçant ici, mais rien de problèmatique si c'est la meilleure solution dans cette situation.

2024-09-14 00:38 UTC, WilliamsTardif commented on packages/react/src/components/modal/modal.test.tsx
> +        expect(getComputedStyle(modal).width).toBe(initialWidth);
[MAY] Si ce `expect` échoue se sera dû au fait que le test a été mal initialisé. Seul le deuxième `expect` est nécessaire selon moi, car la seul raison que ce test devrais échoué, c'est parce que le width n'a pas changé correctement et non que la valeur a mal été initialisé.

2024-09-14 00:38 UTC, WilliamsTardif commented on packages/react/src/components/modal/styled.ts
> +}
[MAY] Qu'est-ce que tu pense de ça ?
Est-ce que tu trouves que c'est toujours aussi explicite que deux if ? 🤔 
Même chose plus haut.
```suggestion
function getHeightPadding({ $noPadding, isMobile }: ContentProps): string {
    return $noPadding ? '0' : isMobile ? 'var(--spacing-2x)' : 'var(--spacing-3x)';
}
```

2024-09-16 13:24 UTC, hebernardEquisoft commented on packages/react/src/components/modal/modal.tsx
>              {modalHeader && (
Si y'a pas de header, alors on vient render le close button!

2024-09-16 13:28 UTC, hebernardEquisoft commented on packages/react/src/components/modal/styled.ts
> +}
Nos règles ESLint nous empêche de faire des nested _ternary expressions_!

2024-09-16 13:31 UTC, hebernardEquisoft commented on packages/react/src/components/modal/modal.test.tsx
> +        expect(getComputedStyle(modal).width).toBe(initialWidth);
Je crois que ça reste intéressant d'avoir un test qui assure la bonne instanciation du modal width non? 🤔

2024-09-16 20:35 UTC, savutsang commented on packages/react/src/components/modal/modal.test.tsx
> +        modal.style.width = newWidth;
Il faudrait que le modif passe par le prop du component React pour que ca test que le prop width fait vraiment la job.

Je me suis rendu compte que ce test ci utilisait plutot testing-library: https://testing-library.com/docs/example-update-props/

2024-09-16 20:40 UTC, hebernardEquisoft commented on packages/react/src/components/modal/modal.test.tsx
> +        modal.style.width = newWidth;
Ouin j'ai hésité!
Mais les deux fonctionnent!

2024-09-17 14:45 UTC, savutsang commented on packages/react/src/components/modal/styled.ts
> +    top: ${getHeightPadding};
```suggestion
    pointer-events: none;
    position: absolute;
    right: ${getWidthPadding};
    top: ${getHeightPadding};
    
    & > * {
        pointer-events: auto;
    }
```

2024-09-24 14:39 UTC, LarryMatte approved these changes
Je laisse les devs juger du code mais en ce qui me concerne, c'est good.

2024-09-27 15:12 UTC, WilliamsTardif approved these changes

2024-10-08 13:10 UTC, merged