feat(SegmentedControl)!: new Style and add icon
kronostechnologies/design-elements pull request #995
Opened 2024-09-19 14:15 UTC by LarryMatte

DS-1231

- Modifier le style du composant
- Ajout option d'avoir des icônes ou non
- Ajout option d'avoir tjrs un bouton de pressed
- Modification dans les tokens du composant (Breaking change)

2024-09-19 17:38 UTC, savutsang commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +    ariaDisabled: boolean;
A enlever, ce n'est pas utilise.

2024-09-19 17:43 UTC, savutsang commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +    requireSelection?: boolean;
On utilise `required` dans les autres controls, on devrait garder le meme nom

2024-09-19 17:48 UTC, savutsang commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +    requireSelection?: boolean;
On utilise `required?: boolean;` dans les autres controls. Meme si c'est pas un champ de formulaire, ca reste que c'est un contrainte de requis. Je reutiliserais le meme nom.

2024-09-19 18:48 UTC, savutsang commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +    requireSelection?: boolean;
Il y a de quoi qui me tracasse avec ca, ce prop est attache a un couple de comportements ici et la mais c'est pas SI clair que ca ce que require implique.

Je pense c'est mieux avec un prop `toggleable`, si c'est true, le user peut toggle off.

Pour le default, le dev n'a qu'a mettre un defaultPressed. Je ne pense pas qu'on n'a besoin d'ajouter plus que ca.

2024-09-20 14:32 UTC, savutsang commented on packages/react/src/components/segmented-control/segmented-control.tsx
>          disabled?: boolean;
Ce disabled n'est plus passe au bouton, il n'est plus utilise.

2024-09-20 14:34 UTC, savutsang commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +        ariaDisabled?: boolean;
Relie au commentaire precedent, je pense qu'on devrait renommer `ariaDisabled` a `disabled`, le comportement c'est disable, `aria-disabled` c'est l'implementation qu'on utilise pour faire le disable.

2024-09-20 16:23 UTC, savutsang submitted a review, later dismissed

2024-09-23 13:01 UTC, maboilard requested changes
Quelques commentaires :
- Le border-radius de l'état hover semble être de 8px mais dans Figma il est de 4px
- Dans l'état hover, le padding-left et right devrait être de 4px et identique au padding-top et bottom
- Le letter-spacing du texte lorsqu'une option est pressed semble beaucoup plus prononcé que ce qu'il y a dans Figma

2024-09-25 14:18 UTC, maboilard approved these changes
LGTM!

2024-09-26 13:50 UTC, WilliamsTardif approved these changes

2024-09-30 00:08 UTC, meriouma reviewed
LGTM

2024-09-30 00:08 UTC, meriouma commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +        label?: string;
Ce bout là m'embête. Il n'y a plus aucune prop d'obligatoire à par la value. Je pense qu'on l'a pas encore fait ailleurs alors ça pourrait être fait plus tard, mais on pourrait rendre le type plus complexe et plus restrictif pour s'assurer que ce sont les bonnes combinaisons de props, genre soit `label` obligatoire et `ariaLabel` facultatif, `icon` + `label` obligatoires et `ariaLabel` facultatif, ou `icon` et `ariaLabel` obligatoires. Mais comme je disais, on peut réfléchire à ça dans un 2e temps pour resserrer l'usage.

2024-09-30 00:08 UTC, meriouma commented on packages/react/src/themes/tokens/component/segmented-control-tokens.ts
> +    | 'segmented-control-text-color'
La prop est là 2 fois. Tant qu'à rebrasser, tu devrais les mettre en ordre alphabétique, ce serait plus simple à lire.

2024-09-30 02:06 UTC, LarryMatte commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +                    aria-label={button.ariaLabel || undefined}
Dans le cas où il y a seulement une icône, il n'y aura pas de label

2024-09-30 15:51 UTC, meriouma commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +                    aria-label={button.ariaLabel || undefined}
Mais dans le cas où il y a un `button.label`, mais pas de `button.ariaLabel`, est-ce qu'on veut quand même un `aria-label` avec `button.label` comme valeur?

2024-09-30 17:31 UTC, LarryMatte commented on packages/react/src/components/segmented-control/segmented-control.tsx
> +                    aria-label={button.ariaLabel || undefined}
Si c'est seulement une icône qui est affichée et qu'il n'y a pas d'`aria-label` de _set_, il va _fallback_ sur le `button.label` qui n'est juste pas existant.

2024-09-30 19:00 UTC, pylafleur approved these changes
LGTM!

2024-09-30 19:34 UTC, merged